### ISSUE TITLE
Mint-X-Dark for Window borders

### ISSUE THREAD

**Issue by cruftytheclown** [linuxmint/mint-themes#104]
I wish there were a Mint-X-Dark theme for Window borders. I don't like the look of the Mint-Y-Dark exit button.

**Comment by JosephMcc** [comment]
There is no plan to do this. We already support a good number of themes.

**Comment by cruftytheclown** [comment]
A dark theme counterpart to the default light mint theme seems desirable to me, and not akin to merely requesting a greater number of themes. But I hear you
