### ISSUE TITLE
Mint Themes 1.6.1 Gtk3-2.x ready?

### ISSUE THREAD

**Issue by mdinslage** [linuxmint/mint-themes#106]
I see that you released a new mint-x theme version a few days ago, I was just wondering if these are now compatible with the new gtk-3.2x or are they still for gtk-3.1x?

Thanks

**Comment by JosephMcc** [comment]
Mint-X is not ready for gtk3.20+ yet. Will be working on it very soon. Mint-Y is in decent shape for it but still needs some work.

**Comment by JosephMcc** [comment]
They are being merged into one package.
