### ISSUE TITLE
Mint-X Vertical Scroll Bar behaves incorrectly

### ISSUE THREAD

**Issue by GarethAdamson** [linuxmint/mint-themes#107]
Clicking near the right edge of the slider in the vertical scroll bar causes the slider to move. This happens only in Mint-X themes. (Slider with rounded ends and shadowed edge.)

To exercise the bug: open a long document or web page, or a big directory in Nemo. Anything big enough to have a vertical scroll bar. Click near right hand edge of vertical slider to exercise the bug. Click elsewhere on the slider to see expected behaviour.

Expected behaviour: slider stays where it is. (In some themes it flashes, but not Mint-X.)

Actual behaviour: slider moves as if the click were in the trough below the slider. In warp mode (default), the slider centers on the click. In page mode (with SHIFT key or gtk-primary-button-warps-slider = false in ~/.config) it moves down one page-full.

This behaviour overrides my touchpad's double-click-to-drag feature, so that when I try to drag the slider, if my pointer is too far to the right, it runs away from me! But a single click is enough to exercise the basic bug.

Observed on
Linux Mint 18.3 64-bit
Cinnamon 3.6.7+sylvia

**Comment by GarethAdamson** [comment]
Bug does not occur in some apps that perhaps use their own widgets, e.g. LibreOffice.

It does occur in Nemo, xed and Firefox.

**Comment by xenopeek** [comment]
I can confirm this observation on Linux Mint 18.3 Cinnamon with Mint-X theme and testing in Xed. Clicking just a pixel right of the slider control on the vertical scroll bar, that centers the slider on that position — scrolling you a short stop up or down while you intended to grab the slider control and drag it up or down.

**Comment by JosephMcc** [comment]
I can no longer reproduce this in Mint19. I few tweaks happened to the scrollbar in the process of updating it for gtk3.22.
