### ISSUE TITLE
Poor contrast with active window in MATE window list

### ISSUE THREAD

**Issue by bwat47** [linuxmint/mint-themes#131]
This could be subjective, but IMO there's a big contrast issue with the Mint-Y theme under MATE.

The active window in the MATE window list gets a very light green highlight (and has white text).

This bright highlight + light text is pretty difficult to read, and is kind of an eye sore over time since you almost always have an active window in the window list

![untitled](https://user-images.githubusercontent.com/1442520/41630109-5b4088fa-73fb-11e8-8467-32ac433afe34.png)

**Comment by xenopeek** [comment]
Thanks for sharing your feedback. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by JosephMcc** [comment]
I'm taking a look at this as part of the updates for Mint19.1.
