### ISSUE TITLE
Window list items have no borders in Mint Mate 19

### ISSUE THREAD

**Issue by Tensori** [linuxmint/mint-themes#132]
Window list items in the Mate panel are right next to each other without any borders. Only the active window and a hovered window does have borders.

OS is Mint Mate 19 64-bit. Problem occurs all the time, no further actions needed to reproduce.
![screenshot at 2018-07-05 14-11-23](https://user-images.githubusercontent.com/40865346/42333435-6ad213da-8083-11e8-98f2-9a0e4ea7cc94.png)

**Comment by mtwebster** [comment]
What theme are you using? (Gtk theme)

**Comment by Tensori** [comment]
I have tested almost all available vanilla themes, and the issue exists with all of them: Mint-X, Mint-X-Aqua, -Brown, -Orange, etc., and Mint-Y themes as well. Window border setting has no positive effect either; have tried Spidey, Splint, WinMe, ClearlooksRe and of course Mint-X/Y - but the window list keeps being borderless.

**Comment by JosephMcc** [comment]
I can look at improving this in the next release if it's what people want to see. The "no borders" look seems to be pretty common for the mate panel in many themes.

**Comment by Tensori** [comment]
So is this designed feature or a bug? If this is a feature, what parameters I need to change in the theme files?

**Comment by mdinslage** [comment]
I have also begun working on this and have it looking about 90% what is was with the GTK 3.18 version.  Personally, I would like to see the mate panel restored to the old 3.18 look.  It doesn't look bad now, but I think it looks better the way it was.

**Comment by mdinslage** [comment]
Yeah, here is the old look
![before3](https://user-images.githubusercontent.com/28424337/42361427-00cd2282-80b4-11e8-9581-bb70ad556db3.png)

**Comment by JosephMcc** [comment]
Ok. Thank you. I have to agree I think that looks better.

**Comment by Tensori** [comment]
![screenshot at 2018-02-22 18-55-12](https://user-images.githubusercontent.com/40865346/42363502-9f5d916a-8100-11e8-94df-089177a6584d.png)
Here's a screenshot of items when they are squeezed. I still wonder, what causes this?

**Comment by JosephMcc** [comment]
Alright the old look is now restored: https://github.com/linuxmint/mint-themes/commit/08ac3acaeb0451b12dcc1a735237086c50c7adf2
