### ISSUE TITLE
Old Pane Separator Look?

### ISSUE THREAD

**Issue by mdinslage** [linuxmint/mint-themes#133]
@JosephMcc Thank You for restoring the old mate-panel look, it looks just like 18.3 now.   I am not trying to beat a dead horse here and this is the last time I am going to bring up this issue.  Essentially everything looks the way it should now with Mint 19, it even looks better IMO, because the tab alignment and your small tweaks have made it better.  The last lingering thing is the new pane separator look.  It doesn't look bad but I still prefer the old 18.3 look.  I just fix the code on my own machine to the old look so its a non issue for myself, but I was wanting to get opinions from others on what they think about the new look.  Is the old look or new look better?  Below is a screenshot. Left is 19, right is 18.3.   

![pane-sep](https://user-images.githubusercontent.com/28424337/42415353-f14a3bf2-8210-11e8-9166-ebbf34b56612.png)

**Comment by JosephMcc** [comment]
Thanks, but as I noted before. If you want this to "just work" and it's the style intended by the mate devs, request them to give it the "wide-separator" style class. Caja is on github :)

**Comment by mdinslage** [comment]
Understood.  Thanks again for everything :)
