### ISSUE TITLE
Apply Mint-Y theme to the Desktop panel too for completeness

### ISSUE THREAD

**Issue by uncertainquark** [linuxmint/mint-themes#134]
In Linux Mint 19, the GTK theme is switched to Mint-Y theme but the Desktop panel theme is still left out to the old one. Applying Mint-Y theme to the Desktop panel gives a much more complete and sleeker look as seen below. 

1. Linux Mint Desktop panel theme as it is right now in Mint 19:
![01-mint-panel](https://user-images.githubusercontent.com/22585732/42420353-27ac4db2-82e2-11e8-91ac-3168395210f7.png)
![01-mint-panel-cal](https://user-images.githubusercontent.com/22585732/42420354-27e85410-82e2-11e8-841c-393ca5069183.png)

2. Linux Mint-Y Desktop panel theme applied (look at the app menu and calendar especially)
![01-minty-panel](https://user-images.githubusercontent.com/22585732/42420363-3c7251ba-82e2-11e8-8048-01d78396af21.png)
![01-minty-panel-cal](https://user-images.githubusercontent.com/22585732/42420364-3cc28162-82e2-11e8-9c39-f8f201df74f0.png)

Switching to the Mint-Y theme for the Desktop panel improves consistency and look and feel.

**Comment by JosephMcc** [comment]
Thanks for the suggestion. We constantly review this type of thing with each new release. We'll keep this suggestion in mind.
