### ISSUE TITLE
Terminal app needs to be fully dark

### ISSUE THREAD

**Issue by uncertainquark** [linuxmint/mint-themes#135]
Every interface (GNOME, elementary, Unity, Mac, etc.) that have a dark theme for the terminal, have it dark throughout. As such, it is odd looking when the Mint terminal opens up to a mix of dark and light themes. 
![05-terminal-light](https://user-images.githubusercontent.com/22585732/42420538-c6b38a72-82e4-11e8-910a-558145e541bf.png)

Make the terminal theme dark by default.
![05-terminal-dark](https://user-images.githubusercontent.com/22585732/42420542-dc191224-82e4-11e8-88b5-ad6ebd1d91df.png)

Little things like these will go long way in UX polish. :)

**Comment by JosephMcc** [comment]
Thanks for the suggestion. As clem noted in another post, we have some technical limitations in our way for doing this currently. This also is just a theme issue. It's down to the defaults for each individual application. This is how I personally set up my system.

We'll keep this in mind moving forward though.
