### ISSUE TITLE
Files app theming looks weird with incosistent use of white and dark elements

### ISSUE THREAD

**Issue by uncertainquark** [linuxmint/mint-themes#136]
Files app under Mint-Y theme has inconsistent use of dark and light elements.

![06-files-light](https://user-images.githubusercontent.com/22585732/42420582-61ce6c48-82e5-11e8-828a-7a24a8534ed4.png)

Either make the app theming fully light by default or make the top part dark like this.

![06-files-dark](https://user-images.githubusercontent.com/22585732/42420587-764c2836-82e5-11e8-8e2e-eaeb2b6db00a.png)

**Comment by JosephMcc** [comment]
Thanks for the suggestion. I wouldn't hold my breath on this changing though. That has been the style used in Mint's themes for as long as I remember. It's also very easy just to switch to Mint-Y-Darker which accomplishes many of the things that you've opened.
