### ISSUE TITLE
Photo manager should be dark by default

### ISSUE THREAD

**Issue by uncertainquark** [linuxmint/mint-themes#138]
elementary OS, macOS and GNOME all have made a very nice decision to make the photo manager as dark by default, as it caters to the use case of images and enhances the purpose.

It would be nice to do the same for the Photo manager on Mint. Here are comparisons of the current light theme vs the Mint-Y dark theme applied.

![07-photos-light](https://user-images.githubusercontent.com/22585732/42420714-6f9944fe-82e7-11e8-971f-5a7cb427bd52.png)
![07-photos-dark](https://user-images.githubusercontent.com/22585732/42420718-741903a2-82e7-11e8-9c04-db313129b851.png)

**Comment by clefebvre** [comment]
@uncertainquark please don't open an issue for each app :)

We're considering adding dark support in Mint-Y. We didn't do it yet because of compatibility issues with MATE. We're still looking into it for 19.1.

**Comment by uncertainquark** [comment]
Okay, sorry! I will just mention the remaining one here in that case. Media player should also utilize dark mode in 19.1 hopefully. :)

![11-media-light](https://user-images.githubusercontent.com/22585732/42420885-30fe9bf6-82ea-11e8-9396-61ac337d722f.png)
![11-media-dark](https://user-images.githubusercontent.com/22585732/42420890-34a8f3aa-82ea-11e8-867b-d42bada170e7.png)
