### ISSUE TITLE
Use "Breeze icons" in Libreoffice instead of "Tango" for consitentcy with the rest of Mint 19 

### ISSUE THREAD

**Issue by uncertainquark** [linuxmint/mint-themes#139]
Breeze has nice symbolic icons which go nicely with the look and feel of the rest of Mint 19. Comparison of Tango vs. Breeze:

![10-lo-writer-tango](https://user-images.githubusercontent.com/22585732/42420922-ceab937c-82ea-11e8-97ad-8f0e9bc094c5.png)
![10-lo-writer-breeze](https://user-images.githubusercontent.com/22585732/42420923-d41db4e8-82ea-11e8-8490-7fc58f531e6b.png)

**Comment by JosephMcc** [comment]
Thank you for the suggestion. I think some changes here are already in our roadmap and we'll keep this in mind.
