### ISSUE TITLE
[Mint-X gtk+ 3] Scrollbar regression from 3.18

### ISSUE THREAD

**Issue by mrnhmath** [linuxmint/mint-themes#140]
The trough of the scrollbar is too small to fit the slider in. Mint 18.3 with gtk+ 3.18 looked fine.

![captura de tela em 2018-07-13 13-10-56](https://user-images.githubusercontent.com/13562431/42701959-5765bd12-869e-11e8-9dc5-4f04260e3cd5.png)

**Comment by JosephMcc** [comment]
The gaps between the scrollbar and the trough in previous versions were actually the cause of an issue: https://github.com/linuxmint/mint-themes/issues/107

Having them fit edge to edge fixes that annoying behavior.

**Comment by mrnhmath** [comment]
That was quick, thanks for the clarification.

**Comment by JosephMcc** [comment]
No problem. You just had really good timing :)
