### ISSUE TITLE
Mint-Y dark in Thunderbird: unreadable tooltip

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mint-themes#141]
Thunderbird 52.9.1, using the default Thunderbird theme and Mint-Y global theme.

Screenshots:

![image](https://user-images.githubusercontent.com/9998846/43305106-5cc991d6-916e-11e8-8af3-6b6a8718de6f.png)

Note the tooltip with white text on a yellow background.

![image](https://user-images.githubusercontent.com/9998846/43305142-7c01e86e-916e-11e8-8fe1-31a32edaad5e.png)

**Comment by JosephMcc** [comment]
As I've noted many times in the past, some apps simply do not work well with full dark themes. Thunderbird is one of those. Just look at the styling of the buttons in your screenshot. That is coming from the theme. Thunderbird is pulling certain things from the gtk theme and basically "doing what it wants" with them.

**Comment by CottonEaster** [comment]
Someone should file a bug report with Mozilla. For, it is important that such a standard application looks decent with one of Mint's standard themes - no? I will file that report myself.

**Comment by JosephMcc** [comment]
This has been an issue forever. They don't use the full gtk theme. Firefox has improved, though still isn't perfect, so maybe it will improve eventually in Thunderbird.

**Comment by CottonEaster** [comment]
I have filed a bug report - which cites extant bug reports for both Thunderbird and Firefox - with Mozilla, [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1479872).

**Comment by CottonEaster** [comment]
It transpires that _the problem can be solved in Thunderbird_ - even the existing version of Thunderbird - via the right settings; see [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1479872).
