### ISSUE TITLE
Firefox bookmark separators not visible

### ISSUE THREAD

**Issue by mastermind4** [linuxmint/mint-themes#143]
Firefox bookmark separators under the Bookmarks Toolbar are invisible or nearly invisible (depending on theme) in Linux Mint 19.  Can this be fixed?  Or, is this due to Firefox's incomplete GTK implementation?

![bookmark_separators](https://user-images.githubusercontent.com/4398206/43482663-550d04a2-94d7-11e8-91bf-68341e8db074.png)

**Comment by JosephMcc** [comment]
Thanks for the feedback. This was a design choice but they should be coming back for Mint19.1
