### ISSUE TITLE
Mint-X-Gtk3: Invisible entries in LibreOffice's spinbuttons

### ISSUE THREAD

**Issue by mrnhmath** [linuxmint/mint-themes#144]
Linux Mint 19 MATE, LibreOffice 6.0.3.2

![captura de tela em 2018-09-01 18-07-36](https://user-images.githubusercontent.com/13562431/44949931-16cd5580-ae12-11e8-817d-a638df99fe7b.png)
![captura de tela em 2018-09-01 18-08-45](https://user-images.githubusercontent.com/13562431/44949933-1765ec00-ae12-11e8-901d-d4e17d925918.png)

**Comment by JosephMcc** [comment]
Thanks for the report. I'll try to look into this when I get a chance.

**Comment by JosephMcc** [comment]
I couldn't find the specific dialogs you are showing there but the ones I could find all displayed correctly in current versions of LibreOffice.

**Comment by howdev** [comment]
Not just in Libroffice. The spin does not display content when selected with Mint-Y  light themes. Mint-Y-dark don't have this problem. I can give you screenshots.
