### ISSUE TITLE
Mint-X-Grey shipping with default Mint-X image assets.

### ISSUE THREAD

**Issue by smurphos** [linuxmint/mint-themes#145]
https://github.com/linuxmint/mint-themes/tree/master/src/Mint-X/variations/Grey is missing a bespoke Cinnamon folder with Grey image assets.

All of the other Mint-X variations are shipping with appropriately recoloured image asset for the Cinnamon theme.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mint-themes/commit/44239e7352844c403106ef9a0f96ade3b3c98a2e
