### ISSUE TITLE
Menu separators are missing

### ISSUE THREAD

**Issue by GitHubIsToxic** [linuxmint/mint-themes#146]
Menu separators are missing/invisible in all variants of Mint-X and Mint-Y themes.

Ok, actually they are not missing, but geeeze guys, they are ~1px high, have ~0-2px vertical spacing, and have the _same color as the menu background_!!
```
.separator {
  -gradient-height: 1px;
  -gradient-start: transparent;
  -gradient-end: transparent;
  -margin-horizontal: 1.5em;
  height: 1em; }
```
That is NOT a separator! Separators occupy space. They appear as a divider between other menu items. Separators actually serve a purpose, and by design be visible to the user.

[rant]
I understand hiding separators makes the menus design aesthetically cleaner, and easier on the eyes, I won't argue with that reasoning even, because it is true. But let's not reduce and simplify and reduce and simplify again, iterate, forever, until the Cinnamon UI to becomes dysfunctional. Leave that to Microsoft, Gnome and other incompetents, who have lost their way. Know when to stop. Functionality *does* matter, and should always triumph over 'good looks'. That's the very reason of the success of Linux Mint, from the very beginning. Good looks AND functional. That's why I use Mint in the first place.
[/rant]

Also keep in mind, that some software (like Firefox) overrides and strips the margin on menu items to make their menus more compact. In Firefox for example, the current Mint-Y separators are exactly 1 pixel high, and invisible. It is currently practically impossible to identify, locate, drag or delete separators in the Bookmarks menu.

FYI, I made a modified Mint-Y theme adding back separators, this looks reasonable *and* functional:
```
    margin: 4px 10px;
    background-color: #eee;
```
(I was going to attach screenshots, but it is impossible to take screenshots when menus are open in Linux)

**Comment by JosephMcc** [comment]
The invisible menu separators was a style choice we inherited from the original Arc themes. They are coming back in Mint19.1.

> (I was going to attach screenshots, but it is impossible to take screenshots when menus are open in Linux)

Use something like Shutter that allows setting a delay. You can take the screenshot and open the menu before it actually happens.

**Comment by GitHubIsToxic** [comment]
Great, glad to hear that!

And thanks for reminding me about that workaround, I realize I've used it in the past. Another way is via desktop sharing and taking the screenshots on Windows (which is rather sad).

**Comment by vassilisw** [comment]
Great to hear indeed. I was pointed the issue at the very beginning of Y theme, but the guys just told me that it is by design and that's it. So what? Maybe we have to insist? anyway...
