### ISSUE TITLE
[Mint-Y] More colors

### ISSUE THREAD

**Issue by utkumaden** [linuxmint/mint-themes#148]
Mint-X has multiple color choices which is great, as not everyone likes the default green Linux Mint has shipped with for the longest time. (Like yours truly)

Why isn't the Mint-Y theme compiled(?) with multiple colors yet. As far as I remember it's been a while since it has been out. The icon themes have the colors. Probably wouldn't take long to write a script that generates the necessary files.

For example, I prefer the color blue for user interfaces; as I am used to it. But I have to either use the blue icon theme with green Mint-Y widgets and windows, which looks ugly; or use the blue Mint-X variant with which doesn't really match with the aesthetic of the Mint-Y icons. So overall I have to use the old theme to have a nice looking desktop experience.

**Comment by JosephMcc** [comment]
Thanks for the suggestion. These are coming. The new theme was made default for the first time with Mint19. This turned up some other things that needed improvement. Wanted more of those ironed out before doing more colors.
