### ISSUE TITLE
Mint-Y & Caja file manager: Extra panel on (F3), select 2 files in list view = file disappeared !

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint-themes#153]
Please excuse any bad English. See image file below to get a clear understanding. The problem described here does not occur in Mint-X, so it really is a problem in Mint-Y.

**Steps to reproduce the behavior:**
- Open Caja file manager (i am on Linux Mint Mate 18.3 32-bits)
- Press F3 to get extra panel
- Set both views in list mode
- Select one file in the first panel and another one in the second panel

**Expected behavior:**
Both files being selected, both files being displayed with white letters on mint background color.

**Actual behavior:**
The first file disappeared (white text on white background) and the second file looks ok. **(See included picture)**

![caja-extrapanel-bug](https://user-images.githubusercontent.com/31940713/47256700-2bad8900-d452-11e8-82a5-920343b325e8.png)

**Note:**
I solved this problem on my computer, here is the trick. The line numbers correspond to `Mint-Y/gtk-3.0/gtk.css` version supplied with Linux Mint Mate 18.3. (Why can't we get the updates like they do in LM 19?)
File: `Mint-Y/gtk-3.0/gtk.css`
**Add** the following lines **under** line 3587:
```
.cell:selected, .cell:selected:focus, .cell:selected:hover {
  background-color: #9ab87c;
  background-image: linear-gradient(to bottom, #9ab87c, #9ab87c);
  color: #ffffff; }
```
**Strange**: for some reason, it doesn't work with just "background-color". A fake, flat linear-gradient must be used.

**Comment by Zuko** [comment]
Same problem on Mint 19 (Mate)

**Comment by JosephMcc** [comment]
Closed by https://github.com/linuxmint/mint-themes/commit/9669d616a6b4f1d3232853a10daa64fe7a930da9
