### ISSUE TITLE
Mint-Y color changer

### ISSUE THREAD

**Issue by HattDroid** [linuxmint/mint-themes#156]
Hi,

I've just updated Mint-Y color changer to support the recent updates of Mint-Y and the new repository it's been hosted on.
Here's the link:
[https://github.com/HattDroid/Mint-Y-Colora-Theme](https://github.com/HattDroid/Mint-Y-Colora-Theme)

For info, the original color changer project doesn't work anymore with the current Mint-Y theme, hence the reason behind this fork.

Hope this could help people looking to change the default accent color of Mint-Y and that we could have this option merged at some point (the current project I have linked is based on former code and can be made more robust and simple).

Thanks.

**Comment by smurphos** [comment]
You should post about this on the Mint forums - https://forums.linuxmint.com/viewforum.php?f=211

**Comment by HattDroid** [comment]
Thank you for the advice, just did it here: 
[https://forums.linuxmint.com/viewtopic.php?f=211&t=280509](https://forums.linuxmint.com/viewtopic.php?f=211&t=280509)

**Comment by clefebvre** [comment]
Very nice. I'll keep this open a bit for people to find it easily.

It's also going to help us a bit (we're planning to ship more deviations in 19.1). Thanks.

**Comment by clefebvre** [comment]
I'll close this now, part of it was integrated in the way we generate deviations.
