### ISSUE TITLE
linux mint 19 libre office cannot change hyperlink color

### ISSUE THREAD

**Issue by mrgenericuser** [linuxmint/mint-themes#170]
linux mint 19 - libre office - cannot change hyperlink color.  It stays mint green no matter what I do, and it affects the print color as well.

**Comment by JosephMcc** [comment]
I'll have to admit to not being familiar with LibreOffice. Is this still an issue and if it is, could you give steps to reproduce it?

**Comment by mrgenericuser** [comment]
Sorry for the late reply.

Yes, it is still an issue for me.
Still using Linux Mint 19 Cinnamon.

LibreOffice Calc
Version: 6.0.7.3
Build ID: 1:6.0.7-0ubuntu0.18.04.10

Steps to reproduce:

place cursor in a cell, i.e. A1
[Menu :: Insert] -> Hyperlink
Web
URL: https://www.google.com/
Form: Text
Text: A Site
[OK]

[Menu :: Styles] -> Manage Styles
[Styles Frame] -> Hyperlink -> [right click] -> Modify
[Window :: Cell Style: Hyperlink] -> [Font Effects Tab] -> change font
color to any other color
[Window :: Cell Style: Hyperlink] -> [Background Tab] -> change background
color (in my case, to No Fill)
[OK]

Even creating a new hyperlink does not take the color changes.  I do not
know if the cinnamon theme is overriding libreOffice, but I don't think it
is supposed to do that within the content of a document unless a document
is somehow set to use a system default, as formatting of a document is
something the document should have the ability to control and override.

I hope this makes sense and is helpful.  If you have any further questions
please let me know.
--randall

**Comment by JosephMcc** [comment]
Sorry for taking so long to answer. I lost track of this. In testing I don't see a way to fix it from the theme. Even trying multiple different themes, the problem still exists.
