### ISSUE TITLE
Linux Mint 19.1 Beta: Color variations of the Mint-Y theme do not apply color changes to some buttons

### ISSUE THREAD

**Issue by mattvalley** [linuxmint/mint-themes#171]
### Summary
When I select a color variation of the Mint-Y theme for the Controls option, the color change is not applied to some of the buttons in various apps.  Here are a couple of example screenshots after choosing the Mint-Y-Aqua theme where some of the buttons are still green from the initial theme.

![calculator_theme](https://user-images.githubusercontent.com/4983376/49492239-bb49a400-f814-11e8-8313-656202d8870b.png)

![xed_theme](https://user-images.githubusercontent.com/4983376/49492248-c13f8500-f814-11e8-9af9-6c21f2c1417b.png)

### Environment
Linux Mint 19.1 Beta - 64bit Cinnamon Edition

### Steps to Reproduce
- Fresh install of Linux Mint 19.1 Beta
- Go to the Themes screen in System Settings
- Change the Icons to Mint-Y-Aqua
- Change the Controls to Mint-Y-Aqua
- Change the Desktop to Mint-Y-Dark-Aqua
- Restart the system and log back in
- Open the Calculator app (gnome-calculator)
- Notice the equals button in the bottom-right corner is still green from the initial theme
- Open the Text Editor app (xed)
- Type in some text and click the Close window button (without saving first)
- Notice the "Save As..." button in the dialog prompt is still green from the initial theme

### Additional Details
- I tried changing only the Controls option while leaving the rest with the default selection and still saw the same behavior.  I also tried selecting other color variations (light and dark) of the Mint-Y theme and saw the same behavior.
- The color variations of the Mint-X theme are still working correctly.

**Comment by JosephMcc** [comment]
This is actually intentional. Those buttons are marked as suggested and destructive action buttons. They are kept green and red respectively in all the variations.

**Comment by mattvalley** [comment]
Makes sense.  Thank you for clarifying.
