### ISSUE TITLE
[Mint-X] GTK3 file chooser's side pane: dark background (same as Mint-Y)

### ISSUE THREAD

**Issue by ohque** [linuxmint/mint-themes#172]
After playing around a bit with 19.1 beta CInnamon edition I noticed that GTK3 file chooser's side pan (home dirs and bookmarks on the left side) is much more readable in Mint-Y theme. The main reason is that "-symbolic" icons look much clearer against dark background (perhaps dark background should become a standard wherever symbolic icons are used). It's also more consistent with how Nemo is themed and so makes the file chooser feel more like part of the file manager, which should be an ideal in any DE in my opinion.

I still prefer Mint-X theme due to its readability and discernability at a glance, mostly due to better contrasts and depth - or lack of flatness. I'm aware that is merely subjective. Yet the file chooser is the one thing where Mint-Y theme is much better.

If you can point me to the correct CSS selectors for the file chooser I'll try to write the patch myself.

And thanks for the wonderful distro.

**Comment by JosephMcc** [comment]
Sorry for never responding to this. At this point I don't think we have any intention of changing the design. If you want to do it yourself you could always find the theming in Mint-Y and port it to Mint-X. You'd be looking for filechooser and sidebar.
