### ISSUE TITLE
Suggestion: enlarge scrollbar width by some 30%

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mint-themes#176]
The size - lack of width - of scroll bars (non-overlay and overlay-when-visible) is such as to make them fiddly to use. The only ways the user can change the width - to my knowledge - is by changing (to a third-party?) theme or editing css. An increase of 30% in width would little affect the aesthetics - and amount to only a few pixels - but would, I suspect, give just enough extra width to increase usability ('grabability').

I have moved this from the Cinnamon bugtracker (specifically: [here](https://github.com/linuxmint/Cinnamon/issues/8143)), having been told, understandably, that was the wrong place for it. I imagine that this - here - _is_ the right place for it.

**Comment by JosephMcc** [comment]
Thanks for the suggestion and this is the correct place. There are currently no plans to change this however.
