### ISSUE TITLE
Panel window list suggestion: different style for minimized windows

### ISSUE THREAD

**Issue by s44i7h-sam** [linuxmint/mint-themes#177]
Currently minimized windows are distinguished by the square brackets. However that is visually a very poor indicator. For example, visually searching among a few minimized terminal windows for that single "un-minimized" terminal window that you're currently working in is very frustrating since you often mistake a minimized one for the opened one. It's a design that makes the user behave by trial and error.

Instead I suggest that *opened* ("un-minimized") windows standout in some graphical rather than textual way, just like the currently focused window does. This could be achieved by making the label font of *minimized* windows somewhat darker - a gray font color.

**Comment by JosephMcc** [comment]
Sorry but the theme currently has no control over this. Cinnamon itself draws those bracket indicators.

**Comment by s44i7h-sam** [comment]
But the issue is not with the existence of those brackets. It's about the absence of any *theming* of the minimized windows. Is there no CSS class for minimized windows?
