### ISSUE TITLE
Transparency glitch with Mint-X

### ISSUE THREAD

**Issue by Janne-d-Arc** [linuxmint/mint-themes#179]
```
 * Cinnamon version 4.0.8
 * Distribution: Linux Mint 19.1 Cinnamon
 * Graphics hardware *and* driver used: GeForce 950 with Nvidia Drivers 390.77
 * 64 bit
 ```

**Issue**
Dragging a Terminal window over another window causes a transparency glitch (the window in the background is not visible or if the other application is maximized, it is possible to see the desktop background in the Terminal window) when the "Mint-X" theme is used. 

**Steps to reproduce**
Opening a Terminal and a window of any other application, when dragging the Terminal window over the second window will cause the background window not to be visible or only its shadow will be visible.

**Expected behaviour**
Transparency should work as when the "Mint-Y" theme is used.

**Other information**
Enabling the "Use transparent background" option along with "Use transparency from system theme" in the Terminal preferences seems to solve the problem but this is not necessary when the "Mint-Y" theme is used.

![screenshot from 2018-12-23 20-09-32](https://user-images.githubusercontent.com/13596575/50436405-634e0c80-08ab-11e9-95c6-b4d9475d5adb.png)
![screenshot from 2018-12-23 20-10-05](https://user-images.githubusercontent.com/13596575/50436412-6a751a80-08ab-11e9-86a7-beab8909fd2e.png)
![virtualbox_linux live_26_12_2018_01_07_51](https://user-images.githubusercontent.com/13596575/50436421-6f39ce80-08ab-11e9-8352-2c7a26c80bc1.png)

**Comment by pyroxar** [comment]
Did this bug is still present? I can't reproduce this.

**Comment by xenopeek** [comment]
This is happening on Linux Mint 20 MATE Beta: https://github.com/linuxmint/mint20-beta/issues/44

**Comment by Wohlstand** [comment]
I thought the third screenshot is a feature, and I can't find how to enable it back... I.e. Make a terminal to hide everything but show the background at the desktop, I liked this magic effect, sad that it was a bug... :grin:
