### ISSUE TITLE
Openbox themes

### ISSUE THREAD

**Issue by DarthWound** [linuxmint/mint-themes#182]
_EDIT: improved themes because I used an old Mint-Y source as reference..._

Hello, as I like using Mint-Y in my Openbox setups, I've made openbox-3 themes matching them, for both Light and Dark(er). Currently only for grey color, however it's easy to adapt for other variations as you only have to replace ~~#8d8d8d~~ #9d9d9d for light and #8f8f8f for dark with accent color you want. Feel free to modify and include them in Mint-Y packages if you want.

~~[OB-Mint-Y.zip](https://github.com/linuxmint/mint-themes/files/2763134/OB-Mint-Y.zip)~~
See [this comment](https://github.com/linuxmint/mint-themes/issues/182#issuecomment-497298927).

**Comment by modeler** [comment]
Excellent work, thank you for sharing.

**Comment by DarthWound** [comment]
Oops, I totally forgot, since then I've made corresponding OB themes for other colors too.

Complete pack:
```
wget https://alkusin.net/crubuntung/downloads/extras/OB-Mint-Y-pack.tar.xz
tar Jxvf OB-Mint-Y-pack.tar.xz
```

**Comment by modeler** [comment]
Thank you. I would love to see these merged into the main git here.

I know that Linux Mint doesn't have an LXDE spin, it's not even in the repos but Ubuntu does. In my opinion the Mint themes are the best looking of all, hands down. I use them on Debian myself so the Openbox themes are very welcome.

**Comment by modeler** [comment]
Hi again, the link to OB-Mint-Y-pack.tar.xz appears to be dead now. Any chance you could attach it here or upload to its own git repo?

Thanks!

**Comment by DarthWound** [comment]
Sorry, I "cleaned" my server a few days ago and this archive was deleted ^^

Can't attach XZ files in GitHub, they only support GZ and ZIP... so I've made a ZIP:
[OB-Mint-Y-pack.zip](https://github.com/linuxmint/mint-themes/files/3236766/OB-Mint-Y-pack.zip)

**Comment by JosephMcc** [comment]
Thanks for the effort but currently we focus on Mint and the DE's that we ship. I'm sure there are some people who will enjoy your work.
