### ISSUE TITLE
calendar.png seems to be missing

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mint-themes#184]
The Mint-_Y_ theme has a calendar.png icon. More precisely, subfolders of the `apps` folder within that theme have instances of (variations upon) calendar.png. I wonder whether Mint-_X_ should have that icon too (and whether the lack of it causes problems for the program Rainlendar).

**Comment by JosephMcc** [comment]
Sorry but I don't even know what Rainlendar is. I've never heard of it. What problems do you have and does it work properly in other themes?

**Comment by LinuxOnTheDesktop** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;Rainlendar is a calendar program that (in one version) runs on Linux (directly - not via Wine or Mono). Rainlendar is not to be confused with Rainmeter (this latter being a kind of Conky for Windows).

&nbsp;&nbsp;&nbsp;&nbsp;The [Rainlendar website is here](http://rainlendar.net/cms/index.php).

&nbsp;&nbsp;&nbsp;&nbsp;Rainlendar has a panel icon (which can operate as an indicator or not as an indicator). In Cinnamon, that icon (whether 'indicator' or not) either does not appear at all or else is tiny. (I don't recall what determines which of those two unfortunate outcomes one gets.) There is a fairly elaborate hack - to make the icon work in Cinnamon - that someone put together, and which was refined by Rainlendar's author; but that hack seems not to work with themes that have a certain structure - the structure Mint-Y has.

&nbsp;&nbsp;&nbsp;&nbsp;For details, please see [here on the Rainlendar forum](http://www.rainlendar.net/cms/index.php?option=com_kunena&Itemid=42&func=view&catid=4&id=25645).

&nbsp;&nbsp;&nbsp;&nbsp;It is hard to get this problem fixed, partly because, as often with Linux, it's hard to know whose software is responsible for the problem - while the users, of course, just want things to work. I might mention the following too. After changing certain configuration settings, Rainlendar restarts itself (by design); after the restart, Rainlendar's transparency does not work properly. Rainlendar's author holds, I believe, that this must be Cinnamon's (or Mint's) fault.

**Comment by JosephMcc** [comment]
The post you link to shows it's looking for a rainlendar specific icon. rainlendar-d6-panel or something. It's the job of the application to ship application specific icons if it needs them.

**Comment by LinuxOnTheDesktop** [comment]
Thanks Joseph. Now: in an effort to fix this, I've spoken to the Rainlendar developer; I've spoken to you; I could go back to the Rainlendar developer; and some enterprising Rainlendar user tried to create working icons for me, and failed; and this point I give up on the icons.

There remains the transparency problem. To quote myself, from above: 'After changing certain configuration settings, Rainlendar restarts itself (by design); after the restart, Rainlendar's transparency does not work properly. Rainlendar's author holds, I believe, that this must be Cinnamon's (or Mint's) fault.' There seems to be no extant Mint bug report for that; I'll file one against Muffin.
