### ISSUE TITLE
Feature (usability) request: position the close icon such that throwing pointer to top-right of screen and clicking closes window

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mint-themes#185]
I would like to be able to throw my pointer to the top right of the screen and click and thereby close a maximised window. I can do that on my Windows 8 machine. On Mint, with Mint-Y (and other themes?) I cannot. Rather, I must carefully move the pointer a little away from the top-right of the screen. Would it not save time - make Cinnamon more usuable - were I able to do what I do on Windows?

**Comment by sidmint** [comment]
that's a very useful feature i was used to. i still use that by manually installing themes like for example https://www.xfce-look.org/p/1165642/

**Comment by LinuxOnTheDesktop** [comment]
Thanks, sidmint, that theme looks good, though I will have to see whether it has everything I need.

**Comment by JosephMcc** [comment]
Testing Mint-Y on the latest git master this does work the way you are asking for.
