### ISSUE TITLE
Feature request: use gtk-application-prefer-dark-theme

### ISSUE THREAD

**Issue by rschouwenburg** [linuxmint/mint-themes#187]
Not sure if there is a particular reason for this, but Mint-Y ignores gtk-application-prefer-dark-theme gtk-setting. Since we have an official dark theme now, is it possible to use the Mint-Y-Dark when requested by the app?

**Comment by clefebvre** [comment]
Yes, we had a compatibility issue with Marco 1.20 which didn't support this well so we didn't want to activate it by default in Mint-Y as it could cause issues in MATE. This is fixed in the coming release though, so we'll switch it on.
