### ISSUE TITLE
Mint-Y: Pale fullcolor action icons

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mint-themes#197]
Problem
------------

Some applications are still using fullcolor icons instead of symbolic icons. It's not reasonable to think we can patch them all. We ship three variations of Mint-Y themes:

- Mint-Y uses light widgets and requires dark icons
- Mint-Y-Dark uses dark widgets and requires light icons
- Mint-Y-Darker uses both light and dark widgets and requires sometimes dark icons sometimes light ones.

As a compromise and to make icons visible on all themes, we currently ship with action fullcolor icons which are pale grey. The good news is that they're visible everywhere. The bad news is that they don't look good anywhere.

![image 8](https://user-images.githubusercontent.com/1138515/53873519-6fb3bb80-3ff8-11e9-948c-053af92f3aeb.png)

Ideally, in the picture above, the icons would be much darker on the light menu, and much lighter in the dark toolbar. This isn't possible with fullcolor icons though.

Solution 1 (Rejected)
--------------------------

Switch to a colourful set of fullcolor action icons.

Pros: 

- They'll likely look OK on any background.

Cons: 

- They'll look different than symbolic icons, bringing inconsistency and making apps using them integrate less in the desktop.
- It's hard to find a good existing set out there.
- Highlighting a colorful icon can be problematic depending on its color and the color of the theme. For instance if the theme is Mint-Y-Blue, highlighting a widget using a blue action button might hide the icon.

Solution 2 (Accepted)
---------------------------

- [x] Produce two sets of icons per color variation: one light (for -dark and -darker themes) and one dark (for light themes)
- [x] Switch Mint-Y-Darker GTK3 to use dark menus
- [x] Switch Mint-Y-Darker GTK2 to use dark menus

We could also disable icons in menus, but if people re-enabled them, Mint-Y-Darker would look broken.

Pros:

- The icons will look good and similar to symbolic icons, giving apps a consistent look.

Cons:

- With 33 GTK themes and 22 icon themes, Mint-Y is starting to be quite big.

Solution 3
-------------

- Only ship one Mint-Y theme (light, green, with dark fullcolor icons), i.e. 1 GTK theme with 1 icon theme.
- Ship a theme generator/customizer tool which can generate variations, in which the user selects an accent color, and a theme variation (Light, Dark, Darker), and which produces a custom theme for him/her.
- Use the ideas from solution 2 (Making -Darker variation use dark menus and -Dark/-Darker variations use light fullcolor icons).

Pros:

- Same as solution 2
- Less duplication and mayhem in theme selection tools
- More flexibility for users, the tool could even use sass and let them define some of the colours of the theme (other than just the accent colour).

Cons:

- Users currently using colour variations would be using a theme which no longer exists when upgrading. They would end up with Adwaita temporarily.
- The generation tool might have some limits when colorizing assets.

**Comment by clefebvre** [comment]
Solution 2 is implemented.

**Comment by clefebvre** [comment]
Reopening... mint-y-darker wasn't fully acceptable, still an issue in inkscape, printer queue dialog etc.. so menus are back in white again and we need to bring back pale grey icons, but only for -darker.

**Comment by JosephMcc** [comment]
The theme generator idea is something that is really on feasible if we limit what it does. It could not be something of for creating a whole new theme. If kept to fairly simple limitations I think it might be doable. That means things like choosing the accent color you want to use instead of shipping with 30 themes just to cover color variations people might want to have.
