### ISSUE TITLE
Mint-Y: Enable gtk-application-prefer-dark-theme

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mint-themes#199]
We couldn't do this in the past because of Marco. Apparently support for dark variants is fixed in Marco 1.22, which is coming up in Mint 19.2, so we should enable this option in Mint-Y.

- [x] Package MATE 1.22
- [x] Enable option in Mint-Y
- [ ] Test compatibility
- [ ] Ensure DE options are working fine
- [ ] Review which apps should be dark by default

**Comment by clefebvre** [comment]
This is postponed to 19.3.

Marco 1.22.0 doesn't fully support dark variants, it needs the following commit: https://github.com/GNOME/metacity/commit/6b0d325442b995a78b8783384f7ec370db1369a4

Mint-Y metacity 3 needs to switch from hardcoded colors to GTK customs.

**Comment by JosephMcc** [comment]
I'm closing this since most of the work has been done.
