### ISSUE TITLE
Review font selection

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mint-themes#200]
Here's a quick comparison of fonts in Elementary, Ubuntu and Linux Mint:

![image](https://user-images.githubusercontent.com/1138515/53882035-20c45100-400d-11e9-9db0-fa7187ea1b4b.png)

The elementary fonts come from fonts-open-sans and fonts-roboto. The Ubuntu fonts come from fonts-ubuntu, and the Linux Mint fonts come from fonts-noto-hinted.

The suggestion is to:

- [x] Switch to the Ubuntu font
- [x] Remove fonts-noto, fonts-noto-hinted and fonts-noto-unhinted (they create stuttering in Chromium)
- [x] Test compatibility with Asian languages and QT apps
- [x] Review font sizes
- [x] Review mono font selection
- [x] Consider switching Cinnamon theme to Ubuntu and/or to using system font

Comparison of the different fonts
--------------------------------------------

This is done by applying the fonts on top of Mint 19.1.

Here's the default look, with Noto Sans:

![mint](https://user-images.githubusercontent.com/1138515/53884110-b6161400-4012-11e9-9cb2-2990b71dba45.png)

**OpenSans**

Here we're using Open Sans (same size, same mono font as before, just switched Noto Sans to Mono Sans):

![opensans](https://user-images.githubusercontent.com/1138515/53884186-e493ef00-4012-11e9-9db8-61ea5f0e66cd.png)

The result largely looks the same and isn't as good as the original. Except for a stylized G which arguably looks better, "i" aren't as readable, and there are some spacing issues here and there.

**DejaVu Sans**

![sans](https://user-images.githubusercontent.com/1138515/53884780-40ab4300-4014-11e9-9366-4d9344fb3ff6.png)

This is the exact same font as Noto Sans but it looks slightly larger. The titlebars look a little bit big, but we can reduce the size.

There are tiny differences in the legibility. The 9 in mintupdate's bind9 update seems to be a little easier to read.

**Ubuntu**

Switching to Ubuntu we get a slight improvement overall. Spacing is improved and the font is a little easier to read. It also has that friendly feeling to it.

![ubuntu](https://user-images.githubusercontent.com/1138515/53885804-849f4780-4016-11e9-8fa0-3e39b56adb0b.png)

Here's an in-depth look at the differences:
http://www.identifont.com/differences?first=noto+sans&second=ubuntu&q=Go

Ubuntu also has something else going for it, it's likely to be set up and patched/configured/postinst-glued properly in Ubuntu and so also in Mint. This gives it an advantage over similar or even better / more popular fonts used on the web or outside the Linux community.

Comparison of the different Mono fonts
-----------------------------------------------------

Our Mono font works quite well already: Monospace Regular 10.

![image](https://user-images.githubusercontent.com/1138515/53891340-15c7eb80-4022-11e9-85aa-b6cdd81e8f0f.png)

In comparison, Ubuntu Mono 12 (which gives us the same size), is harder to read and a little too fancy:

![image](https://user-images.githubusercontent.com/1138515/53891327-0cd71a00-4022-11e9-95f2-6428f4d23282.png)

**Comment by clefebvre** [comment]
The font was switched to Ubuntu.

**Comment by psychsane** [comment]
Thanks for switching to Ubuntu fonts :dancer:
