### ISSUE TITLE
Mint-Y: Don't use the accent color as much

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mint-themes#202]
The Mint-Y theme makes heavy use of the accent color. If you love green, you're in for a treat, if you don't... well it's a bit omnipresent.

We're also starting with a disadvantage compared to other projects because most of them are able to use Blue, which people enjoy more, which is easier to work with, more standard, and which generally looks better than green.

The idea here is to reduce the amount of accent color within the Mint-Y theme.

Here's a look at the current Mint-Y:

![image 7](https://user-images.githubusercontent.com/1138515/53891994-5b38e880-4023-11e9-8380-879b35175278.png)

In comparison, here's Adwaita:

![image 12](https://user-images.githubusercontent.com/1138515/53892014-6ab83180-4023-11e9-84e5-0dabcc179817.png)

As you can see above, checkboxes, radio buttons are neutral and don't use the accent color. Same goes for toggle buttons and buttons....etc.

The Mint-Y notebook tabs are neutral (unlike the Adwaita ones) and they work very well. We should try and make more widgets neutral like this. We can always add emphasis on colour around the theme, in the use of selection, tiling zones, logos, backgrounds, etc.. we'll look more classy if we don't overuse it within the theme.

**Comment by clefebvre** [comment]
Links are now neutral.

**Comment by clefebvre** [comment]
![image](https://user-images.githubusercontent.com/1138515/54084732-537f8980-432c-11e9-9949-1db8fc483b35.png)

![image](https://user-images.githubusercontent.com/1138515/54084737-5da18800-432c-11e9-9124-155248258ea7.png)

![image](https://user-images.githubusercontent.com/1138515/54084741-6abe7700-432c-11e9-8baa-32fd0ce6cdb9.png)

![image](https://user-images.githubusercontent.com/1138515/54084743-7742cf80-432c-11e9-94e0-d322202c6ff4.png)

![image](https://user-images.githubusercontent.com/1138515/54084824-88d8a700-432d-11e9-94b4-0ca7621190b2.png)

**Comment by clefebvre** [comment]
Inactive Ambiance (loses its accent color):

![image](https://user-images.githubusercontent.com/1138515/54624986-5124da00-4a66-11e9-8252-5c5de0674f3a.png)

**Comment by kuntalkundu** [comment]
please add a tool like this widget factory in linux mint. Which will help us to change the depth of green color or what we want.

**Comment by clefebvre** [comment]
it's there, awf-gtk2, awf-gtk3, gtk3-widget-factory.

**Comment by JosephMcc** [comment]
gtk3-widget-factory is actually installed as part of the gtk-3-examples package. This also give you gtk3-demo which can be handy to see some widgets you may not see in the others.

**Comment by JosephMcc** [comment]
Closing this since most of it's been done. We can always review any other areas we'd like to change.
