### ISSUE TITLE
xfce4-screensaver lock-screen appearance broken

### ISSUE THREAD

**Issue by Mau-G** [linuxmint/mint-themes#206]
Hello not sure if this is something to be fixed in the theme or in xfce4-screensaver but the appearance of the lock-screen is broken. Text area and buttons have gaps instead of being unified. Please see screenshot for reference.

What it looks like:
![Screenshot_2019-03-31_15-55-26](https://user-images.githubusercontent.com/44322817/55286369-87028080-53cd-11e9-9ebc-46cf2df52228.png)

What it should look like:
![xfce4-screensaver-0 1 3_featured](https://user-images.githubusercontent.com/44322817/55286382-d47eed80-53cd-11e9-8c79-b5ae3a4e9a66.png)

**Comment by vinzv** [comment]
I can confirm that issue, disregarding of the colouring (dark/bright).
Would be great if someone could fix it!

**Comment by JosephMcc** [comment]
It would help if you let us know which theme you are using that it's broken with.

**Comment by JosephMcc** [comment]
I was just looking at this. xfce4-screensaver doesn't even look to be available in Mint.

**Comment by Mau-G** [comment]
> It would help if you let us know which theme you are using that it's broken with.

It happens with any variant of the Mint-Y theme.

> I was just looking at this. xfce4-screensaver doesn't even look to be available in Mint.

It's still in beta for now  and we're testing this out in openSUSE Tumbleweed Xfce checking for bugs before the official release.
https://git.xfce.org/apps/xfce4-screensaver/about/

**Comment by tux93** [comment]
This could be closed since it was fixed in xfce4-screensaver

**Comment by Mau-G** [comment]
@tux93 yes thanks for the reminder
