### ISSUE TITLE
Mint-Y-Dark-Grey: <enter> duplicates text in alt-F2 dialogue

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mint-themes#207]
To reproduce:

1. Load the Mint-Y-Dark-Grey Destop theme.
2. Copy some text to the mouse buffer.
3. Alt-F2.
4. Paste text via right-click context menu.
5. Press return.
6. See your text appear twice.

Cf. https://github.com/linuxmint/cinnamon/issues/6290. It does seem, though, that the problem affects only some Desktop themes. For instance, the `Cinnamon`  theme is not affected.

**Comment by JosephMcc** [comment]
I'm closing this for now. After two years I've still never been able to reproduce this.
