### ISSUE TITLE
tray icons are sized all over the place and stretched in MATE

### ISSUE THREAD

**Issue by calexil** [linuxmint/mint-themes#209]
see picture

![Screenshot at 2019-04-08 18-42-36](https://user-images.githubusercontent.com/3487071/55761869-c7e24100-5a2e-11e9-89f1-f5251382301e.png)

**Comment by calexil** [comment]
This is still happening all the way in 19.2

![Screenshot at 2019-08-04 16-10-23](https://user-images.githubusercontent.com/3487071/62428705-611a1f00-b6d2-11e9-9a28-c5f7aadfd042.png)

**Comment by calexil** [comment]
quite oddly I can remedy this by cranking down the dpi below 96 and then back up..

**Comment by JosephMcc** [comment]
It doesn't happen in any other themes?

**Comment by calexil** [comment]
tbh I wasn't sure this was even the right place to report it, since I think it's actually a MATE problem, but I was hoping beyone hope someone would answer.

the update from 18.3 to 19.1 caused it to If I knew what kinda changes happened to mate panel and perhaps the dpi scaling that might be a start

**Comment by JosephMcc** [comment]
Don't think this is related to the theme in any way.
