### ISSUE TITLE
Hard to differentiate between opened windows

### ISSUE THREAD

**Issue by medmedin2014** [linuxmint/mint-themes#211]
How can I draw external white line all around border to be able to differentiate between opened windows, I use Ubuntu Mate 18.04.2 - 64bits with Marco desktop manager without any animations effects or compositing manager.
![Selection_018](https://user-images.githubusercontent.com/7027319/56951035-b45a5f80-6b2e-11e9-89ef-008f9568750b.png)

**Comment by LinuxOnTheDesktop** [comment]
Cf. [this other bug report](https://github.com/linuxmint/cinnamon/issues/6534) (filed against Cinnamon).

**Comment by LinuxOnTheDesktop** [comment]
It would be good were the current reworking of themes to fix this problem.

**Comment by JosephMcc** [comment]
I'm closing this since the metacity themes have been reworked since. There should be a 1px border on windows now.
