### ISSUE TITLE
Mint-Y-Dark: some parts of the Thunderbird UI are hard to read

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mint-themes#218]
&nbsp;&nbsp;&nbsp;&nbsp;When using any of Thunderbird's 'default' themes ('Default', 'Light', 'Dark'), in conjunction with Mint's Mint-Y-Dark theme, I see this:

![image](https://user-images.githubusercontent.com/47056543/60309595-76b75e80-9946-11e9-997e-72713761fe9c.png)

The text 'unified folders' is somewhat hard to read. Matters are worse when the Inbox is highlighted (highlighted but at the same time not selected):

![image](https://user-images.githubusercontent.com/47056543/60309704-09f09400-9947-11e9-96d7-ee09ef749166.png)

&nbsp;&nbsp;&nbsp;&nbsp;The problem does not seem to owe to any Thunderbird extensions. The problem could be worse, but, ideally, there should not be white or white-grey text on a whitebackground. The problem may owe partly or even wholly to Mozilla but it would be good were Thunderbird to look nice for users of Mint's flagship dark theme.

&nbsp;&nbsp;&nbsp;&nbsp;I confess to using the Mint alpha PPA; _possibly_ the problem does not occur, or is slightly different, on the release version of Mint-Y.

EDIT: **There's also a problem - a **worse** one - with tooltips:**

![image](https://user-images.githubusercontent.com/47056543/60309943-4cff3700-9948-11e9-8568-3b51f514cb11.png)

Thunderbird 60.7.1

**Comment by JosephMcc** [comment]
Thunderbird, like some web browsers and other apps, doesn't fully use the gtk theme. It has always been poor with many full dark gtk themes. It's one of the reason we didn't have one for so long. So we wouldn't get complaints over things that aren't really fixable :) 

Closing this as it's something that we can't actually do much about.

**Comment by smurphos** [comment]
@JosephMcc 

I made a start on trying to fix some of thunderbirds poor GTK integration in response to query re the Cinnamox Themes here https://forums.linuxmint.com/viewtopic.php?p=1582161#p1582161 via a custome userChrome.css to override some of the hard-coded problems. Could Mint distribute a userChrome.css in this way?

**Comment by JosephMcc** [comment]
@smurphos I know you can work around this some by doing this but would really rather not. From what I've seen, and maybe I could be wrong, these have a tendency to break often with new versions. Just really don't want to get started with the maintenance issues this would bring. I didn't check your link but are you doing this for Firefox as well?

**Comment by LinuxOnTheDesktop** [comment]
@JosephMcc , @smurphos 

It seems to me then that the choice is between more work by Mint or else a somewhat broken Thunderbird. Or at least that is the choice until Thunderbird (and Firefox) improve things. (I note that one problem I have with Thunderbird is the subject of a bug report that is more than a decade old and that has dozens of comments upon it. Nor is that particular problem entirely unrepresentative.)

It may be relevant to note the following. Mint's donations have increased of late and Mint's mission is an accessible, polished version of Linux. (Can I myself volunteer for the job at issue? No. I do not quite have the necessary knowledge and already I spend a lot of time - more than the developers might like! - testing Mint and reporting its bugs.)
