### ISSUE TITLE
Mint-Y Dark, on Thunderbird: customise 'from' address yields unreadable text

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mint-themes#219]
&nbsp;&nbsp;&nbsp;&nbsp;When I tell Thunderbird to 'customize the from' address (by clicking the arrow at the end of the 'from field') I see this:

![image](https://user-images.githubusercontent.com/47056543/60309462-cfd2c280-9945-11e9-84a6-1442d4a405dd.png)

&nbsp;&nbsp;&nbsp;&nbsp;Admittedly, I see the above only when using the third-party Thunderbird theme 'Deep Dark'. _Yet_, the developer of that theme tells me that the problem must be either with a Thunderbird extension or with my OS theme. Removing all extensions (except the Deep Dark theme) does not solve the problem. Changing the theme to Mint-Y (not the dark version) does solve the problem - the text becomes legigible. From the combination of all the above I infer, tentatively, that the problem is with Mint-Y-Dark.

&nbsp;&nbsp;&nbsp;&nbsp;I could use a theme supplied by Thunderbird itself - viz., one of 'Default', 'Light', 'Dark'. However: (1) I don't want to and as said the problem does seem to be with Mint-Y-Dark; (2) if I use the default themes then I encounter a different (albeit less severe) problem, namely, #218.

&nbsp;&nbsp;&nbsp;&nbsp;I confess to using the Mint alpha PPA; just possibly the problem does not occur, or is slightly different, on the release version of Mint-Y.

Thunderbird 60.7.1

**Comment by JosephMcc** [comment]
See: https://github.com/linuxmint/mint-themes/issues/218
