### ISSUE TITLE
Mint-Y-dark Control highlights too bright

### ISSUE THREAD

**Issue by TrickMe** [linuxmint/mint-themes#220]
Control Highlights (Aqua, Red, Green, Blue, Teal, Grey) are probably fine for normal/bright themes.
For dark themes, please adjust them according to the dark environment/surroundings and the text, which is rendered white instead of black.

Right now, control highlights are just too bright for dark themes.
Check the "Restore Selected Items" and Empty Trash" buttons in the "Trash" window to get a good view for optimal brightness.

Thank you!

**Comment by JosephMcc** [comment]
Thanks for the suggestion. We always keep these sort of changes in mind based on general feedback from users.
