### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by callagg2** [linuxmint/mint-themes#221]
Assume i choose the following:
Desktop -> Mint-Y-Dark Teal
Controls -> Mint-Y-Dark-Teal
Icons -> Mint-X-Teal
and i come to Window Borders....
Now i have three options is seems
1. Mint-X which is shaded in grey
2. Mint-Y which is shaded in grey
3. Mint-Y-Dark which is shaded in Very dark Grey/Black

Picking number 3 gives me a very dark/black title bar as expected
Picking number 2 gives me a grey shaded title bar as expected
But picking numer 1 gives me ..... a  very dark/black title bar - can i put in a request for this to be a grey shaded title bar or have an additional option where the drop down color for Mint-X matches the title bar colour? The reason i ask is because it is very difficult to read the application title name in Mint-X window border, it is black because it is assuming the title bar is grey.

Thanks

Thanks

**Comment by JosephMcc** [comment]
Thanks for the request. Not sure if this is a change we will make since Mint-X is really meant to work with the Mint-X controls.
