### ISSUE TITLE
Missing window borders on Mint 19.2 Mate with Mint-Y* themes

### ISSUE THREAD

**Issue by dimka-rs** [linuxmint/mint-themes#224]
Upgraded 19 -> 19.1 -> 19.2. On 19.2 window borders has gone. Playing with Desktop Setting showed that:
* Only Marco and Marco + Compton are affected, Marco + Compositing works fine.
* Only Mint-Y, Mint-Y-Dark and Mint-Y-Darker (green) themes are affected.

**Comment by aleex5** [comment]
that happens because mint themes have no borders, in fact if in cinnamon you disable shadows, you will realize that they have no borders
the only way to make these themes look good is if you have shadows activated

**Comment by smurphos** [comment]
That's not the whole story. mint-themes ships two versions of the window borders themes - a metacity-theme-2.xml  and metacity-theme-3.xml

In Mint 19.1 and below MATE used the former and Cinnamon used the latter. The former has borders.

The MATE version in 19.2 is the first MATE version that supports metacity v3, and it will be used if present - but the MATE devs will all due respect to them made a bit of a mess of the implementation so their support for borderless themes does not work in all combinations of window manager / compositor. They are being a bit slow to recognise that this is their bug and not a theme problem ;-)

MATE does still support v2 still so the quick fix until the MATE devs get their act together in some future version it to delete the metacity-theme-3.xml file from the themes directory to force use of the legacy metacity-theme-2.xml

**Comment by JosephMcc** [comment]
I think the explanation given by smurphos here says it all.

**Comment by StarKnightt** [comment]
> That's not the whole story. mint-themes ships two versions of the window borders themes - a metacity-theme-2.xml and metacity-theme-3.xml
> 
> In Mint 19.1 and below MATE used the former and Cinnamon used the latter. The former has borders.
> 
> The MATE version in 19.2 is the first MATE version that supports metacity v3, and it will be used if present - but the MATE devs will all due respect to them made a bit of a mess of the implementation so their support for borderless themes does not work in all combinations of window manager / compositor. They are being a bit slow to recognise that this is their bug and not a theme problem ;-)
> 
> MATE does still support v2 still so the quick fix until the MATE devs get their act together in some future version it to delete the metacity-theme-3.xml file from the themes directory to force use of the legacy metacity-theme-2.xml

Thank you for clearing my dobut
