### ISSUE TITLE
Missing volume bar using media keys on Linux Mint 19.2 with the "Linux Mint" Cinnamon theme

### ISSUE THREAD

**Issue by Janne-d-Arc** [linuxmint/mint-themes#225]
After upgrading Linux Mint 19.1 to 19.2, when I use the Media keys to increase or decrease the volume, the volume bar is not visible using the "Linux Mint" Cinnamon theme:

![Mint](https://user-images.githubusercontent.com/13596575/62748700-33f5a580-ba1f-11e9-8036-256e490d3ae5.png)

**Comment by JosephMcc** [comment]
That screenshot is not the Mint-X cinnamon theme. Maybe it's the Linux Mint theme?

**Comment by brownsr** [comment]
that looks like the linux Mint theme, with Mint-X icons

**Comment by Janne-d-Arc** [comment]
You're right, I'm sorry. So many years using Mint-X as the default theme made me forget that the Cinnamon theme is not called the same. It's the Linux Mint theme, I'm using the old default theme, Mint-X with Linux Mint. I will edit the title and the comment.

**Comment by Janne-d-Arc** [comment]
Well, it seems that I have found the problem, in the “cinnamon.css” file of the "Linux Mint" theme was not assigned a value for ".osd-window .level-bar". By adding it, the volume bar is displayed correctly:

![Volume](https://user-images.githubusercontent.com/13596575/62843719-ad8cce00-bc81-11e9-8df0-7aa60abb6bef.png)

**Comment by JosephMcc** [comment]
Nice catch. I'll get this fixed. It should still have a fill color without this though. It should be getting picked up from the default cinnamon theme if a theme does not override it. That's why I don't see the problem here and didn't catch it.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/mint-themes/commit/e1f27ebf40349bba2af2d9b52687363c7181488f
