### ISSUE TITLE
Colour in progress bar overlay does not match theme colour selection

### ISSUE THREAD

**Issue by StaphSynth** [linuxmint/mint-themes#233]
Hi, I'm using Cinnamon with the Mint-Y-blue theme selected, but whenever there's a progress bar overlay rendered on the task bar icon of a running program, it's in the default Mint green colour (see screenshot)

![theme-color-bug-2019-09-28](https://user-images.githubusercontent.com/20519886/65812911-38fdf680-e211-11e9-8160-f9fecf68b74b.jpg)

Steps to reproduce:
1. Set your desktop theme to something other than the default (for example, Mint-Y-blue)
2. Do something to cause a progress bar overlay to appear on the task bar (for example, get the update manager to perform an update)
3. Observe the that the colour of the progress bar is not the one you selected in step 1.

**Comment by smurphos** [comment]
I can't reproduce the problem wtth Cinnamon 4.2 , mint-themes 1.8.2

Can you double-check that you have set the Desktop theme to Mint-Y-Blue and not just the Controls theme. It's the former that themes the panel.

![screenshot-window-2019-09-29-054718](https://user-images.githubusercontent.com/29017677/65826433-d04c6380-e27c-11e9-8204-81f80c107456.png)

**Comment by StaphSynth** [comment]
See, now I feel (and look like) an idiot :)

Yes, the Desktop theme was still set to the default.

Thanks for that, and for all the other amazing work you guys do.

**Comment by JosephMcc** [comment]
Don't worry. It happens to all of us :)
