### ISSUE TITLE
[Feature Request] Browser theming

### ISSUE THREAD

**Issue by RafaelKr** [linuxmint/mint-themes#234]
Dear Mint team,

I'm a big fan of dark themes and use it where possible. You made really great improvements to the Mint-Y-Dark themes over the last releases!

Lately I was searching for a dark theme for Firefox matching the Mint-Y-Dark theme, but I didn't find one, so I created one myself. https://addons.mozilla.org/en-US/firefox/addon/linux-mint-mint-y-dark/

I was wondering, if it would be possible and desired to also (optionally) change the Firefox Theme from the "Themes" system settings in Linux Mint.

Based on the dark theme I linked above, I'd be happy to provide variants with an adjusted accent color matching every accent color of the other Mint-Y-Dark themes for it.

And if it is not desired to implement this in the system settings, I would still suggest that the corresponding themes are made available with an official "Linux Mint"-Account in the Mozilla Addon Store.
I'm also willed to hand everything (addon name, addon url, ...) over to an official account or to hand over my whole account as an official account. Credentials and everything else can then be changed of course.

**Comment by RafaelKr** [comment]
I just noticed, that the "Default" theme of Firefox also adapts the dark style of when "Controls" are also set to "Mint-Y-Dark" in the "Themes"-Settings. Until yesterday I just had set Desktop to dark before.

But in my opinion the grey of the toolbar doesn't fit the style of "native" windows like Nemo for example. I think it should be darker.

**Comment by JosephMcc** [comment]
I appreciate the effort but I'm not sure this is something we want to take on. Especially with how often new versions of browsers are released. I'm honestly unsure how often this would be broken and have to be updated.
