### ISSUE TITLE
csd-locate-pointer animation unthemed in Mint-Y and Mint-X (and many other GTK themes)

### ISSUE THREAD

**Issue by smurphos** [linuxmint/mint-themes#236]
Cinnamon 4.4.8, Mint-Themes 1.8.3

Hi, whilst providing some assistance to  a user wanting to change the colour if the csd-locate-pointer animation in their own customised gtk theme I noted that the animation is unthemed in all the stock Mint themes (it's black).  It's also unthemed in upstream Adwaita.

There are some themes that colourise the animation - normally with their selected background colour. The common factor is that themes that work have a declaration as below

```
*:selected {background-color: #xxxxxx;}
```

I had a look here - https://github.com/linuxmint/cinnamon-settings-daemon/blob/master/plugins/mouse/csd-locate-pointer.c#L67 -but can't decipher if there should actually be a defined style class for the animation or if it is just looking for a generic `*:selected` style-class.

Ultimately is adding a `*:selected` declaration to the Mint themes the correct fix?

**Comment by JosephMcc** [comment]
I'll have to look more but I'm not a big fan of adding the wildcard selector. That's just asking for unexpected things :)
