### ISSUE TITLE
why mint-y firefox there still empty space between top of the tabs and top of the screen?

### ISSUE THREAD

**Issue by candrapersada** [linuxmint/mint-themes#237]
why mint-y and mint-y-dark there is still empty space between top of the tabs and top of the screen after using this possibility. See the screenshot?
![image](https://user-images.githubusercontent.com/36833664/72970976-5461c280-3dfb-11ea-8696-76376071e7bc.png)
and theme other there is no problem with free space between the tabs and the top of the screen like adapta nokto?
the same as issues #169

**Comment by JosephMcc** [comment]
Well a couple things here. It doesn't look to me like you are using either Mint-Y or Mint-Y-Dark in your screenshot. Here using either of those themes and turning of drag space in the Firefox customize settings gets rid of the issue.
