### ISSUE TITLE
Google Chrome browser blury titlebar buttons

### ISSUE THREAD

**Issue by tashimotor** [linuxmint/mint-themes#239]
![image](https://user-images.githubusercontent.com/14804351/73339777-84411800-428a-11ea-83d8-88e035f4851a.png)
Any Mint-Y theme

**Comment by otavioschwanck** [comment]
Here too.
![image](https://user-images.githubusercontent.com/9551316/75076922-3fab4400-54f9-11ea-8c1d-2e6d1ddb2795.png)

**Comment by JosephMcc** [comment]
You guys need to give a bit more info. Are you using HiDPI? Have you tried with other themes? Are you using a scaled font in the titlebar?

**Comment by otavioschwanck** [comment]
> You guys need to give a bit more info. Are you using HiDPI? Have you tried with other themes? Are you using a scaled font in the titlebar?

I'm not using HiDPi, tried other themes (Adwaita, Mint-x, adapta) and works flawless. 

Using arc-theme (the theme that mint-y is based), the same problem happens.

**Comment by tashimotor** [comment]
I have 1920x1080 resolution, no HiDPi.
Other themes are OK.
The font scale is 1.0.

**Comment by JosephMcc** [comment]
I'd like to point out that testing here on Mint 19.3 I can reproduce this issue with all three themes I have installed. Mint-y, Mint-x, and Adwaita. The spacing is broken between the buttons when the window is maximized.

**Comment by JosephMcc** [comment]
Tried this with Git master on 20.3 and this doesn't seem to be an issue anymore.
