### ISSUE TITLE
Feature request: $suggested_color on default action button (Save)

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint-themes#240]
### Mint-Y default action button:
Sometimes, i am so lazy or tired that i just press [Enter] on some dialog boxes instead of pointing and clicking with the mouse. I am talking about “**Save changes before closing...**” dialogs. I have no doubts with Xed: the save button is displayed with the green $suggested_color background. So i know i did no mistake. But on some other programs, there is just a subtle dashed line on default action button, so I press [Enter] instinctively, but then i am not sure my document got saved or not, and so i always have to check... It would be nice if all those default action buttons were green, like in Xed. Maybe something as follow?
**_common.scss** file:
```
.button {
[...]
  &.default {
  	background-color: $suggested_color;
  	color: white;
  }
[...]
}
```

**Comment by JosephMcc** [comment]
I've been thinking about this one but think I'd prefer not to go this way. You could easily end up with essentially conflicting things. A logout or shutdown dialog come to mind. The default button could be shutdown but in Cinnamon, for example, this has the destructive class. I think I'd prefer to leave it to applications to decide what style this receives.
