### ISSUE TITLE
[Mint-X Gtk 3 theme] Gtk.FlowBox items have no styling

### ISSUE THREAD

**Issue by Odyseus** [linuxmint/mint-themes#241]
I found two problems while developing a widget using `Gtk.FlowBox`es.

- The CSS rule for [`Gtk.FlowBox`es](https://github.com/linuxmint/mint-themes/blob/master/src/Mint-X/theme/Mint-X/gtk-3.0/gtk-widgets.css#L652) has no effect since `Gtk.FlowBox`es are now named `flowbox` and `Gtk.FlowBoxChild`s are named `flowboxchild` without a class set.
- `Gtk.FlowBoxChild`s inside `Gtk.FlowBox` containers have no styling when selected. This styling was lost when the `*:selected{}` selector was [commented out](https://github.com/linuxmint/mint-themes/commit/3855c033ac61973737d4ad7849285e86b90a8eec#diff-6ed4004cf312accbe177670421c095c0R56) and later [removed](https://github.com/linuxmint/mint-themes/commit/117930a30bf7e13494ba010d4236cc313f421843#diff-6ed4004cf312accbe177670421c095c0L56).

May I recommend the following changes to fix this issue?

```patch
--- a/src/Mint-X/theme/Mint-X/gtk-3.0/gtk-widgets.css
+++ b/src/Mint-X/theme/Mint-X/gtk-3.0/gtk-widgets.css
@@ -649,7 +649,7 @@ expander arrow:checked {
  * flow box *
  ************/
 
-GtkFlowBox .grid-child {
+flowbox flowboxchild {
     padding: 3px;
     border-radius: 3px;
 }
@@ -2611,6 +2611,8 @@ entry selection {
     background-color: @theme_selected_bg_color;
 }
 
+flowbox flowboxchild:selected,
+flowbox flowboxchild:selected:focus,
 row:selected label,
 label:selected,
 label selection,
 .view:selected,
 iconview:selected,
 .view:selected:focus,
 iconview:selected:focus,
 .view text:selected,
 iconview text:selected,
 textview text:selected,
 .view text:selected:focus,
 iconview text:selected:focus,
 textview text:selected:focus,
 .view text selection:focus,
 iconview text selection:focus,
 .view text selection,
 iconview text selection,
 textview text selection:focus,
 textview text selection,
 entry selection:focus,
 entry selection {
     color: @theme_selected_fg_color;
     background-color: @theme_selected_bg_color;
 }
```

Pinging the experts (@smurphos & @JosephMcc).

**Comment by JosephMcc** [comment]
I think this would be fine. I can't think of any place off hand to directly test it.

**Comment by Odyseus** [comment]
Hello, @JosephMcc.

> I can't think of any place off hand to directly test it.

Yeah, there aren't much applications using `Gtk.FlowBox`es. If you prefer, [this ZIP archive](https://github.com/linuxmint/mint-themes/files/4174641/theme-icon-chooser-demo.zip) contains a functional example of an icon chooser dialog. Just unpack and run the `theme-icon-chooser-demo.py` script. It should display a dialog like in the following image.

![Screenshot from 2020-02-08 13-15-50](https://user-images.githubusercontent.com/3822556/74088467-9fbfd600-4a75-11ea-9995-7fddc5ba0c52.png)

**Comment by JosephMcc** [comment]
Thanks. I'll check it out and see about getting the problem fixed.

**Comment by JosephMcc** [comment]
Fixed. Thank you sir for making it so easy.
