### ISSUE TITLE
Chrome window buttons way too short on Mint-Y variants

### ISSUE THREAD

**Issue by xqmate** [linuxmint/mint-themes#247]
In order to get a better user experience from laptops with reduced screen size, most Chrome users like to turn off "use system bar and borders" option (which is turned off by default on most distros). When a Chrome window is maximized, the buttons appear to be bad rendered, and turn out to show up in a smaller size. The very same thing does not happen with other browsers (like Firefox) neither do happen with Arc theme (which I believe Mint-Y theme is based on). All variants inherit this issue. Here are some screenshots (top is Chrome maximized, bottom is Firefox):

**Mint-Y**
![buttons](https://user-images.githubusercontent.com/62488085/77238964-396dbd80-6bb4-11ea-8319-39e0773e0c02.png)

**Arc**
![buttons-arc](https://user-images.githubusercontent.com/62488085/77239140-de3cca80-6bb5-11ea-966b-ebb1af47730e.png)

**_Additional info_**
- Font scaling: 1.0 (Standard)
- No HiDPI

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/mint-themes/issues/239
