### ISSUE TITLE
Feature request:  Thicker borders for Mint-X theme

### ISSUE THREAD

**Issue by mdinslage** [linuxmint/mint-themes#253]
I was playing around with Mint-X theme version 1.8.3 today and I noticed that the borders are very thin, which IMO looks aesthetically unappealing and also makes the windows difficult to grab on larger display monitors.   I think it would be nice if we could get a few extra pixels to the border to make it easier to grab and I think it would make the over all theme look a little better. Attached is a screenshot showing what I am referring too.  This is not that big of a deal, the theme looks great as it is, but it's just a thought.

Thanks for your consideration. 

![borders](https://user-images.githubusercontent.com/28424337/78533097-f9126000-77ad-11ea-9dc4-60b3eba1b51b.png)

**Comment by mdinslage** [comment]
One last screenshot,  This is a side by side of the old GTK 3.14 theme I am using in Slackware 14.2 and the newest 1.8.3 in a VM.  As you can see the older version has just a few extra pixels on the frame border.  It would be nice to get the new theme to have the same border as the old.

![macros4](https://user-images.githubusercontent.com/28424337/78613945-c494b780-7832-11ea-95ac-304e37877579.png)

**Comment by JosephMcc** [comment]
Thanks for the suggestion but this is unlikely to change. If I'm not mistaken, even Mate now supports invisible borders so this shouldn't have much affect on being able to actually grab and resize the windows.
