### ISSUE TITLE
Nemo file manager sidebar color

### ISSUE THREAD

**Issue by zbandhan** [linuxmint/mint-themes#254]
Nemo file manager's sidebar remains always black. It does not change according to its theme color variation. Whatever theme-color I select the sidebar bgcolor is same black. Is it changeable with theme color because Mint has almost every desired color to pick.

**Comment by mtwebster** [comment]
You can override it but if you do you'll probably have to change more than that, like the symbolic icon and text colors, or else they could end up unreadable.

@JosephMcc

**Comment by JosephMcc** [comment]
I'm a little confused as to what the OP wants. It sounds like you don't like that the sidebar is always dark in the mint themes no matter what color variation you choose. We do the same in all the file managers of the DE's we support. It's just a design choice we make that I don't think will change. You can change it yourself if you want to edit the css and sass files or you can override it in a ~/.config/gtk-3.0/gtk.css file. You can find most of the selectors you need to use and experiment with here: https://github.com/linuxmint/mint-themes/blob/master/src/Mint-X/theme/Mint-X/gtk-3.0/apps/cinnamon-applications.css#L11

**Comment by stevedonato** [comment]
Not true  the reverse. I always had a black dark background on the nemo sidebar (easier to read then same background as white main area) Now it is white? I cannot get the black background in the side bar back.
