### ISSUE TITLE
Calendar not properly showing days of the week (in PT-BR)

### ISSUE THREAD

**Issue by BrunoNZ** [linuxmint/mint-themes#259]
I'm testing the updated Blue theme and i noticed that the Calendar is not properly showing the names of the days of the week (in PT-BR). It was supposed to show "dom" (from Domingo, Sunday in english), but because the updated font's size it just shows "d...". The following image exemplify the problem.

I'm testing with commit e17a662fa56f5629a4af7a32ea059fa1d83234df and default fonts (and sizes).

![bug_minty_calendar(1)](https://user-images.githubusercontent.com/1660320/79260549-d85ca100-7e64-11ea-8810-000029bf73f0.png)

**Comment by JosephMcc** [comment]
Could you test this in Mint20 and Cinnamon 4.6? There have been some fixes in regards to this.

**Comment by BrunoNZ** [comment]
Nice! I've just tested with master (commit 4ca080c67c040180db7ad4d9ff2f513a1fc0dc4d), and everything is fine. It looks identical to what mint-themes 1.8.6 looks like. Thanks!

**Comment by JosephMcc** [comment]
Thanks for following up. I'm going to go ahead and close this.
