### ISSUE TITLE
[Mint themes 1.8.4] Is Mint Y Teal a bit too "bluish"?

### ISSUE THREAD

**Issue by FrogMcRibbit** [linuxmint/mint-themes#267]
Colors for the Mint Y theme has been reworked recently. I (and many others on the Manjaro forum) have noticed that the Teal variant looks much more bluish than before.

https://forum.manjaro.org/t/manjaro-cinnamon-20-0-lysia-released/138796/5?u=frog

I know it is a matter of taste, but I was wondering if it was intentional or if it was accidental?

If it is intentional and you are satisfied with that color, it is not a problem. Manjaro team might just patch the theme in order to get a color that correspond more to their branding. :)

**Comment by clefebvre** [comment]
Hi @FrogMcRibbit,

It's intentional. Feel free to patch it if you want to go back to the previous tint.

**Comment by FrogMcRibbit** [comment]
All right, thanks for the answer!

**Comment by oberon-manjaro** [comment]
Hi guys and thank you @clefebvre for your reply. What confuses me a little here is, that the current repo contains a file **Mint-Y-Variations-NEW-1a-11-notext.svg**, showing these samples for Teal colors:
![image](https://user-images.githubusercontent.com/11800714/80374564-1f03bf80-8897-11ea-9d5f-b7a76e0505fd.png)
However, for me the actual new hightlights don't really look like those:
![image](https://user-images.githubusercontent.com/11800714/80374723-68540f00-8897-11ea-88f6-ea0872b6a5ac.png)
