### ISSUE TITLE
White-on-White text on workspace change

### ISSUE THREAD

**Issue by BrunoNZ** [linuxmint/mint-themes#268]
The text that appears on workspace change is now white, without shadows, and it's hard to read it on White/Light backgrounds. The following images show the same text on version 1.8.4 and 1.8.3, respectively.

![bug_mintytheme](https://user-images.githubusercontent.com/1660320/81126159-db512b80-8f10-11ea-94b9-74f17a7c1fed.png)
![bug_mintytheme_2](https://user-images.githubusercontent.com/1660320/81126163-dee4b280-8f10-11ea-9601-05c8299f38b5.png)

**Comment by JosephMcc** [comment]
That's because the themes are updated to work with Cinnamon master. On master there is a background box behind the text similar to other cinnamon dialogs. Once the new Cinnamon is released this will take care of itself.
