### ISSUE TITLE
Dark theme not work in Chromium web sites

### ISSUE THREAD

**Issue by ozelot379** [linuxmint/mint-themes#269]
In web sites, it's possible to add CSS in the media selector `@media (prefers-color-scheme: dark) { ... }` and the CSS is rendered, if the system using a dark theme

If I use a dark mint-theme, in Firefox this will work, but not on Chromium

I don't know whether it's an issue on linux api or this theme or Chromium

But I think it should also work on Chromium, because for instance on Windows 10 or macOS, Chromium supports that CSS, if the dark mode is enabled in the system settings

I use the follow versions:
OS: Linux Mint 19.3
Desktop: Cinnamon 4.4.8 (Default APT Repo)
mint-themes: 1.8.5 (http://packages.linuxmint.com/pool/main/m/mint-themes/mint-themes_1.8.5_all.deb)
Chromium: 83.0.4103.61 (Default APT Repo, no snap)
Firefox: 77.0.1 (Flatpak)

**Comment by JosephMcc** [comment]
If this works properly with Firefox but not Chromium, I'd lean towards it being a Chromium issue. Have you tried it with other dark themes to test it's specific to our themes?
