### ISSUE TITLE
[question] how do I install these themes?

### ISSUE THREAD

**Issue by arnotes** [linuxmint/mint-themes#270]
how do I install these themes?
also. do they include the windows borders and icons?

**Comment by LinuxOnTheDesktop** [comment]
These themes are built into Mint.
The Mint-X and Mint-Y themes do include 'border' and 'window controls' themes.
The [Mint forum](https://forums.linuxmint.com/index.php) is a better place for such questions.

**Comment by JosephMcc** [comment]
These easiest way to install these themes is to build and install the deb.
