### ISSUE TITLE
Active/inactive window difference too subtle

### ISSUE THREAD

**Issue by timabell** [linuxmint/mint-themes#281]
I finally realised the reason I reliably fail to copy text from the terminal - I don't realise the terminal doesn't have focus, and I can barely tell because the only difference is an almost imperceptibly darker title at the top of the window (this is aggravated because the terminal doesn't actually focus when you highlight text in it, but that's a different issue).

Active
![window title active](https://user-images.githubusercontent.com/19378/85681914-ae74f580-b6c3-11ea-884c-71b8ec423e4b.png)

Inactive
![window title inactive](https://user-images.githubusercontent.com/19378/85681923-b03eb900-b6c3-11ea-8cda-6f7d35f5901a.png)

Amongst a lot of visual noise from a busy desktop with many windows this is impossible to spot.

I would like to see something like a completely inverted colour for the active window title.

**Comment by brownsr** [comment]
You might like to give other themes a try as well.  Generally we have been increasing contrast over the last few versions, and as an example a snapshot of my own desktop using the Mint-Y (dark) window controls as they are in the Mint 20 beta below looks  clearer than the example you have shown above.  It is certainly an area where we continually review to achieve the best blend of style and usability that we can, so we will bear your comment in mind.

Regards

Simon
![Screenshot from 2020-06-25 12-37-53](https://user-images.githubusercontent.com/6322481/85713595-6e247000-b6e1-11ea-9120-e3131a5a367f.png)

**Comment by JosephMcc** [comment]
Thanks for the feedback. As noted above, this is something that is constantly looked at and tweaked. But also as @brownsr said, a different theme might be more suited to your personal taste.

**Comment by timabell** [comment]
Thanks for responding. That does look marginally better. I have been trying the different themes that came with mint, but they all seem to suffer from the same issue more or less. I tried looking to download some themes but didn't manage to find what I was after.
