### ISSUE TITLE
Invisible "back" arrow with Mint-Y-Dark buttons in Firefox

### ISSUE THREAD

**Issue by leandromartinez98** [linuxmint/mint-themes#282]
The "back" button arrow in Firefox becomes invisible in the dark-y themes:

![image](https://user-images.githubusercontent.com/31046348/85808622-c7b18c80-b72b-11ea-81d5-dfa598979e8c.png)

**Comment by JosephMcc** [comment]
Close and reopen Firefox after changing the theme. That fixes the issue here.
