### ISSUE TITLE
popup menu in cinnamon scale difficult to read

### ISSUE THREAD

**Issue by brainchild0** [linuxmint/mint-themes#283]
Many but not all of the Mint themes make the popup menu displayed in the Cinnamon scale view (thumbnails of all open windows arranged on a grid filling the entire screen) appear with red text against a low-opacity background.  This combination is visually cluttered, and makes it difficult to read the text.  Other themes present  a much nicer combination, text of a neutral color against an opaque background.

The red tone is also used in the symbol for closing the window, not only in the scale, but also in  popup lists in the application switcher showing open window of each application.  This tone appears harsh in comparison to the gentle shapes of Cinnamon themes, and the simple colors of many.

Perhaps making the latter  design universal across all the themes would improve their appeal.

**Comment by smurphos** [comment]
This needs to be fixed 

Mint-Y - https://github.com/linuxmint/mint-themes/blob/master/src/Mint-Y/cinnamon/sass/_common.scss#L375

Mint-X is usable but the color scheme doesn't really match the rest of the theme - https://github.com/linuxmint/mint-themes/blob/master/src/Mint-X/theme/Mint-X/cinnamon/cinnamon.css#L213

**Comment by brainchild0** [comment]
And the glyph for closing the window: [src/Mint-Y/cinnamon/common-assets/misc/close.svg](https://github.com/linuxmint/mint-themes/blob/master/src/Mint-Y/cinnamon/common-assets/misc/close.svg).
