### ISSUE TITLE
Request to make Mint themes available as a Snap package. (Please hear me out)

### ISSUE THREAD

**Issue by imarkskinner** [linuxmint/mint-themes#285]
Firstly its not my intention to discuss the pros or cons of snap packages.

Secondly, I appreciate the Mint devs reasons for blocking snap packages and I don't intend to debate that either.

However the fact remains that currently Mint users who decide to install snap apps (or are forced to due to lack of other options) are being left stuck in the middle with ugly un-themed applications tarnishing their otherwise beautiful desktops. As I understand it with my limited knowledge a snap app can only use themes that are also packaged in a snap.

If I'm corrrect in this I would implore someone to package the mint themes as a snap package so we can once again enjoy a nice looking Mint experience. Please see this from the users point of view and overlook the negative feelings towards the snap store to make our experience better. 

Edit: This also applies to the Mint family of icons.

**Comment by iKarith** [comment]
I won't speak for the Mint developers, nor am I interested in a flamewar over the issue, but I can tell you that I'm not certain that I wish to be beholden to whatever terms are required to be granted permission to have my work allowed into the Canonical snap store. The best solution might be the contribution of whatever snap build files are required and an offer from someone willing to package them for Canonical's walled garden. In fact, it's possible to simply fork the repo and do that, pulling in changes as they are made, and pushing them out as they go. Debian packages often include watchfiles to help automate knowing there's a new version to be packaged. Setting that up on the git repo might be worthwhile.

**Comment by JosephMcc** [comment]
I don't think we have any intention of doing this currently. But that doesn't stop someone else from packaging them if they wish to.
