### ISSUE TITLE
Mint-Y design request: make rounded corners more rounded

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint-themes#286]
If rounded corners were more rounded, then the buttons and other interactive things would be a bit differentiated from the rest.
**Examples:**
![button-corner-radius](https://user-images.githubusercontent.com/31940713/86541006-35ea1200-bed7-11ea-8251-8752ed6e682d.png)
The Mint-Y rounded corners on buttons and alike are so subtle, it just looks like rectangles with one missing pixel on each 4 corners!

**Comment by JosephMcc** [comment]
Thank you for the suggestion but for now we have no plans to change the themes design. Will keep this in mind however.
