### ISSUE TITLE
Mint-X theme for "Controls": Firefox bookmarks separators in sub-folders become invisible

### ISSUE THREAD

**Issue by jrw** [linuxmint/mint-themes#291]
In LinuxMint 20, when using the Mint-X theme for the Controls (buttons) items, separators in Firefox bookmarks toolbar sub-folders become invisible.  They become visible again by switching to Mint-Y theme for Controls.

To reproduce:

1. Use Mint-Y theme (System Settings -> Themes -> Controls -> Mint-Y)
1. Make the Firefox bookmarks toolbar visible (Hamburger menu -> Customize -> Toolbars -> Bookmarks Toolbar)
2. Create a sub-folder in the toolbar (right click -> create folder)
3. Add some items in the sub-folder (right click -> new bookmark)
4. Add a separator between items (right click -> new separator)
5. The separator should be visible in the toolbar sub-folder
5. Switch to the Mint-X theme 
6. Now the separator in the bookmarks sub-folder will be invisible
7. Switching back to the Mint-Y theme restores the visibility of the separator

**Comment by JosephMcc** [comment]
I can reproduce this issue but at the moment am unsure of a proper fix for it.

**Comment by jrw** [comment]
In my case, the solution was to switch to a different theme.  It literally took me weeks to realize the the problem of the missing separators was caused by my choice of theme and not by some Firefox flaw.

    On Friday, September 11, 2020, 10:43:43 AM EDT, JosephMcc <notifications@github.com> wrote:  
 
 


I can reproduce this issue but at the moment am unsure of a proper fix for it.

**Comment by JosephMcc** [comment]
Fixed by https://github.com/linuxmint/mint-themes/commit/0fdfe5f406c7b7ecf102cbc81988350f91e3ef46
