### ISSUE TITLE
request for introducing total black theme as dark is not dark enough

### ISSUE THREAD

**Issue by sidmint** [linuxmint/mint-themes#292]
dark themes are good but total black [base colour is hex code 000000] themes are absent in Mint for people who love it like me. Black is good when working in very dark environment and dark still has enough light felt when pupils expands.

'Darkest' variants of Flat remix is a very good example. Can base on it too as its quality is very good already. Just ask people, I think they'll love it.

**Comment by JosephMcc** [comment]
Thank you for the suggestion but for now we have no plans to support yet another variation of the theme.
