### ISSUE TITLE
same icon themes for Qt and GTK applications

### ISSUE THREAD

**Issue by dev-abir** [linuxmint/mint-themes#293]
Icon theme for Qt applications remains "Mint-Y" on changing icon theme from "System Settings" app.

Qt theme changes on changing GTK theme, but icon theme remains same... This creates an inconsistency for Qt apps like using light icon theme(Mint-Y), while the whole application uses a dark theme....

Right now we have to manually change icon themes through "Qt 5 configuration tool". I think this should be done automatically....

**Comment by JosephMcc** [comment]
This isn't really the place for this. I don't know how it can be fixed but it would probably have to be done at the DE or distro level. Someone can correct me if I'm wrong.
