### ISSUE TITLE
[Request] Release 1.8.6 in Github

### ISSUE THREAD

**Issue by kevinsmia1939** [linuxmint/mint-themes#295]
Hello,

I see that the changelog have release 1.8.6. but on github release is 1.8.0. 
If you don't mind, can you release1.8.6 on github as well? 

Thank you.

**Comment by mdinslage** [comment]
In the meantime you can just grab it here.
http://packages.linuxmint.com/pool/main/m/mint-themes/

**Comment by kevinsmia1939** [comment]
> In the meantime you can just grab it here.
> http://packages.linuxmint.com/pool/main/m/mint-themes/

Thanks, was not aware of that.
