### ISSUE TITLE
Start including calendar-day-with-events in a real theming effort

### ISSUE THREAD

**Issue by ccprog** [linuxmint/mint-themes#296]
As far as I am aware, there currently is no use case for this class included in Cinnamon, it only seems to be there as a leftover from old Gnome calendar.

But now, since I have published my [Calendar with public holidays](https://cinnamon-spices.linuxmint.com/applets/view/329) applet, I get requests to enhance it to actually include configurable events. The [last one](https://github.com/linuxmint/cinnamon-spices-applets/issues/3296) explicitely proposed to leverage this class to introduce separate visual representations for public holidays (styled with `.calendar-nonwork-day`) and other events (styled with `calendar-day-with-events`). 

This would be, in my opinion, a good idea, but it depends on at least standard themes containing styles that fullfill sensible usability criteria.

Currently, if you set the two classes against each other, you get

```
.calendar-nonwork-day {
  color: #202020; /* or #f0f0f0 for dark */
  background-color: transparent;
  font-weight: bold; }

.calendar-day-with-events {
    font-weight: bold;
    color: #cccccc;
}
```

This will not work, especially with dark themes. Equally, me styling the applet without knowledge of the installed theme will also fail. 

So while I am completely aware that my position as an applet author does not give me leverage in core development, I find myself with an existing tool that I still cannot use.

**Comment by JosephMcc** [comment]
The calendar theming has changed quite a bit in the new release so I'm not sure this is still relevant.
