### ISSUE TITLE
Glitchiness of Mint-Y and Mint-Y-Dark themes in e.g. sqlitebrowser

### ISSUE THREAD

**Issue by dancesWithBugs** [linuxmint/mint-themes#298]
I've encountered this on Cinnamon edition live distro. Just boot, `apt-get install sqlitebrowser` and switch themes to reproduce.

Mint-X as baseline for comparison: The Clear-button is visible, all lines are visible, selecting text (triple click) and typing overwrites existing content as expected.

https://user-images.githubusercontent.com/75453205/103238650-a1271500-494b-11eb-9b9a-fc8f73467358.mp4

In Mint-Y some lines are missing from the start, and the selection isn't cleared when typing.

https://user-images.githubusercontent.com/75453205/103238769-f6fbbd00-494b-11eb-9208-62ec51efa2fa.mp4

Mint-Y-Dark adds an additional glitch where the Clear-button is invisible (albeit functional).

https://user-images.githubusercontent.com/75453205/103238726-da5f8500-494b-11eb-95c9-b5f84409bcad.mp4

PS: Despite the bugs I'm absolutely in love with how harmonious Mint-Y-Dark looks. The various shades of gray work just so well together and the colors are just vibrant enough to highlight relevant parts yet not distracting. It's a pleasure to look at. Thank you. :)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/mint-themes/commit/c71c760709fed358c2c4f8010e8dc38a9c1f2d68 Address the main issue here which is showing the double text when doing a rename. While it still has problems in the dark theme, I don't think those are fixable without a major redesign of the theme which is out of scope for now.
