### ISSUE TITLE
Title bar height is 4px smaller and button are smaller

### ISSUE THREAD

**Issue by orbitalchicken** [linuxmint/mint-themes#299]
Linux Mint Cinnamon 20.1. 

With the default font for title bar (Ubuntu Medium), the title bar height appear 4px smaller and buttona are also smaller than on Mint 20.0 and 19.3 or than with Noto Sans Bold. 

However when I select the font Noto Sans Bold, (I had to add the font), the problem is not there and the Title bar height is the same as is 20.0 and 19.3. 
![image](https://user-images.githubusercontent.com/9101553/102721990-25cebf00-42cc-11eb-8d53-9fdc6105e2a1.png)
![image](https://user-images.githubusercontent.com/9101553/102721995-28c9af80-42cc-11eb-96d0-65ab1d88df65.png)

**Comment by JosephMcc** [comment]
Closing this since the window titilebar handling is no longer even done by the Metacity theme in Cinnamon.
