### ISSUE TITLE
Mate with Mint-Y: black icons in programs

### ISSUE THREAD

**Issue by linluc** [linuxmint/mint-themes#301]
This has been tested on two different laptops (both with Intel video cards) using the latest, fully updated 20.1 MATE edition. I know I've seen more programs affected by this, for now this issue can be easily reproduced using either Double Commander or Inkscape,  both presented below (after changing the theme the program must be restarted):

![image](https://user-images.githubusercontent.com/30745201/105642187-34be0980-5e56-11eb-85f3-80e29fd1af4a.png)

I've checked the program logs and system logs and I don't see anything obvious related to this problem. Since Mint-Y is the default theme, I hope this issue will catch some attention. This will encourage me to report even more issues I have encountered :-)

**Comment by apandada1** [comment]
I don't know about double commander. In inkscape you can open settings and choose any icon theme.

**Comment by JosephMcc** [comment]
Since you are using Mate, I know when changing themes, it can change all your themes at once. That includes the icons. There is a way to change them individually but I'm not looking at it right this moment.

**Comment by JosephMcc** [comment]
Closing this since it isn't a bug. It also has nothing to do with the gtk themes. This is just a difference between Mint-X and Mint-Y.
