### ISSUE TITLE
[Mint-Y] Client-side decorated windows have much weaker drop shadows than server-side decorated windows.

### ISSUE THREAD

**Issue by Uldreth** [linuxmint/mint-themes#303]
If the Mint-Y theme is used, server-side decorated windows have a drop shadow around them, while client-side decorated windows have a dark border, but no shadow. This is a theme issue, likely related to the peculiarities of the Arc theme. Other themes based on different themes (for example those based on Materia) have proper drop shadows for both server and client-side decorated windows.

Steps to reproduce:

1) Set one of the Mint-Y themes (I personally used Mint-Y-Darker-Aqua).
2) Set a bright/white background or open an app window that is brightly colored.
3) Open a client-side decorated window (for example Gnome Disks) and move it over the bright background.
4) Observe the lack of shadows.
5) Open a server-side decorated window, for example Nemo and move it over the background.
6) Compare the difference between the two cases.

Expected behaviour:

For purposes of uniformization I would expect that both kind of windows would have the same characteristics, such as shadows. The observed discrepancy is visually jarring.
![mint-y_issue_1](https://user-images.githubusercontent.com/29836149/108848268-14ae7100-75e1-11eb-9b3e-49f8051ab615.png)
![mint-y_issue_2](https://user-images.githubusercontent.com/29836149/108848276-1841f800-75e1-11eb-8315-37b395878972.png)

**Comment by mtwebster** [comment]
I see a shadow - though it's more diffuse than wm-decorated ones. Maybe I misunderstand?

**Comment by Uldreth** [comment]
Maybe there is a very-very small shadow, but if there is it is barely visible and the primary element that separates the window from its contents is a flat black bar.

I am linking a new image on which I compare Nemo to Disks with both using the Mint-Y theme. This time the focus is on the server-side decorated window (Nemo), however note it seems to me (by changing focus around) that for client-side decorated windows the border/"shadow" is unchanged by focus (for server-side windows the shadow is much more pronounced when focused).

So in the linked screenshot you can essentially see the relation between shadows/borders when both windows are focused (because the CSD window has the same behaviour when unfocused as well).

Even if the CSD window has a meager shadow, the difference is quite significant, with CSD windows blending into their surroundings much more because the lack of the drop shadow .

![mint-y_issues_3](https://user-images.githubusercontent.com/29836149/108861164-39114a00-75ef-11eb-87a6-889d018465ee.png)

**Comment by Uldreth** [comment]
I have added yet another image in which I took screenshots of both windows in their focused states and moved them into one image.

[mint-y_issue_focused.pdf](https://github.com/linuxmint/mint-themes/files/6029737/mint-y_issue_focused.pdf)

**Comment by Uldreth** [comment]
I am adding yet another image that contains image of both windows being focused 
![mint-y_issue_focused](https://user-images.githubusercontent.com/29836149/108863569-9f976780-75f1-11eb-8a11-29d943ff50b4.jpg)

**Comment by user1-github** [comment]
To me, the bigger issue here is the ugly small dark window border of CSD windows which is very noticeable when used with Mint Y "Darker" themes, as can be seen in the screenshots. I hope this will also be taken into consideration besides the smaller shadows issue.
