### ISSUE TITLE
[Mint-X] Gnome application's notifications too transparent

### ISSUE THREAD

**Issue by mfreeman72** [linuxmint/mint-themes#304]
When using Gnome applications (such as Geary or the Reversi game, for example), they have some kind of notification system within the program that drops down from the top of the window. If I'm using Mint-Y or most other themes, it has a theme-appropriate background. However, if using the Mint-X theme, the background is fully transparent, which makes the notification extremely difficult to read.

**Comment by JosephMcc** [comment]
Thank you for the report. I'll look into it. I could have sworn there was a way to bring this up in gtk3-widget-factory but I can't seem to figure out how now.

**Comment by Odyseus** [comment]
Hello, everybody.

> I could have sworn there was a way to bring this up in gtk3-widget-factory but...

@JosephMcc: You might have found out by now, but in case that someone else needs to know, here is how:

![app-notification](https://user-images.githubusercontent.com/3822556/130157803-026d52d0-dcc5-4a05-bfcf-34fc06bdc295.png)

In page 2 of the `gtk3-widget-factory` **(\*)** interface, the top left corner vertically oriented **SpinButton** triggers the visibility of the application notification *widget* **(\*\*)**.

In the image, the *widget* with `app-notification` CSS class (the one seen bellow the page switcher) has the style set by the commit at 32e7130af1b7c2f8f7f1fe4e70ff3f80c8b7f136.

**(\*)**: `gtk3-widget-factory` command is available after installing the package called `gtk-3-examples`.
**(\*\*)**: note that the application notification isn't actually a widget, [but a mix of widgets, a CSS class and behaviors](https://stackoverflow.com/a/45437257).

**Comment by JosephMcc** [comment]
Haha. Yes I did. I stumbled on it again by accident. Forget about that one when I haven't used it in awhile. Thanks though!
