### ISSUE TITLE
Dark themes lack button contrast

### ISSUE THREAD

**Issue by gunchleoc** [linuxmint/mint-themes#305]
#### Expected behaviour

I can see what's on the buttons

#### Actual behaviour

I can't see what's on the buttons. Example screenshots from Inkscape & Geany:

![theme-geany](https://user-images.githubusercontent.com/4095570/111025989-c6baab00-83df-11eb-8e7c-0ab26172b7a7.png)
![theme-inkscape](https://user-images.githubusercontent.com/4095570/111025990-c7534180-83df-11eb-8734-91a07570e301.png)

Note how the "close" button for the active tab in Geany is completely invisible, and all other buttons are very hard to see.

#### Steps to reproduce the behaviour

1. Control Center
2. Look and Feel
3. Appearance
4. Select the `Mint-Y-Dark-Red`theme (or any other default dark theme)
5. Open Geany

#### MATE general version

1.24.0

#### Linux Distribution

Mint 20.1

**Comment by dev-abir** [comment]
In settings, change both the "Icon", and "Controls" theme, to a dark theme, it should be resolved after that.

**Comment by gunchleoc** [comment]
No it doesn't unless I gave up using any of the Dark themes and switch to something with a light background.

**Comment by dev-abir** [comment]
Actually I am using cinnamon, and not facing such issue. Maybe it is MATE specific... Sorry for that...

**Comment by JosephMcc** [comment]
This isn't a problem with the themes. Dark themes have limitations with some apps. As noted above, if you set the icon theme to one of the dark versions, like Mint-Y-Dark-Red it fixes the issue.

**Comment by gunchleoc** [comment]
Ah, now I've found it, duh!

I still think it's a bug that the dark themes don't pick their dark icon sets per default. Can this be fixed? Where do I report it if this is the wrong package to do so?

**Comment by JosephMcc** [comment]
I'm not sure. Under Cinnamon they are separated so it's not a bug. You choose the ones you want. Nothing gets selected automatically.

**Comment by JosephMcc** [comment]
Actually we could set this in the index.theme for the dark themes and maybe in Mate it would get picked up? Not sure I don't use it that much. I'll dig a bit more and look into it.

**Comment by gunchleoc** [comment]
Thanks! It's certainly something a user would expect when selecting a theme, that the theme also selects its own icons etc. and that you then only customize it afterwards if you want.
