### ISSUE TITLE
Gtk2 applications menu separators are missing on Mint-Y themes

### ISSUE THREAD

**Issue by vassilisw** [linuxmint/mint-themes#306]
Tested with Mint 20.1Ulyssa.

**Comment by LinuxOnTheDesktop** [comment]
Screenshots would help, probably.

**Comment by vassilisw** [comment]
Right click menu
![image](https://user-images.githubusercontent.com/16954451/119208389-a1ff4580-baaa-11eb-8d3d-7a085fc30e3b.png)

Menu
![image](https://user-images.githubusercontent.com/16954451/119208418-c2c79b00-baaa-11eb-8cae-7cb2f95a9c8d.png)
