### ISSUE TITLE
Gtk4 support?

### ISSUE THREAD

**Issue by codic12** [linuxmint/mint-themes#312]
Don't think Cinnamon is getting ported to gtk 4 for a while, but applications slowly are, so it would be great to have support for it.

**Comment by JosephMcc** [comment]
Yeah, this is something we are certainly going to need to do soon. It's been in the back of my mind for a bit.

**Comment by apandada1** [comment]
Arc theme (on which Mint-Y is based) has been recently ported to GTK4. https://github.com/jnsh/arc-theme/releases/tag/20211018

**Comment by JosephMcc** [comment]
Mint-Y now has initial support for Gtk4 and Mint-X will be coming.
