### ISSUE TITLE
Headerbar too big in some applications 

### ISSUE THREAD

**Issue by codic12** [linuxmint/mint-themes#313]
In some applications, the Gtk headerbar is too big. for example:
Gnome Boxes, for a reference for how big the headerbar should be in Mint-Y:
![image](https://user-images.githubusercontent.com/48339289/116001752-efbb8780-a5aa-11eb-9f91-f8a2a3fdec61.png)

In Gnome System Monitor v40, the headerbar is far too big:
![image](https://user-images.githubusercontent.com/48339289/116001762-0235c100-a5ab-11eb-82f9-0d6947098f1e.png)

Same in Gnome Photos v40:
![image](https://user-images.githubusercontent.com/48339289/116001825-69537580-a5ab-11eb-9ea5-3a215e6a7421.png)

As an aside, same issue in Mint-X, though I don't even know if that's maintained.

**Comment by JosephMcc** [comment]
Will get to this at some point but it's low priority for the moment. The versions of those apps that are affected aren't even available in Mint.

**Comment by apandada1** [comment]
It seems that the apps which have icons in headerbar are too big compared to others.
In this screenshot, I am showing Foliate (it is affected), Blanket and Wike under Mint-Y-Darker theme
![Screenshot_2021-05-16_18-33-57](https://user-images.githubusercontent.com/3063132/118398269-7a0c7e00-b675-11eb-9c52-d0c6f3e63f28.png)

The same apps with Adwaita, where Foliate's headerbar is not too big.
![Screenshot_2021-05-16_18-34-20](https://user-images.githubusercontent.com/3063132/118398282-84c71300-b675-11eb-9c21-2547b21552ef.png)

@JosephMcc All these apps are available in Mint 20 and Mint 19 via flatpak and (some of them) also via PPA.

**Comment by codic12** [comment]
I believe this is due to the LibHandy headerbar widget which gtk apps have started moving towards; I believe by gnome 41 most of them will be using those.

**Comment by apandada1** [comment]
More specifically, this happens in version 1 of libhandy. Foliate ebook reader works with both libhandy1 and libhandy0, and with libhandy0, the headerbar height is normal.

_With libhandy-1_
![Screenshot from 2021-05-17 10-59-43](https://user-images.githubusercontent.com/3063132/118479385-94566280-b72e-11eb-818e-a25692ab074f.png)
_With libhandy-0_
![Screenshot from 2021-05-17 11-01-31](https://user-images.githubusercontent.com/3063132/118479390-96202600-b72e-11eb-9180-cf6750cb5301.png)


While libhandy1 is not available in Mint 20's official repositories, I had backported it from Ubuntu 20.10 repositories in the Foliate PPA. Also, the flatpak packages come with libhandy1.

**Comment by apandada1** [comment]
@codic12 @JosephMcc Could you verify whether my pull request fixes this?

**Comment by codic12** [comment]
Looks like it fixes it!

**Comment by clefebvre** [comment]
Nice work guys!
