### ISSUE TITLE
Extra horizontal rules in Gnome Clock

### ISSUE THREAD

**Issue by zhmars** [linuxmint/mint-themes#317]
Hi, after upgrade  to 1.8.8, I got some horizontal rules in Gnome Clock. Possibly related to https://github.com/linuxmint/mint-themes/pull/316

Is that intentional?

before (1.8.7)

![2021-06-13 14-01-33 的屏幕截图](https://user-images.githubusercontent.com/18466397/121797122-dc46a780-cc50-11eb-8103-5847c12b2903.png)

after (1.8.8)

![2021-06-13 14-01-01 的屏幕截图](https://user-images.githubusercontent.com/18466397/121797129-e7013c80-cc50-11eb-9fcb-b88e704ca16c.png)

**Comment by apandada1** [comment]
I used Arc Theme's libhandy configuration in #316 , and the horizontal rules got copied from that, so that was not intentional. 
I would let the community decide whether they want the horizontal rules or not (I personally like them, though).

By the way, does Adwaita have those horizontal rules?

**Comment by JosephMcc** [comment]
I'd say in this case the horizontal separator looks better. If we get other unintentional ones, we can fix them when they turn up.
