### ISSUE TITLE
Please consider these changes to make Mint-X title text darker [Feature Request]

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint-themes#318]
I already do this for my own installation but several other users suggested it to be shared here as a feature request.  This has been done for a while and no issues or aberrations have been encountered.

##// Modify existing theme in user space.
##// Make the title text darker in Cinnamon Metacity.
cp -a /usr/share/themes/Mint-X ~/.themes
sed -i 's+<constant name="C_title_focused" value="shade/gtk\:bg\[NORMAL\]/0.50"/>+<constant name="C_title_focused" value="shade/gtk:bg[NORMAL]/0.00"/>+' ~/.themes/Mint-X/metacity-1/metacity-theme-3.xml
sed -i 's+color: shade(@theme_bg_color, 0.5)+color: shade(@theme_text_color, 0.00)+' ~/.themes/Mint-X/gtk-3.0/gtk-widgets.css
#
##// Modify existing theme in user space.
##// Make the title text darker in GTK2/3 for GNOME applications.
cp -a /usr/share/themes/Mint-X-Aqua ~/.themes
sed -i 's+color: shade(@theme_bg_color, 0.5)+color: shade(@theme_text_color, 0.00)+' ~/.themes/Mint-X-Aqua/gtk-3.0/gtk-widgets.css

Thank you for your consideration.

![Screenshot from 2021-06-23 20-29-17](https://user-images.githubusercontent.com/45599505/123184506-d4151600-d461-11eb-9408-847a8ad21c0e.png)

**Comment by JosephMcc** [comment]
This should be improved now in git master.
