### ISSUE TITLE
Mint-Y in Cinnamon breaks 'rename' dialog in Konqueror and XnView MP

### ISSUE THREAD

**Issue by aprunai** [linuxmint/mint-themes#319]
Hello! I love Mint-Y and use it regularly, since I first installed Mint in fact. But some days ago I started using Konqueror under my Cinnamon DE and I found that as soon as I start renaming a file, text in the window becomes garbled; Mint's font is mixed with Konqueror's. Another user found this was due to Mint-Y, and in fact when changing theme to Mint-X the issue went away. The same thing happens with XnView MP, another software that's not native to Cinnamon. Can this be fixed? I'd really like to keep Mint-Y!

![immagine](https://user-images.githubusercontent.com/3056130/125986536-2219a551-2364-496c-b789-c756e13c8685.png)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/mint-themes/commit/c71c760709fed358c2c4f8010e8dc38a9c1f2d68 Should fix the issue with the double text when renaming. It still has issue using the dark theme but those aren't really fixable under Qt apps using the Gtk2 theme.
