### ISSUE TITLE
[Modification request] The light theme variation should use light sidebar background

### ISSUE THREAD

**Issue by hsbasu** [linuxmint/mint-themes#321]
In all theme variations, i.e. both light and dark, the background of the `sidebar` in `nemo` is black. This is in contrast to the expected behaviour of the light variation. I would suggest a light variant (may be slightly more darkened compared to the background of the contents) background for the sidebar for seamless user experience. Thus using a simple shell script one can get a fully light variant during day and fully dark variant during night.

**Comment by JosephMcc** [comment]
This is the case now.
