### ISSUE TITLE
Artwork Improvements for Mint 20.3

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mint-themes#323]
### General

- [x] Improve Nemo toolbar (https://github.com/linuxmint/nemo/commit/9927b5ed42c4f61f27b9c894587e01deb5583dac)
- [ ] New emblems in Mint-Y
- [ ] Better sounds

### Dark Apps

Once the theme gets support for gtk-dark.css, CSD windows work well everywhere since it's GTK who is rendering their titlebar. SSD windows on the other hand only work well with WMs which support this (muffin, marco, metacity). Xfwm doesn't support this, so if the theme enables gtk-dark.css and an app is using SSD titlebars (i.e. Xfwm titlebars) and dark mode, it will look dark but have a light titlebar, which looks completely broken. For this reason, SSD apps which support dark mode need to disable dark mode in Xfwm.

- [x] gtk-dark.css support (https://github.com/linuxmint/mint-themes/commit/da6bcf01e1356bad4cd20e14755039996cc21c9d)
- [x] hypnotix (https://github.com/linuxmint/hypnotix/commit/23f0350b9f9bce0afab196c0d1638e885d455a35)
- [x] xviewer (already has support, already enabled by default, disabled in Xfce https://github.com/linuxmint/xviewer/commit/8bac701b9df99d85f1299a3568086e390a0eb6ac)
- [x] celluloid (already has support, already enabled by default)
- [x] pix (https://github.com/linuxmint/pix/commit/81263e14251c006d0f7d467e76fe751f2776bebe https://github.com/linuxmint/pix/commit/2cc947f9237c2e3a6ac6c7e37453d5be8aced8da)
- [ ] gnome-terminal

### Titlebars

- [ ] Rounded tops
- [x] Larger buttons (https://github.com/linuxmint/mint-themes/commit/32d79a17f99f01ac77dfdb6aa875421ddd5f1103)
- [ ] Update Xfwm themes (wait until tints are decided first)
- [ ] MATE: Fix artefacts in metacity theme
- [ ] MATE: Patch appearance settings to fix warning message about the lack of metacity-2x theme
- [ ] Cinnamon: Remove metacity support in themes settings
- [ ] Muffin: render all windows with GTK borders

### Colors

- [x] Light Nemo Sidebar (https://github.com/linuxmint/mint-themes/commit/aadf71ac3cc792033a1628c76dfe62a0978ceea5)
- [ ] Light Thunar Sidebar
- [ ] Light Caja Sidebar
- [ ] Remove accents on toggled buttons?
- [ ] Remove accents in menus?
- [ ] Remove accents in lists?
- [ ] Tint greys (https://github.com/linuxmint/mint-themes/commit/3359bfcfbc582fdbb1d6c2d83e9b9f6d5afd0969)
- [ ] Ensure compatibility with tinted greys in GTK2 and Qt apps
- [x] Cinnamon Mint-Y should have a light panel (https://github.com/linuxmint/mint-themes/commit/8dea24cf59d89729ea34308bf3f5caddd79cafc7)

### Legacy

- [x] Remove Mint-Y-Darker (https://github.com/linuxmint/mint-themes/commit/98a1fdde7d1e52ef4f09e3591752869051a44149)
- [x] Provide a single metacity theme for Mint-Y (https://github.com/linuxmint/mint-themes/commit/19b3e19bb04f6ee9b083d799b2ad5a7e9760e889)
- [ ] Provide access to Mint-Y-Legacy-Darker in the repository

### Updates

- [ ] MATE: Switch to metacity or mint-y-legacy
- [ ] Xfce: Switch to metacity or mint-y-legacy

**Comment by JosephMcc** [comment]
Several of these are implemented in https://github.com/linuxmint/mint-themes/pull/322, including:

Light Thunar sidebar
Light Caja sidebar
Remove accents on toggled buttons
Rounded window borders

**Comment by hsbasu** [comment]
Having gradient color in panel would be great as it would provide a 3D look.

**Comment by JosephMcc** [comment]
@hsbasu In what panel? And we are mostly talking Mint-Y here, so gradients and a 3d look are not the overall style.

**Comment by hsbasu** [comment]
> @hsbasu In what panel? And we are mostly talking Mint-Y here, so gradients and a 3d look are not the overall style.

The cinnamon panel, I was talking about, which holds the menu and other applets.

I tried using a css gradient in $panel_bg. But it isn't taking the gradient options.

**Comment by SebastJava** [comment]
@JosephMcc I was looking at your 32d79a1 More precisely, this new **src/Mint-Y/metacity-1/max-icon.svg** (https://github.com/linuxmint/mint-themes/commit/32d79a17f99f01ac77dfdb6aa875421ddd5f1103#diff-cb7890e8a7615f775d4850282ffb99dab21557536f4cab28a31c163a33216e04) and other new SVGs.

May i suggest you do Save as Plain SVG, to make those files smaller and faster, or, much better, Save as Optimized SVG, to remove the metadata and others, making it still smaller and faster.

Also, if you have some spare time, you could consider this: https://forums.linuxmint.com/viewtopic.php?f=211&t=357513

Thanks.

**Comment by JosephMcc** [comment]
@hsbasu In case you haven't found out yet, Cinnamon doesn't except css gradients. Look in the Mint-X or default Cinnamon theme to see how gradients are done.

**Comment by JosephMcc** [comment]
I'm closing this one now. We aren't working on 20.3 anymore plus most all of these that we decided to keep are now done. Pretty much all that's left would be switching Xfce and Mate to use Metacity by default if we choose. That one isn't really relevant to this repo.
