### ISSUE TITLE
Mint-Y Darker theme is just dark

### ISSUE THREAD

**Issue by joka42** [linuxmint/mint-themes#324]
![image](https://user-images.githubusercontent.com/68659955/135155747-89e6ca3d-ed24-42e0-a430-943a794955e6.png)

As seen in this image, the Mint-Y Darker theme is just dark. There was already a report of the Bug, but the "fix" does not work anymore, because the necessary option was removed from the settings.

see: https://github.com/linuxmint/mint-y-theme/issues/59

Related post on reddit:
https://www.reddit.com/r/linuxmint/comments/pwnyn9/linux_mint_202_cinnamon_darker_theme_is_just_dark/

**Comment by joka42** [comment]
I just tested other "darker" themes like Arc-Darker and the same issue occurs

**Comment by JosephMcc** [comment]
Sorry I can't be more help but somewhere along the line you set this setting somehow. You can check ~/.config/gtk-3.0/ and see if there is a settings.ini file in there that contains "gtk-application-prefers-dark-theme". If there is, it should be set to 0.

Outside of that, this isn't an issue with the theme. The -darker version of the theme is also being discontinued.
