### ISSUE TITLE
Creating a custom color theme

### ISSUE THREAD

**Issue by sometimes-retro** [linuxmint/mint-themes#330]
I was looking to make a custom color theme, because the color tint I wanted was about halfway between the Aqua and Blue themes provided. An estimate of the tint I'm looking at is around `#477295` in hex.

Is there a way to go about creating a custom theme? Or, would that be extremely involved, given the organization of the code? I have done this with the Arc themes, but they were set up differently.

Great job on the themes, and thank you for any help you can provide! :)

**Comment by clefebvre** [comment]
Have a look in https://github.com/linuxmint/mint-themes/blob/master/constants.py for the colors used by the different variants. You'll need to adapt this to your liking and recompile the package.

**Comment by sometimes-retro** [comment]
Thank you very much! What are the commands to compile it (my background is not in Python)? Are there any particular packages I'll need?

**Comment by clefebvre** [comment]
If you're completely new with git/dpkg-dev, then:

```
apt install mint-dev-tools
mint-build -g mint-themes
```

It will install far more than you need but it's the simplest solution.

This will get the github source code and build deb package. Once it's built it once, you can modify the files, and build manually with:

```
cd mint-themes
dpkg-buidpackage
```

**Comment by clefebvre** [comment]
Check https://linuxmint-developer-guide.readthedocs.io/en/latest/building.html for more info.

**Comment by sometimes-retro** [comment]
Thank you very much, again, for all your help! I just took a shot in the dark and used the `make` command and the output said it was missing `sassc` so I did an `aptitude search` for `sassc` and found both `sassc` and `pysassc`. I figured I'd install both just in case. I did a `make clean` and then `make` again, and it seems to have compiled without an issue. I've already tested them out and they seem to work well.

If I wanted to change the naming to something else so that they didn't conflict with already installed Mint themes, would I only have to add or alter the names in the file you mentioned or others as well? Would that be in the link you posted? I figured it might be too specific a question for the build guide.

**Comment by clefebvre** [comment]
yes, you'd need to modify string occurences and filenames, the easiest way would be with something like bulky for files and regexxer for strings, change Mint-Y to something else and respect the case when swapping names.

**Comment by sometimes-retro** [comment]
That's a great idea, thank you. Are the Darker themes still an option? Or, is that no longer part of the `mint-themes` package? I have an old set of Mint themes installed and the Darker themes are present, but I didn't see them in the folder with the others after making the package.

**Comment by clefebvre** [comment]
it's in https://github.com/linuxmint/mint-themes-legacy

**Comment by sometimes-retro** [comment]
Thank you so much @clefebvre ! I set up everything with the `mint-themes-legacy` package and it all compiled without an issue and now I have working themes with the old dark style. I really appreciate you taking the time to help me with this. :)
