### ISSUE TITLE
Inkspace warnings: Ignoring unrecognized CSS property: block-progression

### ISSUE THREAD

**Issue by andrewdbate** [linuxmint/mint-themes#334]
When I run the script `src/Mint-Y/gtk-3.0/render-assets.sh` I get the warnings for each png rendered:
```
** (org.inkscape.Inkscape:52013): WARNING **: 18:17:15.063: Ignoring unrecognized CSS property: block-progression
** (org.inkscape.Inkscape:52013): WARNING **: 18:17:15.068: Ignoring unrecognized CSS property: block-progression
** (org.inkscape.Inkscape:52013): WARNING **: 18:17:15.079: Ignoring unrecognized CSS property: block-progression
...
```
I am running Inkscape 1.1.1 (the latest version). I have not tested whether these warnings occur with earlier versions of Inkscape.

The rendered png files look correct. The files generated are not binary identical to those committed into the git repo, but they look identical.

**Comment by JosephMcc** [comment]
I don't see those warnings running Inkscape on Mint but it is an older version. Will keep this in mind moving to Mint21 and the newer base.

**Comment by SebastJava** [comment]
This happens with the new Inkscape 1.1.1. This CSS property is deprecated, and removed from this new Inkscape. I did a quick web search and found this: https://webplatform.github.io/docs/css/properties/block-progression/. So, this property has initial (default) value set to `tb`, and this is the value specified in the `src/Mint-Y/gtk-3.0/assets.svg` file. So, I assume this property could just be deleted from the SVG file, and things would remain the same.

> This property has been dropped from the current version of [CSS Writing Modes specification](http://dev.w3.org/csswg/css-writing-modes=the). You are encouraged to manipulate an element’s writing mode via the [writing-mode](https://webplatform.github.io/docs/css/properties/writing-mode) property instead.

So, it would be more accurate to replace this obsolete property with this new **writing-mode**. But this new mode still has the same initial value: `horizontal-tb`. So, I think I just don't care and I will try to simply delete this old property from the SVG file.

To be tested later today:
1. Open `src/Mint-Y/gtk-3.0/assets.svg` file in a text editor.
2. Search and replace all `block-progression:tb;` with nothing (just delete it). Save.
3. Test it running `render-assets.sh`.

**Comment by SebastJava** [comment]
Quickly tested: it looks okay at first sight.

Next, while we are at it, you could also search and replace `--export-png` with `--export-filename` in the `src/Mint-Y/gtk-3.0/render-assets.sh`.
