### ISSUE TITLE
Mint-Y themes broken

### ISSUE THREAD

**Issue by NickVolt77** [linuxmint/mint-themes#337]
I've seen that someone changed Mint-Y themes to have light taskbar. This is nonsense. If you want to have light taskbar, make new themes with new names. **Changing existing themes is wrong.** Now I need to search for a new theme with dark taskabr and light menu. This shouldn't be done like that. That's way Linux has such a bad opinion. You can't change people themes just like that. Want full light theme? Make them as new. I vote to restore old Mint-Y theme.

**Comment by mtwebster** [comment]
This is a bit of an over-reaction.

If you're on Mint 20.3 beta:
```
apt install mint-themes-legacy
```

**Comment by NickVolt77** [comment]
I'm on Manjaro Cinnamon. What now? I don't see this in a repo.
This is not over-reaction. Changes should not be made like this. You can't replace theme with new theme and claim that it has been fixed - it wasn't fixed, it have been changed. It is no longer Mint-Y-Blue in my case. Tomorrow someone replace Cinnamon's code with Gnome and say "this is Cinnamon now, if you want real Cinnamon do apt install cinnamon-legacy"?

**Comment by clefebvre** [comment]
The legacy theme includes both metacity and gtk themes so can you have the exact same look you had before.

**Comment by firepainting** [comment]
I totally agree with @NickVolt77.

I want only the panel/taskbar to be dark, and everything else light. 

Please consider restoring the previous Mint-Y "theme desktop".

Meanwhile I'm going to try the legacy stuff, although I don't really prefer doing this.

Thank you.
