### ISSUE TITLE
[Cinnamon - and other DEs?]: upgrading when using a now-unsupported theme creates window button glitches

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mint-themes#338]
To reproduce the problem that I have in mind, the following sufficed on two computers.

- On Mint 20.2 Cinnamon, have Mint-Y Darker (or Mint-Y-Dark?) as your window border theme. [EDITED.]
- Upgrade in-place to 20.3.
- Open a terminal (using either the Gnome terminal or the XFCE terminal).
- Hover over a window button on the terminal. One will see something like this:

![image](https://user-images.githubusercontent.com/47056543/148547669-90d057e6-6500-4b6d-8e6b-4a06510bd1ba.png)

The cause of the problem, I think, is that the 'Dark' themes have been removed (or rather pushed into the legacy package).

**Possible solutions**

1) Put something in the release announcement or in a release note about the problem.

And/or

2) Upon installation of 20.3 Cinnamon ensure that the system is not trying to use any themes that no longer exist. Do this by switching the user, automatically, to a supported theme.

Or, best:

3) Upon installation, check whether the user is using a depreciated theme. If he/she is, then offer to install the legacy package. If that offer is declined, proceed as 2.

**Comment by Lurux** [comment]
This does not only apply to people using "darker" themes, but to people using **dark window borders** in general.

I too got glitchy window borders after ugrading to 20.3 using a dark theme.

I suggest updating your title to "dark theme" as the "darker" themes are no longer supported I'm pretty sure.

**Comment by LinuxOnTheDesktop** [comment]
> I suggest updating your title to "dark theme" as the "darker" themes are no longer supported I'm pretty sure.

My point is - for this is what I reckon is happening - as follows. The dropping of support for those 'darker' themes is too ungraceful: one receives no message about it and one ends up with glitchy window buttons.

**Comment by Lurux** [comment]
Oh wait - I thought you were talking specifically about the titlebars, since that's the example you used to illustrate your issue.

I guess I'll have to open another issue for this - the titlebars get borked, too, when using the dark theme, because the standalone "mint-y-dark" window border theme similarly got removed (the new version just adapts to the GTK theme)

**Comment by LinuxOnTheDesktop** [comment]
@Lurux 

My mistake. I was confusing the original issue, which is about malfunctioning titlebar buttons, with a different theming problem. Also: it may be that, as you say, thing are as follows. The malfunctioning titlebar problem affects not only those who were using Mint-Y Darker (_sic_) but also those using Mint-Y Dark (_sic_). (I have deleted the post of mine that was confused.)

**Comment by clefebvre** [comment]
Section added in the announcements to clarify the situation.

**Comment by Lurux** [comment]
@clefebvre, I guess you can also close #341 then (probably a dup of this, in the end)
