### ISSUE TITLE
20.3 Firefox has borders even when maximized, so we can't click tabs and scrollbars from the screen edge

### ISSUE THREAD

**Issue by Lurux** [linuxmint/mint-themes#339]
Firefox has borders even maximized with the new 20.3 theme, so the user can't access tabs or the scrollbar by slamming the mouse to the screen edge and clicking there.

Here's a close-up look of the borders in the top-left corner of Firefox when maximized. The border corner is highlighted in red.
![ff-borders](https://user-images.githubusercontent.com/35870988/148564470-3a150b21-fc59-457d-b036-70f814289f32.png)

**Comment by mtwebster** [comment]
ref: https://github.com/linuxmint/mint20.3-beta/issues/5

Firefox issue, fixed in ff 96.  You can work around it by running firefox with GTK_CSD environment variable set.

```
GTK_CSD=1 firefox
```

**Comment by Lurux** [comment]
Hmmm, interesting. Yeah, I should have specified that I'm using CSDs, I forgot that wasn't the default. Thanks !

**Comment by Lurux** [comment]
@clefebvre, I just noticed this problem also affects Thunderbird, has a fix been sent there as well ?

**Comment by mtwebster** [comment]
Yes, they're based on the same source

**Comment by mmortal03** [comment]
> ref: [linuxmint/mint20.3-beta#5](https://github.com/linuxmint/mint20.3-beta/issues/5)
> 
> Firefox issue, fixed in ff 96. You can work around it by running firefox with GTK_CSD environment variable set.
> 
> ```
> GTK_CSD=1 firefox
> ```

I'm on Linux Mint 20.3, with Firefox's Customize Toolbar -> Title Bar unchecked, and setting this causes the minimize, maximize, and close (x) buttons to not be clickable from the top edge of the screen. Actually, not only from the top edge of the screen, but you can *only* click on the actual symbols for each -- the region around each isn't even clickable.

Any idea how to fix this? Installing legacy themes seems to have no impact on this.
