### ISSUE TITLE
Firefox border / corner issue when title bar hidden

### ISSUE THREAD

**Issue by changke** [linuxmint/mint-themes#342]
Hi, after updated to Mint 20.3 with new Mint-Y theme I noticed this issue:
- I use Firefox and set to hide title bar, also have the official green theme on.
- With new Mint-Y theme, the top corners don't shown correct, with extra gray border and square corner (see screenshot).
- Can be mitigated by allow showing title bar.
- No such problem before updating.
![ff-mint-y-top-left](https://user-images.githubusercontent.com/272572/148606628-1c36603a-dc83-4323-b98f-f39ef4256f99.png)
![ff-mint-y-top-right](https://user-images.githubusercontent.com/272572/148606629-f24e7901-776a-492f-82ff-19257e52d492.png)

Could also be a Firefox issue though.

Thanks!

**Comment by clefebvre** [comment]
A fix was sent upstream and it's coming in Firefox 96 afaik.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/mint-themes/issues/339
