### ISSUE TITLE
Custom theme with Controls Mint-X-blue and Window Border Mint-Y-blue

### ISSUE THREAD

**Issue by Mavhod** [linuxmint/mint-themes#343]
I just update linuxmint 20.3, I found Window Border in Mint-Y will be only green color if I change Controls theme to Mint-X.

I want linuxmint can set Controls to Mint-X-blue and Window Border to Mint-Y-blue like previous version.

**Comment by clefebvre** [comment]
This isn't possible with the new theme. However you can get the old theme back using Legacy:

`apt install mint-themes-legacy`

Then select Mint-Y-Legacy-Blue as window border.
