### ISSUE TITLE
Mint 20.3 restoring to default Mint Y Green at every startup

### ISSUE THREAD

**Issue by viveksreedharan88** [linuxmint/mint-themes#345]
![Before Start up](https://user-images.githubusercontent.com/76948666/148632777-26f0a692-c60a-4539-8d97-4b5467f6c830.png)
![After Startup](https://user-images.githubusercontent.com/76948666/148632778-36529b62-fabb-445f-8ea8-7027faf16b03.png)
Hi. Ever since 20.3 stable Cinnamon was released, I am noticing no matter any custom theme/icon/color i set in Themes, it gets restored to default Mint Y Green at start up. This happens everytime. What is set by the user is not retained at all. Appreciate a fix here.

**Comment by smurphos** [comment]
Do you get any output from the terminal command - `find $HOME ! -user $USER`

**Comment by viveksreedharan88** [comment]
Yes, but nothing related to themes.

**Comment by viveksreedharan88** [comment]
vivek@vivek-HP-340S-G7-Notebook-PC:~$ find $HOME ! -user $USER
/home/vivek/Videos/AnyDesk/outgoing root (734093468)-root (783115203) 4.anydesk
/home/vivek/Videos/AnyDesk/outgoing root (734093468)-root (783115203) 1.anydesk
/home/vivek/Videos/AnyDesk/outgoing root (734093468)-root (783115203) 3.anydesk
/home/vivek/Videos/AnyDesk/outgoing root (734093468)-root (783115203) 2.anydesk
/home/vivek/Videos/AnyDesk/outgoing root (734093468)-root (783115203) 0.anydesk
/home/vivek/libfprint/_build/examples/c590b3c@@identify@exe
/home/vivek/libfprint/_build/examples/c590b3c@@identify@exe/identify.c.o
/home/vivek/libfprint/_build/examples/c590b3c@@identify@exe/utilities.c.o
/home/vivek/libfprint/_build/examples/c590b3c@@identify@exe/storage.c.o
/home/vivek/libfprint/_build/examples/c590b3c@@verify@exe
/home/vivek/libfprint/_build/examples/c590b3c@@verify@exe/verify.c.o
/home/vivek/libfprint/_build/examples/c590b3c@@verify@exe/utilities.c.o
/home/vivek/libfprint/_build/examples/c590b3c@@verify@exe/storage.c.o
/home/vivek/libfprint/_build/examples/verify
/home/vivek/libfprint/_build/examples/c590b3c@@img-capture@exe
/home/vivek/libfprint/_build/examples/c590b3c@@img-capture@exe/utilities.c.o
/home/vivek/libfprint/_build/examples/c590b3c@@img-capture@exe/storage.c.o
/home/vivek/libfprint/_build/examples/c590b3c@@img-capture@exe/img-capture.c.o
/home/vivek/libfprint/_build/examples/img-capture
/home/vivek/libfprint/_build/examples/c590b3c@@manage-prints@exe
/home/vivek/libfprint/_build/examples/c590b3c@@manage-prints@exe/utilities.c.o
/home/vivek/libfprint/_build/examples/c590b3c@@manage-prints@exe/manage-prints.c.o
/home/vivek/libfprint/_build/examples/c590b3c@@manage-prints@exe/storage.c.o
/home/vivek/libfprint/_build/examples/identify
/home/vivek/libfprint/_build/examples/c590b3c@@enroll@exe
/home/vivek/libfprint/_build/examples/c590b3c@@enroll@exe/utilities.c.o
/home/vivek/libfprint/_build/examples/c590b3c@@enroll@exe/storage.c.o
/home/vivek/libfprint/_build/examples/c590b3c@@enroll@exe/enroll.c.o
/home/vivek/libfprint/_build/examples/manage-prints
/home/vivek/libfprint/_build/examples/c590b3c@@cpp-test@exe
/home/vivek/libfprint/_build/examples/c590b3c@@cpp-test@exe/cpp-test.cpp.o
/home/vivek/libfprint/_build/examples/cpp-test
/home/vivek/libfprint/_build/examples/enroll
/home/vivek/libfprint/_build/meson-logs/install-log.txt
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-list-supported-devices@exe
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-list-supported-devices@exe/fprint-list-supported-devices.c.o
/home/vivek/libfprint/_build/libfprint/fprint-list-supported-devices
/home/vivek/libfprint/_build/libfprint/FPrint-2.0.typelib
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_bozorth3_bz_drvrs.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_binar.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_bozorth3_bz_io.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_contour.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_matchpat.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_ridges.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_bozorth3_bz_gbls.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_imgutil.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_dft.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_globals.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_bozorth3_bz_alloc.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_getmin.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_bozorth3_bozorth3.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_maps.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_chaincod.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_loop.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_quality.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_shape.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_sort.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_morph.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_util.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_init.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_detect.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_block.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_line.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_free.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_link.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_remove.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_bozorth3_bz_sort.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_log.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_xytreps.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@nbis@sta/nbis_mindtct_minutia.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_vfs101.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_aesx660.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_aes1660.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_vfs301.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_aeslib.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_goodixmoc_goodix.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_upek_proto.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_etes603.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_aes4000.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_aes2501.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_synaptics_bmkt_message.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_goodixmoc_goodix_proto.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_aes3500.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_vfs5011.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_vcom5s.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_upekts.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_aes1610.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_upektc.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_aes3k.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_aes2550.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_synaptics_synaptics.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_aes2660.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_uru4000.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/meson-generated_.._fpi-drivers.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_vfs0050.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_elan.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_upeksonly.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_vfs301_proto.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-drivers@sta/drivers_upektc_img.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-private@sta
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-private@sta/fpi-byte-reader.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-private@sta/fpi-device.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-private@sta/fpi-ssm.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-private@sta/fpi-print.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-private@sta/fpi-image.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-private@sta/meson-generated_.._fpi-enums.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-private@sta/fpi-usb-transfer.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-private@sta/fpi-byte-writer.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-private@sta/fpi-image-device.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-private@sta/fpi-assembling.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-list-udev-rules@exe
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-list-udev-rules@exe/fprint-list-udev-rules.c.o
/home/vivek/libfprint/_build/libfprint/fp-enums.c
/home/vivek/libfprint/_build/libfprint/fpi-enums.h
/home/vivek/libfprint/_build/libfprint/libnbis.a
/home/vivek/libfprint/_build/libfprint/libfprint-drivers.a
/home/vivek/libfprint/_build/libfprint/libfprint-2.so.2.0.0
/home/vivek/libfprint/_build/libfprint/fpi-enums.c
/home/vivek/libfprint/_build/libfprint/fp-enums.h
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-2@sha/fp-print.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-2@sha/meson-generated_.._fp-enums.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-2@sha/libfprint-2.so.2.0.0.symbols
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-2@sha/fp-image-device.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-2@sha/fp-image.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-2@sha/fp-context.c.o
/home/vivek/libfprint/_build/libfprint/642ed89@@fprint-2@sha/fp-device.c.o
/home/vivek/libfprint/_build/libfprint/fprint-list-udev-rules
/home/vivek/libfprint/_build/libfprint/FPrint-2.0.gir
/home/vivek/libfprint/_build/libfprint/libfprint-private.a
/home/vivek/libfprint/_build/libfprint/60-libfprint-2-autosuspend.rules
/home/vivek/libfprint/_build/tests/test-fpi-ssm
/home/vivek/libfprint/_build/tests/59830eb@@test-fpi-ssm@exe
/home/vivek/libfprint/_build/tests/59830eb@@test-fpi-ssm@exe/test-fpi-ssm.c.o
/home/vivek/libfprint/_build/tests/test-fpi-device
/home/vivek/libfprint/_build/tests/libfprint-test-utils.a
/home/vivek/libfprint/_build/tests/59830eb@@fprint-test-utils@sta
/home/vivek/libfprint/_build/tests/59830eb@@fprint-test-utils@sta/test-utils.c.o
/home/vivek/libfprint/_build/tests/59830eb@@fprint-test-utils@sta/test-device-fake.c.o
/home/vivek/libfprint/_build/tests/59830eb@@test-fpi-device@exe
/home/vivek/libfprint/_build/tests/59830eb@@test-fpi-device@exe/test-fpi-device.c.o
/home/vivek/libfprint/_build/.ninja_log
/home/vivek/libfprint/_build/.ninja_deps
/home/vivek/libfprint/_build/doc/sgml.stamp
/home/vivek/libfprint/_build/doc/html.stamp
/home/vivek/libfprint/_build/doc/libfprint-2-overrides.txt
/home/vivek/libfprint/_build/doc/intro.xml
/home/vivek/libfprint/_build/doc/xml/fpi-device.xml
/home/vivek/libfprint/_build/doc/xml/fp-device.xml
/home/vivek/libfprint/_build/doc/xml/libfprint-2-doc.bottom
/home/vivek/libfprint/_build/doc/xml/api-index-full.xml
/home/vivek/libfprint/_build/doc/xml/intro.xml
/home/vivek/libfprint/_build/doc/xml/api-index-deprecated.xml
/home/vivek/libfprint/_build/doc/xml/fp-image.xml
/home/vivek/libfprint/_build/doc/xml/libfprint-2-doc.top
/home/vivek/libfprint/_build/doc/xml/fp-image-device.xml
/home/vivek/libfprint/_build/doc/xml/api-index-1.6.xml
/home/vivek/libfprint/_build/doc/xml/fp-context.xml
/home/vivek/libfprint/_build/doc/xml/fpi-print.xml
/home/vivek/libfprint/_build/doc/xml/annotation-glossary.xml
/home/vivek/libfprint/_build/doc/xml/object_index.sgml
/home/vivek/libfprint/_build/doc/xml/fpi-ssm.xml
/home/vivek/libfprint/_build/doc/xml/fpi-image.xml
/home/vivek/libfprint/_build/doc/xml/fpi-usb-transfer.xml
/home/vivek/libfprint/_build/doc/xml/fpi-assembling.xml
/home/vivek/libfprint/_build/doc/xml/fpi-context.xml
/home/vivek/libfprint/_build/doc/xml/fpi-image-device.xml
/home/vivek/libfprint/_build/doc/xml/fp-print.xml
/home/vivek/libfprint/_build/doc/xml/fpi-log.xml
/home/vivek/libfprint/_build/doc/libfprint-2-sections.txt
/home/vivek/libfprint/_build/doc/libfprint-2-unused.txt
/home/vivek/libfprint/_build/doc/html
/home/vivek/libfprint/_build/doc/html/driver-print.html
/home/vivek/libfprint/_build/doc/html/up-insensitive.png
/home/vivek/libfprint/_build/doc/html/deprecated-api-index.html
/home/vivek/libfprint/_build/doc/html/pt01.html
/home/vivek/libfprint/_build/doc/html/pt03.html
/home/vivek/libfprint/_build/doc/html/libfprint-2-Logging.html
/home/vivek/libfprint/_build/doc/html/libfprint-2-FpDevice.html
/home/vivek/libfprint/_build/doc/html/getting-started.html
/home/vivek/libfprint/_build/doc/html/right.png
/home/vivek/libfprint/_build/doc/html/driver-helpers.html
/home/vivek/libfprint/_build/doc/html/libfprint-2-Internal-FpPrint.html
/home/vivek/libfprint/_build/doc/html/home.png
/home/vivek/libfprint/_build/doc/html/style.css
/home/vivek/libfprint/_build/doc/html/left-insensitive.png
/home/vivek/libfprint/_build/doc/html/libfprint-2-Internal-FpDevice.html
/home/vivek/libfprint/_build/doc/html/driver-img.html
/home/vivek/libfprint/_build/doc/html/intro.html
/home/vivek/libfprint/_build/doc/html/libfprint-2-Sequential-state-machine.html
/home/vivek/libfprint/_build/doc/html/libfprint-2-USB-transfer-helpers.html
/home/vivek/libfprint/_build/doc/html/pt02.html
/home/vivek/libfprint/_build/doc/html/right-insensitive.png
/home/vivek/libfprint/_build/doc/html/api-index.html
/home/vivek/libfprint/_build/doc/html/libfprint-2-Image-frame-assembly.html
/home/vivek/libfprint/_build/doc/html/index.html
/home/vivek/libfprint/_build/doc/html/libfprint-2-Internal-FpImage.html
/home/vivek/libfprint/_build/doc/html/libfprint-2-Internal-FpImageDevice.html
/home/vivek/libfprint/_build/doc/html/libfprint-2-FpImage.html
/home/vivek/libfprint/_build/doc/html/driver-misc.html
/home/vivek/libfprint/_build/doc/html/libfprint-2-FpImageDevice.html
/home/vivek/libfprint/_build/doc/html/libfprint-2-FpPrint.html
/home/vivek/libfprint/_build/doc/html/libfprint-2.devhelp2
/home/vivek/libfprint/_build/doc/html/libfprint-2-FpContext.html
/home/vivek/libfprint/_build/doc/html/left.png
/home/vivek/libfprint/_build/doc/html/driver-dev.html
/home/vivek/libfprint/_build/doc/html/advanced-topics.html
/home/vivek/libfprint/_build/doc/html/libfprint-2-fpi-context.html
/home/vivek/libfprint/_build/doc/html/up.png
/home/vivek/libfprint/_build/doc/libfprint-2-decl-list.txt
/home/vivek/libfprint/_build/doc/libfprint-2-undeclared.txt
/home/vivek/libfprint/_build/doc/libfprint-2-decl.txt
/home/vivek/libfprint/_build/doc/libfprint-2-undocumented.txt
/home/vivek/libfprint/_build/doc/libfprint-docs.xml
/home/vivek/fprintd/_build/src/net.reactivated.Fprint.Device.xml
/home/vivek/fprintd/_build/src/manager-dbus-glue.h
/home/vivek/fprintd/_build/src/libfprintd-private.a
/home/vivek/fprintd/_build/src/net.reactivated.Fprint.Manager.xml
/home/vivek/fprintd/_build/src/fprintd
/home/vivek/fprintd/_build/src/fprintd-marshal.h
/home/vivek/fprintd/_build/src/25a6634@@fprintd-private@sta
/home/vivek/fprintd/_build/src/25a6634@@fprintd-private@sta/meson-generated_.._fprintd-marshal.c.o
/home/vivek/fprintd/_build/src/25a6634@@fprintd-private@sta/device.c.o
/home/vivek/fprintd/_build/src/25a6634@@fprintd-private@sta/manager.c.o
/home/vivek/fprintd/_build/src/fprintd-marshal.c
/home/vivek/fprintd/_build/src/device-dbus-glue.h
/home/vivek/fprintd/_build/src/25a6634@@fprintd@exe
/home/vivek/fprintd/_build/src/25a6634@@fprintd@exe/main.c.o
/home/vivek/fprintd/_build/src/25a6634@@fprintd@exe/file_storage.c.o
/home/vivek/fprintd/_build/utils/fprintd-enroll
/home/vivek/fprintd/_build/utils/manager-dbus-glue.h
/home/vivek/fprintd/_build/utils/libfprintd_utils.a
/home/vivek/fprintd/_build/utils/fprintd-verify
/home/vivek/fprintd/_build/utils/marshal.c
/home/vivek/fprintd/_build/utils/marshal.h
/home/vivek/fprintd/_build/utils/6fd8973@@fprintd-verify@exe
/home/vivek/fprintd/_build/utils/6fd8973@@fprintd-verify@exe/verify.c.o
/home/vivek/fprintd/_build/utils/6fd8973@@fprintd-verify@exe/meson-generated_.._marshal.c.o
/home/vivek/fprintd/_build/utils/fprintd-list
/home/vivek/fprintd/_build/utils/6fd8973@@fprintd-list@exe
/home/vivek/fprintd/_build/utils/6fd8973@@fprintd-list@exe/list.c.o
/home/vivek/fprintd/_build/utils/6fd8973@@fprintd-list@exe/meson-generated_.._marshal.c.o
/home/vivek/fprintd/_build/utils/6fd8973@@fprintd-delete@exe
/home/vivek/fprintd/_build/utils/6fd8973@@fprintd-delete@exe/meson-generated_.._marshal.c.o
/home/vivek/fprintd/_build/utils/6fd8973@@fprintd-delete@exe/delete.c.o
/home/vivek/fprintd/_build/utils/6fd8973@@fprintd_utils@sta
/home/vivek/fprintd/_build/utils/6fd8973@@fprintd_utils@sta/meson-generated_.._marshal.c.o
/home/vivek/fprintd/_build/utils/6fd8973@@fprintd-enroll@exe
/home/vivek/fprintd/_build/utils/6fd8973@@fprintd-enroll@exe/meson-generated_.._marshal.c.o
/home/vivek/fprintd/_build/utils/6fd8973@@fprintd-enroll@exe/enroll.c.o
/home/vivek/fprintd/_build/utils/device-dbus-glue.h
/home/vivek/fprintd/_build/utils/fprintd-delete
/home/vivek/fprintd/_build/meson-logs/install-log.txt
/home/vivek/fprintd/_build/pam/ee96e48@@pam_fprintd@sha
/home/vivek/fprintd/_build/pam/ee96e48@@pam_fprintd@sha/pam_fprintd.c.o
/home/vivek/fprintd/_build/pam/pam_fprintd.so
/home/vivek/fprintd/_build/po/ka.gmo
/home/vivek/fprintd/_build/po/ro.gmo
/home/vivek/fprintd/_build/po/kn.gmo
/home/vivek/fprintd/_build/po/he.gmo
/home/vivek/fprintd/_build/po/wa.gmo
/home/vivek/fprintd/_build/po/ca.gmo
/home/vivek/fprintd/_build/po/bn_IN.gmo
/home/vivek/fprintd/_build/po/fur.gmo
/home/vivek/fprintd/_build/po/fr.gmo
/home/vivek/fprintd/_build/po/hr.gmo
/home/vivek/fprintd/_build/po/eu.gmo
/home/vivek/fprintd/_build/po/eo.gmo
/home/vivek/fprintd/_build/po/ru.gmo
/home/vivek/fprintd/_build/po/de.gmo
/home/vivek/fprintd/_build/po/mr.gmo
/home/vivek/fprintd/_build/po/ia.gmo
/home/vivek/fprintd/_build/po/zh_HK.gmo
/home/vivek/fprintd/_build/po/zh_CN.gmo
/home/vivek/fprintd/_build/po/fo.gmo
/home/vivek/fprintd/_build/po/da.gmo
/home/vivek/fprintd/_build/po/sr.gmo
/home/vivek/fprintd/_build/po/ml.gmo
/home/vivek/fprintd/_build/po/ms.gmo
/home/vivek/fprintd/_build/po/ta.gmo
/home/vivek/fprintd/_build/po/lv.gmo
/home/vivek/fprintd/_build/po/oc.gmo
/home/vivek/fprintd/_build/po/ja.gmo
/home/vivek/fprintd/_build/po/te.gmo
/home/vivek/fprintd/_build/po/sv.gmo
/home/vivek/fprintd/_build/po/gu.gmo
/home/vivek/fprintd/_build/po/tr.gmo
/home/vivek/fprintd/_build/po/pt.gmo
/home/vivek/fprintd/_build/po/nb.gmo
/home/vivek/fprintd/_build/po/sk.gmo
/home/vivek/fprintd/_build/po/as.gmo
/home/vivek/fprintd/_build/po/fi.gmo
/home/vivek/fprintd/_build/po/cy.gmo
/home/vivek/fprintd/_build/po/sq.gmo
/home/vivek/fprintd/_build/po/hi.gmo
/home/vivek/fprintd/_build/po/cs.gmo
/home/vivek/fprintd/_build/po/be.gmo
/home/vivek/fprintd/_build/po/fa.gmo
/home/vivek/fprintd/_build/po/et.gmo
/home/vivek/fprintd/_build/po/th.gmo
/home/vivek/fprintd/_build/po/sl.gmo
/home/vivek/fprintd/_build/po/nl.gmo
/home/vivek/fprintd/_build/po/nn.gmo
/home/vivek/fprintd/_build/po/pl.gmo
/home/vivek/fprintd/_build/po/es.gmo
/home/vivek/fprintd/_build/po/it.gmo
/home/vivek/fprintd/_build/po/ar.gmo
/home/vivek/fprintd/_build/po/ga.gmo
/home/vivek/fprintd/_build/po/pt_BR.gmo
/home/vivek/fprintd/_build/po/bg.gmo
/home/vivek/fprintd/_build/po/ast.gmo
/home/vivek/fprintd/_build/po/zh_TW.gmo
/home/vivek/fprintd/_build/po/en_GB.gmo
/home/vivek/fprintd/_build/po/el.gmo
/home/vivek/fprintd/_build/po/vi.gmo
/home/vivek/fprintd/_build/po/sr@latin.gmo
/home/vivek/fprintd/_build/po/lt.gmo
/home/vivek/fprintd/_build/po/az.gmo
/home/vivek/fprintd/_build/po/gl.gmo
/home/vivek/fprintd/_build/po/id.gmo
/home/vivek/fprintd/_build/po/hu.gmo
/home/vivek/fprintd/_build/po/or.gmo
/home/vivek/fprintd/_build/po/uk.gmo
/home/vivek/fprintd/_build/po/kk.gmo
/home/vivek/fprintd/_build/po/ko.gmo
/home/vivek/fprintd/_build/po/pa.gmo
/home/vivek/fprintd/_build/po/ca@valencia.gmo
/home/vivek/fprintd/_build/.ninja_log
/home/vivek/fprintd/_build/.ninja_deps
/home/vivek/fprintd/_build/data/fprintd.1
/home/vivek/fprintd/_build/data/pam_fprintd.8
/home/vivek/fprintd/_build/data/net.reactivated.fprint.device.policy

**Comment by clefebvre** [comment]
is mintwelcome running at startup?

**Comment by clefebvre** [comment]
wait... Mint-Y-Darker-Red?? That doesn't exist anymore... where did you get this from?

**Comment by viveksreedharan88** [comment]
> wait... Mint-Y-Darker-Red?? That doesn't exist anymore... where did you get this from?

I kinda took that as a back up from 20.2 : I placed it in /user/share/themes.

**Comment by viveksreedharan88** [comment]
> is mintwelcome running at startup?

Yeah! Its running!

**Comment by JosephMcc** [comment]
This is looks like the same issue as https://github.com/linuxmint/cinnamon/issues/10576

**Comment by clefebvre** [comment]
in Startup Applications can you disable mintwelcome and see if the problem still occurs?

**Comment by viveksreedharan88** [comment]
> in Startup Applications can you disable mintwelcome and see if the problem still occurs?

You just nailed it! Indeed mint Welcome screen is the culprit here! And logically, it kinda makes sense too! When mint welcome screen is running, it is set to green by default, all Mint Y icons/themes/control themes. However I hope this will get fixed. But disabling it at start up is a temporary fix. Thank you so much for suggesting this! I really appreciate this!

**Comment by clefebvre** [comment]
Ok good, that helps locate the problem but it still doesn't really explain it fully....

Two questions...

When your mintwelcome was enabled in Startup Applications.. did it have this option enabled as well? 

![image](https://user-images.githubusercontent.com/1138515/148686513-ac890164-c0b6-4a71-b984-ff83696f4060.png)

In other words, was it showing up on the screen when you logged in?

PS: It should be pretty easy to fix once we fully understand what is going on.

**Comment by viveksreedharan88** [comment]
> Ok good, that helps locate the problem but it still doesn't really explain it fully....
> 
> Two questions...
> 
> When your mintwelcome was enabled in Startup Applications.. did it have this option enabled as well?
> 
> ![image](https://user-images.githubusercontent.com/1138515/148686513-ac890164-c0b6-4a71-b984-ff83696f4060.png)
> 
> In other words, was it showing up on the screen when you logged in?
> 
> PS: It should be pretty easy to fix once we fully understand what is going on.

Yeah. It was checked initially. I have disabled it and also turned off in Start up apps too. The issue is solved now after disabliing it.  And to re-confirm that root cause is the welcome screen, after sometime I started the welcome screen from Start --> Welcome screen. As soon as welcome screen is loaded, the theme changes to Green. Hence, now the conclusion is the Welcome screen causing this trouble all along.

**Comment by clefebvre** [comment]
Ok, it must be a regression. I know where to look. I'll probably get it fixed tomorrow. Thanks @viveksreedharan88 .

**Comment by viveksreedharan88** [comment]
> Ok, it must be a regression. I know where to look. I'll probably get it fixed tomorrow. Thanks @viveksreedharan88 .

My pleasure! Happy to support! Meanwhile, a quick question. Once this is fixed, would we get the patch rolled via update manager? How does this work?

**Comment by clefebvre** [comment]
Yes, absolutely.

**Comment by clefebvre** [comment]
Ok, I can reproduce this. We'll definitely have a fix tomorrow.

**Comment by viveksreedharan88** [comment]
@clefebvre I just noticed there was an update released for Mint themes.... from 1.9.7 to 1.9.8. After installing that, its fixed now. I even enabled welcome screen in the start up, rebooted and checked. Its perfectly fine now. You may close this issue now. Thanks a lot for your support, really appreciate this!

**Comment by clefebvre** [comment]
No, a mintwelcome fix is needed still.
