### ISSUE TITLE
Request: Reinstate mint-y-darker

### ISSUE THREAD

**Issue by JackNWhite** [linuxmint/mint-themes#346]
Hi,

I would like mint-y-darker to be reinstated. I have read the message stating that it doesn't work with either light or dark icons, but I cannot say that it has ever been a problem outside Inkscape, but that seems to have been fixed now.

Was there any user feedback that informed the decision to remove it?

**Comment by viveksreedharan88** [comment]
You can add it by yourself by pasting the attached to /usr/share/themes. You`ll have to open themes in root. 

But eversince i tried to restore it, but i see the below issue. 
[Darker Themes back up.zip](https://github.com/linuxmint/mint-themes/files/7833429/Darker.Themes.back.up.zip)

https://github.com/linuxmint/mint-themes/issues/345

**Comment by artik** [comment]
I agree, many users still use mint-y-darker, and kind of forced to use the new Mint Y set

**Comment by viveksreedharan88** [comment]
> I agree, many users still use mint-y-darker, and kind of forced to use the new Mint Y set

Indeed, I am one of those users too! I like darker themes too!

**Comment by viveksreedharan88** [comment]
Here is the workaround. Go ahead and enable back the legacy themes

Run the below to enable back! You`ll find darker themes in legacy. 
sudo apt install mint-themes-legacy

**Comment by clefebvre** [comment]
Messing with /usr/share/themes as root is a bad idea. Mint-Y-Legacy was made specifically to let you get it back:

`apt install mint-themes-legacy`

Then choose Mint-Y-Legacy-Darker* in the themes settings.

**Comment by JackNWhite** [comment]
I appreciate the effort to rename those themes and add them to the repo, because certainly some people wouldn't bother, but it still means that the Darker theme will get more and more out of sync, and eventually something will break it.

Why not get rid of the Light or Dark theme instead of the Darker theme? What makes you think it is the least of the three?

**Comment by JosephMcc** [comment]
Because light and dark are the two standard variations. We need both of those to support things like the dark  mode that many apps offer.

**Comment by royclarke-0** [comment]
I'm with JackNWhite then Darker theme offers a nice compromise between the light and dark themes and it works so better with applications like LibreOffice without changing the color of the toolbar while retaining the darker menu bar. 

The issue with the legacy themes is that you lose all the nice touches of the rounded corners which makes the 20.3 seem more modern.

**Comment by viveksreedharan88** [comment]
@royclarke-0 I am using legacy only as a control theme. Icon Flat Remix. Theme i use mint Y, the new ones. I don't see any issues with this combination.

**Comment by slgobinath** [comment]
Hi, Mixing legacy themes with the new Mint-Y window controls looks like darker theme but there is a white window border around the title bar. How can I get rid of that border?
![image](https://user-images.githubusercontent.com/4003168/149423857-90ba28a6-d26d-4a97-9ba4-ff27e8d1863e.png)

**Comment by artik** [comment]
> Hi, Mixing legacy themes with the new Mint-Y window controls looks like darker theme but there is a white window border around the title bar. How can I get rid of that border? ![image](https://user-images.githubusercontent.com/4003168/149423857-90ba28a6-d26d-4a97-9ba4-ff27e8d1863e.png) Also the Tilix is using the old title bar with this mix.

https://github.com/linuxmint/mint-themes/issues/340 Let's see if it can be fixed
