### ISSUE TITLE
Mild inconsistencies in new theme in 20.3

### ISSUE THREAD

**Issue by li20034** [linuxmint/mint-themes#347]
I really like the new look in Mint 20.3 Xfce, so I wish to thank everyone who made that possible. I feel that it's one of the best looking lightweight Linux distros out there. However, I noticed some minor inconsistencies.

Firstly, in GTK2 (and Qt) apps, the menu still uses the blue color when highlighted (I'm on Mint-Y-Blue), but GTK3 menus now use a (better looking) light gray highlight. Furthermore, the seperator thickness is a bit inconsistent between GTK2 and 3. I think that is related to this configuration block.
```
style "separator_menu_item" {

  GtkSeparatorMenuItem::horizontal-padding = 0
  GtkWidget::wide-separators = 1
  GtkWidget::separator-width = 1
  GtkWidget::separator-height = 7
    
  xthickness = 1
  ythickness = 0
```

Changing ythickness to 2 makes it look similar to GTK3's seperators. 

Also the title font in apps which use client side decoration (e.g. xfce4-appearance-settings) appear noticeably darker than the title font in apps which use server side decoration (e.g. xfce4-terminal). This wasn't an issue with the old theme. Also, the new theme introduced rounded corners, which don't appear in apps which use CSD either.

I was wondering which files I could edit to make some of these look more consistent (I found one place outlined above, but the rest of this theme config is quite confusing to me). Thanks

**Comment by JosephMcc** [comment]
I don't understand why CSD apps wouldn't be using rounded corners on the top that is a weird one. I'll have to install xfce to test those out.

**Comment by li20034** [comment]
Actually, I think the CSD rounded corners might because I don't have compositing enabled in Xfwm. The rest of them seem unaffected by compositing though.

**Comment by JosephMcc** [comment]
The menu issues are fixed in git master. Will have to look a bit more into the differing titlebar text colors.

I'm pretty sure there is nothing we can do about not having rounded corners when you have compositing disabled.
