### ISSUE TITLE
Suggestion: The interface is too gray

### ISSUE THREAD

**Issue by luisrguerra** [linuxmint/mint-themes#348]
Please consider reducing gray in the interface. Some areas of the interface are very dark and make it look like 90s computer interfaces like Windows 95 and NextStep. I made with an image editor an example of what it might look like with light colors.
Another thing, the circle on the "X" exit button is unnecessary, it is more important for the visualization that the icon is sharp and that it has the proper contrast. Would be good if the circle could be seen only when the mouse is over it, but in red color to signify exiting the application.

![minty2](https://user-images.githubusercontent.com/31783838/148791073-169e2cb5-967e-4e51-9a3c-0e1aef219cdb.png)

Current colors:
![oldmint-y](https://user-images.githubusercontent.com/31783838/148791077-5ebe5b9e-ecba-4473-87d7-855991a0855c.png)

NextStep from 80s:
![nextstep_33_mail](https://user-images.githubusercontent.com/31783838/148791884-3a91bace-b3d3-40c7-9001-fe5e7ef8a79e.jpg)
Windows 95:
![Am_windows95_desktop](https://user-images.githubusercontent.com/31783838/148791889-596a493e-4486-4678-91f0-b85a51ce7fcc.png)

**Comment by SebastJava** [comment]
> Another thing, the circle on the "X" exit button is unnecessary, it is more important for the visualization that the icon is sharp and that it has the proper contrast. Would be good if the circle could be seen only when the mouse is over it, but in red color to signify exiting the application.

![GTK-to-metacity-bug](https://user-images.githubusercontent.com/31940713/149640762-4247f761-1328-4bae-b70c-3b3627c98ca9.png)

There is this old bug with this colored background on the "X" exit button. When you change the control theme color in the `cinnamon-settings themes`, this "X" doesn't change color before the next login, or just changing something else such as the icons. So, doing it as suggested above is a nice and simple way to avoid this bug.

Or maybe there could be two window borders to choose from: one grey with red on mouse hover, and one that is always red...

● ● ●
As for the window being too grey, personally, I would prefer going back to having the accent colors on the selected buttons and other stuff like we had before. Just like what can still be found on these old Mint-Y-Legacy themes...

**Comment by JosephMcc** [comment]
@luisrguerra Thanks for the feedback. We'll keep that in mind moving forward.
