### ISSUE TITLE
Mint 20.3 / Mint-Y: Firefox without titlebar has wrong borders in the corners

### ISSUE THREAD

**Issue by joka42** [linuxmint/mint-themes#349]
Mint 20.3 

Without Titlebar:

![image](https://user-images.githubusercontent.com/68659955/148847329-4407d661-60a7-48e1-a599-3a71c6f16f13.png)

With titlebar:

![image](https://user-images.githubusercontent.com/68659955/148847439-8c1b7f32-cb74-4618-8f05-8d8f604d4149.png)

**Comment by JosephMcc** [comment]
This has been brought up multiple times: https://github.com/linuxmint/mint-themes/issues/339
