### ISSUE TITLE
Request: Restore the "dark panel, light everything else" "theme desktop" (now Mint-Y-Legacy, previously Mint-Y)

### ISSUE THREAD

**Issue by firepainting** [linuxmint/mint-themes#352]
Hello.

My main motivation is that I want to use theme elements that are native to Mint if possible. Therefore I would not prefer any third-party stuff. I'm also assuming that Mint-Y-Legacy would soon be "abandoned."

The calendar applet on Mint-Y-Legacy looks ugly. 

![ugly legacy calendar applet](https://user-images.githubusercontent.com/50393421/149657658-9227fb89-3ad1-40b3-b38d-d7662b98a577.png)

The dots above look like [Issue #10583](https://github.com/linuxmint/cinnamon/issues/10583). However, the change in font size does not seem to be the culprit in my case (as reproduced in said Issue), because another "theme desktop" (the new Mint-Y-Dark) shows the dots as expected. 

I'm raising this because I don't want the design development for the previous Mint-Y to be discontinued, because the ugly would most likely be left ugly, like the Calendar applet.

I also did not leave a comment on the above Issue #10583 because I feel that Mint-Y-Legacy would not really be considered there because it's "Legacy."

Please restore the previous "theme desktop" Mint-Y (now Mint-Y-Legacy).

The light-colored "everything else" (pop-up menu, thumbnail headers, applets) is actually more of a need for me, the dark panel a (really) strong preference.

Side note: I'm also having the 1px border issue with the new themes (#340). (I just upgraded my two PCs to Mint 20.3 from 20.2)

Thank you.

**Comment by JosephMcc** [comment]
Thanks for the feedback, but at least for now, there is no plan to reinstate these other variations that are part of Mint-Y-Legacy.

**Comment by firepainting** [comment]
Hello again. Just wanted to say this as this preference of mine is getting more clear to me.

What I meant by "light everything else" was that anything with text on it the text should be dark on a light background.

Otherwise, for icons, a dark background (i.e., the panel/taskbar).

The only difference between Mint-Y and Mint-Y-Lecagy seems to be the panel color, and consequently, the applets' corresponding color.

I can do a bit of CSS and I think the new Mint-Y can be made to look like Mint-Y-Legacy.

Could you tell me which parts in `themes/Mint-Y/cinnamon/cinnamon.css` I should I look for?

I just saw the calendar applet for the new Mint-Y, it looks good!

Thank you.
