### ISSUE TITLE
src/Mint-Y/metacity-1/*.svg: SVG codings are far too complex, bloated (11 SVG files, up to 50X too big !)

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint-themes#354]
I guess a part of the problem comes from some repetitive edits made in Inkscape. I noticed, when you have some grouped elements, each time you move it, instead of changing the (x,y) coordinates of each element, you end up with a translation function being added. So, each time you move some group, you end up with an added layer of complexity !?

**This button-bg.svg is probably the best example. It is unbelievably far too complex. The SVG coding is 50X too long.** This circle is part of a group, within a group, which is part of a group, contained into a group. And since there was some moves made, there were lots of transforms added to those groups. And there was some "phantom" elements. Now, I just deleted everything and made a plain circle. The image is still exactly the same, but the file size went from... 105 lines down to... 2 lines !

**Done:**
1. Manual edits on most files.
1. All files are saved as optimised svg.
1. Quickly tested: it looks okay.

Please take a look at all these SVGs files lengths: the difference is huge ! Example: button-bg.svg was 105 lines long, now just 2 lines ! Compare the images: they remain unchanged, visually. The SVGs are re-edited to look exactly the same but made much more smaller and faster.

**Comment by SebastJava** [comment]
All okay now. Working fine here: https://github.com/SebastJava/mint-yz-theme

**Comment by LinuxOnTheDesktop** [comment]
I think that, except for fallback, the metacity themes are no longer used. So perhaps this issue should be closed.

**Comment by SebastJava** [comment]
I think the metacity themes are still being used on Mate versions !?

This whole story is very simple: all the images are still exactly the same, but the coding behind it was very complex and i just redraw all those images in a very simple manner, making files up to 50X smaller !! Already tested and used on a daily basis here...
