### ISSUE TITLE
[XFCE 20.3 - Mint-Y xfwm4] Mint Update launched from the 'applications menu' never launches maximized and instead is a teeny bit smaller

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint-themes#357]
Discussed in the following forum thread:
https://forums.linuxmint.com/viewtopic.php?f=90&t=366569

Simply put, on 20.3 XFCE (supposedly the "Mint-Y xfwm4" theme specifically) if you maximize Mint Update and then quit, then re-launch Mint Update via the XFCE applications menu, the window will not actually be maximized but will be a teeny bit smaller.

This "teeny bit smaller" means that, if you try to close the window by clicking in the very top-right of your screen, it will not close Mint Update's program window (but it _will_ close any maximized window that was open behind Mint Update!).

For reference this does not occur on 20.3 Cinnamon.

**UPDATE**: I've also confirmed that this issue occurs out-of-the-box on a live ISO/USB of Mint 20.3 XFCE.

**Comment by JosephMcc** [comment]
I'm closing this since I'm not sure this could be fixed in the theme without changing it's design. Like getting rid of the rounded corners which we don't want to do.

**Comment by NintendoManiac64** [comment]
So there's no way to have Mint Update actually start maximized?

Keeping rounded corners is fine, but rounded vs squared corners shouldn't make a difference for a maximized window.
