### ISSUE TITLE
GtkTreeView thin lines are almost invisible: 1px #F8F8F8 on white background

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint-themes#361]
...Or is it a bug with the WidgetFactory ?
**Mint-Y:**
![Widget-Factory-p3-Mint-Y](https://user-images.githubusercontent.com/31940713/151907059-cbf2e205-7cee-4c46-8872-18a8bb45cabd.png)

**Mint-Y-Legacy:**
![Widget-Factory-p3-Mint-Y-Legacy](https://user-images.githubusercontent.com/31940713/151907065-4041dcfe-c53b-40c9-ac7d-1764cdeca3a9.png)

**Comment by JosephMcc** [comment]
It's quite possibly in the theme but have you seen those in anything outside of widget factory? I can't remember ever seeing them in any real app.

**Comment by SebastJava** [comment]
> [...] Have you seen those in anything outside of widget factory?

No. Only in WidgetFactory, so far...
