### ISSUE TITLE
Bring Mint-Y Cinnamon shell theme in line with the GTK theme

### ISSUE THREAD

**Issue by Lurux** [linuxmint/mint-themes#362]
Now that the Mint-Y GTK theme has tuned down the accent colors, the shell theme's very flashy accent colors have been really jarring to me.

_Illustration: the menu's flashy accent colors are very jarring compared to the file manager's more toned down appearance._
![ctheme](https://user-images.githubusercontent.com/35870988/152057280-d1ad82a5-153c-4a78-87dd-9c1d647ddf38.png)

I'd like to suggest giving the shell theme the same treatment as the GTK Mint-Y theme, removing accent colors from most buttons and elements.

I'm willing to help if I get some pointers, however the theme seems really big and I don't know if there's surefire way to change the accent on all these elements.

___

Another small annoyance I'd like to talk about is the (not) rounded corners.

Since the new GTK theme has doubled down on using rounded corners everywhere, I think it would be beneficial if buttons in the shell had the same corner radius as the ones in the GTK theme.

_Illustration: the selected day in the calendar looks abruptly sharp. Other items, such as the menu categories, are affected._
![cangles](https://user-images.githubusercontent.com/35870988/152058436-b950d357-3f19-4788-9f96-797928a4109d.png)

I also think the background of the applets themselves should have the same radius as the window decorations.

**Comment by SebastJava** [comment]
1. Oh please, don't remove these colors from everywhere. Besides, in the Nemo file manager, in the sidebar, the selected items are still colored, so this Cinnamon menu does not look so awkward, in my opinion.
2. This Mint-Y color is not "flashy", but on high lightness, and thus in high contrast with the dark theme, and low contrast with the foreground white text, and grayish-yellowish, and... just not nice. I agree this color should be changed.
3. You currently have small colored items (assets), gray medium items (active buttons and such), and big colored areas such as big selections in Nemo. This could be considered awkward, bad. It could be better this way: colored small and medium items, and gray file selections.

To sum up, it feels like they are removing colors almost everywhere, except on large areas where it could possibly make it better to have a light colored tint. And, on top of that, this removal of colors on medium-sized elements is done with the promise of a new, more modern color palette. I am still waiting for this modern color palette. Many people are waiting for this. It is definitely needed.

Some people like "flashy" colors, and some others don't. So, why don't you make a color palette offering mixed choices of some subdued colors, some flat colors, and some vibrant colors ? And, if you still don't like it, you can still choose gray. :)

**Example:**

![image](https://user-images.githubusercontent.com/31940713/152585029-98f14a10-1567-4c85-ade3-8866a38eed01.png)
______

Yes, it would be appreciated to see more rounded corners. In fact, I would go the other way around: square windows —so there is no difference between maximized or tiled windows and "normal" windows— and rounded corners on buttons and entries. Not so much, just a bit more than the current settings. The current buttons and entries have rounded corners so subtle, it just looks like a bugged rectangle with a mixing pixel in each corner. Just take a look at the buttons right here in this GitHub interface: that's much better. Having rounded corners on buttons makes them look like... buttons !

P.S.: That's not the shell theme, that's the Cinnamon theme you are talking about. Wrong title ? The shell theme is for the Terminal, as far as I know.

**Comment by SebastJava** [comment]
Thinking about this again, on second thought, i think the best could be to keep those colored backgrounds on selected items, while the hovered items would get darkening on light themes, and lightening on dark themes. That's my suggestion.

So, in your example above (https://github.com/linuxmint/mint-themes/issues/362#issue-1121243832), the categories on the left would still be colored when selected, but this hovered application on the right would simply get a subtle 5% lighten. I agree it can get annoying to get this bold change on foreground and background colors when you are just moving your mouse around.

Additionally, i just found another subtle problem today. I found that your dark Cinnamon theme gets the same accent color as the light theme, so this doesn't help in making the colors less "flashy" on the dark Cinnamon Desktop themes. Check my related https://github.com/linuxmint/mint-themes/issues/370 on this.

And then, as mentioned before, there is a third problem: those Mint-Y colors are bad. But that's just my personal opinion.

P.S.: "Cinnamon Desktop themes" = Panel, Menu, Calendar, OSD, etc. It is this "Desktop" theme you choose on the bottom part in Menu > Preferences > Themes.

**Comment by JosephMcc** [comment]
Closing as it's very similar to https://github.com/linuxmint/mint-themes/issues/360
