### ISSUE TITLE
Question: How do I generate the assets with a different accent color?

### ISSUE THREAD

**Issue by joka42** [linuxmint/mint-themes#363]
Is there a simple way to generate the Inkscape assets with a different accent color? I could not figure it out in a decent amount of time.

I just created a different color palette in constants.py and copied one of the folders in src/Mint-Y/variations and renamed it. It worked, but obviously the colors of the assets are not correct and I could not find a script the generate them. Is there a way?

**Comment by SebastJava** [comment]
On the first time, you must run `./update-variations.py All` from your terminal, in the mint-themes directory. Later, you can replace `All` with one specific color name like `Blue` for quick testing.

More info here: https://github.com/SebastJava/mint-yz-theme/blob/master/Do-It-Yourself.md But this may not be up-to-date. This repository is currently going through a major overhaul and it is now messy, and incomplete.

**Comment by SebastJava** [comment]
Oops:

>With this Mint-Yz fork here, building Mint-Y-Colors is now 100% automated. As of August 2020, the following directories have to be edited by hand on the official Mint-Y:
* gtk-2.0/menubar-toolbar/
* gtk-3.0/thumbnails/
* cinnamon/thumbnails/
* xfwm4/ (3 colored assets)

That's not ready yet. Anyway, at least you can use my guide to understand how most things work.

**Comment by joka42** [comment]
Thanks, I don't know how I overlooked that script in the project's root dir. Thanks!
