### ISSUE TITLE
Metacity: When the window is tiled, the maximize function is presented with the unmaximize icon

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint-themes#365]
![Metacity-max-unmax-icon](https://user-images.githubusercontent.com/31940713/152701904-d99404d6-2220-49ae-9675-f7abbfb18aff.png)

**Comment by JosephMcc** [comment]
I'm going to merge a partial fix for this. It will fix the cases of tiling left, right, or to the corners. It won't fix tiling to the top or bottom half of the screen. The metacity theme spec doesn't support what we would need to do that. The plan in the next version of Cinnamon is to move to allowing the gtk theme to draw the window borders and this issue no longer exists there. The fix will cover the cases in Mate.
