### ISSUE TITLE
request for enhanced support for gnome apps

### ISSUE THREAD

**Issue by brainchild0** [linuxmint/mint-themes#368]
I realize   the enhancement request may not be among the most welcome for this project, but I am wondering whether it would be feasible for Mint themes to support better operation with GNOME core applications.

For example, gThumb presents with a dark background under a Mint theme  for which Mint applications show with a light background (see image).   If gThumb is run with a GNOME light theme selected, then the background is light.

![Screenshot from 2022-02-16 18-12-23](https://user-images.githubusercontent.com/34869175/154403781-34d936f4-8a9f-4681-8ebf-865cab157ae0.png)

**Comment by JosephMcc** [comment]
I think you are misunderstanding some things. Some applications, like gthumb, will automatically use the dark version of the theme if it's available. This has nothing to do with how mint-y supports gnome apps. In fact, it does exactly the same thing when using Adwaita. Which is the default "gnome theme". If you want different behavior you need to take that up with the gthumb developers.

**Comment by brainchild0** [comment]
By my observations, gThumb will use the Adwaita light theme when it is referenced by the proper environment variable (e.g. `GTK_THEME=Ambiance:light`).  In this case, the background would be light, and the other themed features of the application window would also follow the same  theme, Adwaita light.

Presently, the choice is to force the Adwaita light theme in gThumb using an environment variable set specifically to the invocation, but then also to accept the additional effects   of the theme, such as window decorations, or to accept the dark background, with the other features following from the Mint theme as desired.

My thought is that Cinnamon themes might be enhanced to include the features causing gThumb to display a light background the same as it does when the Adwaita light theme is active.

The observations I have made, as best I can determine,   do not support the suggestion that gThumb will use the dark version of the theme whenever it is available.

**Comment by JosephMcc** [comment]
Well first off if you are using `GTK_THEME=Ambiance:light` you aren't using Adwaita at all. You can effectively do the same thing by using Mint-Y:light instead.

> The observations I have made, as best I can determine, do not support the suggestion that gThumb will use the dark version of the theme whenever it is available

Your observations are mistaken. gthumb's code asks for it to prefer the dark variation of the theme when it is available. In short, Adwaita and Mint-Y perform the same. There isn't really anything to be done here.

**Comment by brainchild0** [comment]
Are you explaining that both light and dark are _variations_ given by the same _theme_, the latter of which is selected by the system and the former by the application?

**Comment by JosephMcc** [comment]
Yes. If I'm totally missing what you are trying to explain, I apologize.

**Comment by brainchild0** [comment]
Is there a setting for the environment variable to force of the light variation of whatever theme has been selected, without giving any explicit reference to the theme?

**Comment by JosephMcc** [comment]
Not that I know of but there could be. Many applications actually offer this as a setting in the preferences. gthumb just happens to be one that doesn't seem to.
