### ISSUE TITLE
.gitignore src/Mint-Y/variations/ is needed, otherwise things gets utterly complex when trying to update forks.

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint-themes#369]
`src/Mint-Y/variations/` should be included in the `.gitignore` file, otherwise things get utterly complex when trying to do all sorts of `fetch`, `merge`, `cherry-pick` or whatever git command to update any fork from this upstream source. Because these `src/Mint-Y/variations/` gets auto-updated all the time and they can differ in color and/or style, leading to 1000s differences.

My latest bad experience: how can i `git cherry-pick --no-commit 0c6b13d435edb3a60393a8d7f579d0298406961a` ?
([Mint-Y-Gtk2: Better match the menu to the gtk3 changes](https://github.com/linuxmint/mint-themes/commit/0c6b13d435edb3a60393a8d7f579d0298406961a))

This sounds impossible. I have 1000s conflicts. I will need to improvise with some other custom magic, once again...

I tried a pull request for this `.gitignore` a long time ago, and i never got any answer.

**Comment by SebastJava** [comment]
**.gitignore:**
```
src/Mint-Y/gtk-3.0/.sass-cache
src/Mint-Y/cinnamon/sass-cache

# SASS cache files
*.scssc

__pycache__/
usr/

# dpkg-buildpackage (auto-generated Debian files)
debian/.debhelper/*
debian/files
debian/mint-yz-theme.debhelper.log
debian/mint-yz-theme.substvars
debian/mint-yz-theme/*

src/Mint-Y/variations/
```

**Comment by JosephMcc** [comment]
Closing this since I can't see how it makes sense. Those files need to be tracked for changes and additions.
