### ISSUE TITLE
Missing information: GTK version ? Compatible with Linux Mint 19 and 20 ?

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint-themes#371]
GTK 3.22 or 3.24 ?

**Comment by JosephMcc** [comment]
Not really sure how relevant this is. Each version of Mint gets it's corresponding release of the themes. So it gets the version that works with that release of Mint. Which is what matters.

**Comment by SebastJava** [comment]
Okay, but i wanted to know this for this Mint-Yz fork i am currently working on. Forked from the latest: v1.9.8 

I am writing a README.md which says:

> First, check your system is not too old for this theme to work properly. This theme works well on Linux Mint 19, Linux Mint 20, and newer versions. (GTK+ 3.22 or newer)

Is this information correct ? Additionally, for future updates, it would be good to have this information easily available, somewhere.
