### ISSUE TITLE
Bottom rounded corners on the new Mint-Y-* themes for the terminal application

### ISSUE THREAD

**Issue by Vishvamitra** [linuxmint/mint-themes#381]
Hello! Since I really like the rounded top corners of the windows in the new Mint style, I've been wondering if it's possible to tweak the gtk-3.0.css file in order to provide bottom rounded corners, especially for the terminal emulator, since, at least in my case, it's the only program I usually depoly in non-maximized mode.

**Comment by JosephMcc** [comment]
Sorry but no. That actually isn't possible.

**Comment by mfreeman72** [comment]
An extension is available to do that for all windows (including the terminal) in the Adwaita theme in Gnome 40, 41, and 42 (https://fostips.com/rounded-bottom-corners-gnome-adwaita/). Could something similar be made into a Cinnamon extension? I know I'd love to see rounded bottom corners as an option in Mint themes, personally.
