### ISSUE TITLE
Will Mint-X be updated to GTK4?

### ISSUE THREAD

**Issue by johnsonmt01** [linuxmint/mint-themes#383]
Ubuntu MATE is retiring their Ambiance/Radiance themes with 22.04 LTS.  As I described in my appreciation forum post, that leaves the Mint-X theme as the last remaining non-flat 2010's-era theme included with a prominent distro.

[(https://forums.linuxmint.com/viewtopic.php?f=211&t=372108)]

Are there plans to maintain Mint-X with GTK4 updates, or will it also be retired in the near future?

**Comment by JosephMcc** [comment]
The current plan is to update it for Gtk4. As far as I know we aren't planning to retire it.
