### ISSUE TITLE
Nord colour palette option

### ISSUE THREAD

**Issue by mpaunovic** [linuxmint/mint-themes#384]
I was hoping if we could get the gorgeous Nord color palette option for both themes and icons/folders?

https://www.nordtheme.com/docs/colors-and-palettes

Thank you!

**Comment by mpaunovic** [comment]
I do not consider time is wasted when I am learning something new and interesting so thank you very much for the detailed answer.

Anyway, it's a shame really because I too think that it would attract more people. I'm sorry to say but those predominant dark gray shades and other washed out colors as defaults tend to be a tad boring, just my 2 cents. I find your fork much more appealing.

Thank you once again.

**Comment by WoBoCroc** [comment]
> 

This is exactly why I modify default Mint-Y themes in xfce to my liking.

**Comment by WoBoCroc** [comment]
> They don't want to change. I say it would attract more people, but the others don't seem to share that view.

Which is exactly why I modify Mint-Y themes in xfce to my liking. With every release Mint-Y themes become less and less legible. The contrast is being lost so I enhance it - mainly modify borders and box shadows to make windows stand out from the background more. It's easier to spot them when they overlap too.

**Comment by SebastJava** [comment]
@WoBoCroc 

Can you easily remember how you changed those box shadows ?
Don't work too hard on remembering these... That's just for later, maybe.

I am on LinuxMint Cinnamon 20.3. The shadows are okay for me on the main windows, but I'd like to get these shadows on the menu boxes, as seen here on your 1st screenshot. I thought it was not possible to change those shadows from within the theme, in Cinnamon. I am still unsure about this being possible.

The dark themes also needs stronger, darker shadows on all windows, IMHO.

Please take a look at my fork: https://github.com/SebastJava/mint-yz-theme#readme
I also did some work on contrasts... and colors... and design...

**Comment by WoBoCroc** [comment]
> @WoBoCroc
> 
> Can you easily remember how you changed those box shadows ? Don't work too hard on remembering these... That's just for later, maybe.
> 
> I am on LinuxMint Cinnamon 20.3. The shadows are okay for me on the main windows, but I'd like to get these shadows on the menu boxes, as seen here on your 1st screenshot. I thought it was not possible to change those shadows from within the theme, in Cinnamon. I am still unsure about this being possible.
> 
> The dark themes also needs stronger, darker shadows on all windows, IMHO.
> 
> Please take a look at my fork: https://github.com/SebastJava/mint-yz-theme#readme I also did some work on contrasts... and colors... and design...

The menu box shadows are configurable from the gtk.css file (I'm on xfce, mind you) - and it is under decoration:

decoration {
  border-radius: 0px 0px 0 0;
  border-width: 0px;
  box-shadow: 0 3px 9px 1px rgba(0, 0, 0, 0.5), 0 0 0 1px #BDBDBD;
  margin: 10px; }
  decoration:backdrop {
    box-shadow: 0 3px 9px 1px transparent, 0 2px 6px 2px rgba(0, 0, 0, 0.2), 0 0 0 1px #cacaca; }
  .fullscreen decoration, .maximized decoration, .tiled decoration, .tiled decoration:backdrop {
    border-radius: 0;
    box-shadow: 0 3px 9px 1px transparent, 0 2px 6px 2px transparent, 0 0 0 1px #cacaca; }
  .popup decoration {
    box-shadow: none;
    border-radius: 0; }
  .ssd decoration {
    border-radius: 0px 0px 0 0;
    box-shadow: 0 0 0 1px #BDBDBD; }
    .ssd decoration.maximized {
      border-radius: 0; }
  .csd.popup decoration {
    border-radius: 2px;
    box-shadow: 0 3px 9px 1px rgba(0, 0, 0, 0.5), 0 0 0 1px #939393;}
  tooltip.csd decoration {
    border-radius: 2px;
    box-shadow: 0 1px 3px 1px rgba(0, 0, 0, 0.2); }
  message-dialog.csd decoration {
    border-radius: 3px; }
  .solid-csd decoration {
    border-radius: 0;
    margin: 1px;
    background-color: #e8e8e8;
    box-shadow: none; }
    
 The menus are described by .csd.popup decoration :) This is what it looks like in your mint-y file after I modified this parameter:
    
![image](https://user-images.githubusercontent.com/106600190/173232497-7c4d7bff-15fc-48ad-aeee-8a3792ecb721.png)

**Comment by WoBoCroc** [comment]
> Thanks for the suggestion. Nord was mostly designed as a color palette for code editors from what I can tell. Not for the entire UI. It also seems there is already a theme out there based on it if that's what you want to use.
> 
> Just for general feedback, theming is a highly subjective area. If you ask 10 users what they like best, you get 10 different answers. So is the styling what you would call a bit "boring" or "generic"? Yes it is and that's how it needs to be. As soon as you do something else, you get a whole lot of unhappy users. You simply cannot cater to everyone's personal tastes.
> 
> We experimented with the more vibrant colors suggested by @SebastJava and the feedback from users wasn't great. That's why we still use the color scheme that we do.

I guess this is why we, the users, fork default Mint themes, and will continue doing just that. The "generic" problem you mentioned is real and is far more complex than just that, we get that. I just wish there was more to choose from Mint themes by default :) Current Mint-Y themes look really bland washed-out on poor TN screens (which are used by the vast majority of users). And I wouldn't have noticed that had I not switched to quality IPS panel recently. Increasing contrast just a bit (by improving shadows), making CSD-based windows and regular WM windows more consistent (especially in XFCE) would make one hell of a difference. Dark themes were never my thing - so I won't discuss the nord palette itself, although I must admit it looks great on KDE, though, especially with blurred transparency in kvantum themes. Keep up a good work!
