### ISSUE TITLE
No round corners in messagedialog (bug in gtk.css)

### ISSUE THREAD

**Issue by WoBoCroc** [linuxmint/mint-themes#389]
Mint-Y themes don't show round corners in messagedialog (xfce). It needs fixing
![graf](https://user-images.githubusercontent.com/106600190/172699024-f718c66a-ba80-45be-9447-e5aca640b7e2.png)

A fix looks like this:
headerbar,
.titlebar:not(headerbar) {
  min-height: 42px;
  padding: 0 7px;
  border-width: 0 0 1px;
  border-style: solid;
  border-radius: 8px 8px 0 0; 

by default border-radius was 0.

**Comment by JosephMcc** [comment]
Message dialogs do need a bit of work. Doing a lot of updating for Mint21. Will add this to the todo list. Thanks.

**Comment by JosephMcc** [comment]
This is already fixed in git master.

**Comment by WoBoCroc** [comment]
> This is already fixed in git master.

Thank you!
