### ISSUE TITLE
implement accent-color variable in libadwaita

### ISSUE THREAD

**Issue by apandada1** [linuxmint/mint-themes#391]
I am running [Blanket](https://github.com/rafaelmardojai/blanket) with Mint-Y theme, and it uses the variable `accent-colors` in its [css file](https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/stylesheet/_colors.scss#L6), and Mint-Y theme does not have it. As a result, icons of the active sounds are shown in white (almost invisible) in this theme, while they are nicely visible in libadwaita.

![adwaita](https://user-images.githubusercontent.com/3063132/161421442-fdc3c2aa-f587-4133-b2ad-690d35824cda.jpg)

![image](https://user-images.githubusercontent.com/3063132/179537888-ab3ee773-0794-4918-85d2-be6990928af2.png)
Here the active icon is white.

A similar issue was present in Arc Theme, and this might help fixing it in Mint-Y theme (and variants) as well. See https://github.com/jnsh/arc-theme/issues/179

**Comment by JosephMcc** [comment]
What Distro are you using?

**Comment by apandada1** [comment]
> What Distro are you using?

I am using Manjaro XFCE with the git code of mint-themes (it is easier to test latest packages in Arch based distros than in Mint). I have upgraded my Mint setups to 21 yet (and Mint 20 is not affected since libadwaita is not available there).

However, the issue should be present in Mint 21 beta (where Blanket can be installed as Flatpak). I will test it there and report back soon.

I realized that gnome-clocks is still using libhandy in Mint 21 (therefore, gnome-clocks is not affected), but Blanket and other libadwaita-based apps can be installed as Flatpak (some of them from PPAs and official repos), and they would be affected.

**Comment by JosephMcc** [comment]
I haven't dug into libadwaita enough yet or how it  works with flatpak. It's my understanding that you have to use the GTK_THEME environment variable to apply your theme. Does this still work using a flatpak? Some things I have to dig into.
