### ISSUE TITLE
LM 21 Cinnamon - When using dark theme Libreoffice buttons don't appear correctly.

### ISSUE THREAD

**Issue by Soremir** [linuxmint/mint-themes#394]
Just installed Linux Mint 21 and set the dark theme from the first steps from the welcome screen. Opened Libreoffice and some buttons don't appear correctly because (maybe?) the theme color matches with the icon color.
![1](https://user-images.githubusercontent.com/72141678/181903809-f4947f65-e289-4206-a740-f27e0949f714.png)

If set the theme to light mode, everything appears correctly.
![2](https://user-images.githubusercontent.com/72141678/181903859-f69a5017-7f8e-4b35-b32a-5e3b67eeb8f2.png)

**Comment by JosephMcc** [comment]
This isn't a fault of the gtk theme. It's the icon theme used in LibreOffice by default. If you go to Tools->Options->View you can download some other icon themes that work better with the dark theme.

**Comment by mfreeman72** [comment]
Unfortunately, no icon theme works well with LibreOffic dark mode. The problem for me is that LibreOffice itself doesn't handle dark mode well (which of course isn't Linux Mint's problem at all). For example, when there is a deactivated function, the icon is turned a light gray color, even when using an icon theme that says it's for dark mode. That means that deactivated icons are incredibly hard to distinguish from active ones, especially in a theme like Sifr, where the dark version of the icons are already  the same color as the deactivated icons. But even in any of the others, it's very hard to tell the difference unless you look really closely. Again, though, this is something to address with LibreOffice devs, not Mint devs.
