### ISSUE TITLE
LM 21 - Window title bar padding (close button)

### ISSUE THREAD

**Issue by schorschii** [linuxmint/mint-themes#396]
I installed LM 21 today and noticed that the top and right title bar padding is not consistent anymore:
![Bildschirmfoto vom 2022-08-15 17-29-34](https://user-images.githubusercontent.com/17480795/184666036-115eab2d-ce45-4e59-96d1-f87f302e14dd.png)

Is this intentional or a bug?

**Comment by JosephMcc** [comment]
There are reasons it's that way.  Matching the top to the side would require making the titlebar taller. Something users typically don't like. The padding on the side so that it can stay matched with csd windows like gnome-calculator. So in the end this isn't really a bug and there is really nothing that says they have to be the same.

**Comment by schorschii** [comment]
OK thanks for your explanation. I see you have put some thought into it but my first impression was that this is a bug and I think I'm not alone with this.
I understand that a taller title bar is not desired. How was this solved in Mint 20? From my point of view it was perfect there.
I wouldn't match the side padding with CSD windows because they generally look different. Just my two cents.

**Comment by schorschii** [comment]
Most people intuitively expect this padding to be consistent and it is recommended in most design guides ([e.g. here](https://influencevibes.com/spacing-basics-and-rules-every-designer-should-know/#:~:text=overall%20design%20composition.-,PADDING,-Strict%20padding%20must)).
MacOS for example also has some CSD windows with padding different from normal windows, but always consistent:
<img width="106" alt="Bildschirmfoto 2022-08-23 um 19 00 43" src="https://user-images.githubusercontent.com/17480795/186221678-93bfc75b-6977-458c-b2db-d37ab7703f50.png">
