### ISSUE TITLE
Editing the Mint-Y theme window in the layout: top corners angularity | window corners

### ISSUE THREAD

**Issue by kimariterikishi** [linuxmint/mint-themes#404]
Raised as a question...

The top corners of the Mint-Y theme are currently squared.
Is it possible to make the top corners angled? If so, which text file should be edited for this, and exactly which file and which line?
Is there a plan to make a theme editable?
Because it used to be possible to edit the **gtk.css** file, and, as far as I know, from Linux Mint 18.1 onwards the **cinnamon.css** file.

http://caverdan.com/Mint18Themes/chapters/chapter3Cinnamon.html

It used to be sufficient to edit this file (to enlarge the characters):

`/usr/share/cinnamon/theme/cinnamon.css`

OK, but I can't find a line that can be changed to make the top of the windows angled.
I can only find client-side decoration settings...
I have checked the theme directory (/usr/share/themes/Mint-Y/), in it the cinnamon, gtk-3-0, gtk-4.0 directories for the cinnamon.css files. I cannot change the window corners by editing any of these files.

Could it be the window manager **Muffin**? If so, how can the window corners be changed?

It would be nice if all Linux Mint themes had the option. (Mint-X, Mint-Y)

It would be nice to have an option to allow the user to change the appearance of the windows. If there is no such...

**Comment by JosephMcc** [comment]
There are currently no plans to add settings to change the style of window corners. For general questions, the Mint forums is the place to ask these things.
