### ISSUE TITLE
[21.0 Xfce] mint-y-dark themes still have light-colored title bars on some applications (e.g. terminal, Thunar)

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint-themes#406]
Simply put, on either a live session or a local installation that has been fully updated, using a mint-y-dark theme on Mint 21 Xfce results in some application title bars remaining as light-colored.

At least the following applications all still have light-colored title bars when using a mint-y-dark theme:

- Firefox
- mintUpdate
- Pix
- 'password entry' dialog window
- Software Manager
- Synaptic Package Manager
- Thunar
- Thunderbird
- xed
- xfce4-terminal

And yes, the issue persists even after a reboot on a local fully-updated installation.  For reference, this issue does *not* occur on a local installation of 20.3 Xfce (interestingly, the issue *does* occur on a live session of 20.3 Xfce however).

![screenshot](https://user-images.githubusercontent.com/11896003/191181573-276892e9-52e8-4965-a716-d020bf698951.png)

(fun fact - this is an issue [I noticed back on the 21.0 beta but bug reports were closed the very day that I was going to report it](https://forums.linuxmint.com/viewtopic.php?f=90&t=378140), and it's only until recently that I'm looking into moving over to Mint 21 and couldn't help but notice that this issue still exists)

**Comment by NintendoManiac64** [comment]
Where is that located?  I don't recall having to do that on Mint 20.3, and setting the icons tab in the same "Appearance" program to a dark theme made no difference.

Also, as shown in my screenshot, the title bar of the "Appearance" program correctly changed to a dark theme without issue despite the terminal and Thunar windows not.

Other software that correctly displays dark title bars are:

- Archive Manager
- Calculator
- Celluloid
- Disks
- Document Scanner
- Fonts
- Hypnotix
- Logs
- Notes
- seahorse
- thingy
- Warpinator
- Web Apps
- Xfce Screenshot
- Xfce Task Manager

**Comment by JosephMcc** [comment]
I just fired up XFCE to look. It's in the Window Manager settings. You need to set the theme there as well. Some work because they are client side decorated windows and the window borders are drawn by the app, not the window manager. This is part of the reason we've done away with having separate settings for window borders in Cinnamon.
