### ISSUE TITLE
Mint-Y Accent colors should be made darker for dark themes and subdued lighting environments

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint-themes#414]
**First of all, i feel Clément wanted to work on this alone, so i guess i shouldn't insist too much on this and i am currently busy anyway...**

I took just a quick look at https://github.com/linuxmint/mint-themes/blob/master/constants.py Most of those colors have the same values for light and dark theme variants, i.e. `y_hex_colors1` and `y_hex_colors2`. I hope this is not final. Most of the new `y_hex_colors1` looks great, but i think the `y_hex_colors2` should be made darker. You need to look at those `y_hex_colors2` against your dark themes background: `#383838`. And, maybe, try it with a dimmed room lighting too! You will probably find those colors too "flashy" when experienced in dark themes and subdued lighting conditions...

And, as if this was not complicated enough, i have been told there is no simple rule for the dark variants. And i find this sounds true. You can't just do a simple "darken 10%" on all `y_hex_colors1` to get the `y_hex_colors2`. Sometimes, i even go against the rules by increasing the saturation level on some color, after lowering the lightness by a big amount. But that is just an edge case, to say each color should be modified individually, for the dark variants.

**Examples:**

```
y_hex_colors1 = {}  # BASE
y_hex_colors2 = {}  # DARK
```
y_hex_colors1["Aqua"] = `#1f9ede`
y_hex_colors2["Aqua"] = `#007fbe`

y_hex_colors1["Blue"] = `#0c75de`
y_hex_colors2["Blue"] = `#0b6bcb`

y_hex_colors1["Orange"] = `#ff661a`
y_hex_colors2["Orange"] = `#d84800`

**Comment by SebastJava** [comment]
I forgot to mention these dark color variants were not totally improvised. I had some method. I adjusted these `y_hex_colors2` using this https://colorable.jxnblk.com/

I estimated the color contrast against the dark background should not exceed 3.0. My reference background is `#303030` here.

So i had some method to ensure those colors do not stand out too much from my `#303030`. But to get there, the lightness and saturation levels were re-adjusted in different ways from one color to another, as said before.

**Comment by LinuxOnTheDesktop** [comment]
I agree with SebastJava's point that the new accent colours glare a bit when one is using a dark theme.

However, I discover that the new accent colours slightly improve the readability of text when using dark themes. For, compare the following, which shows the Mint-Y-Dark-Teal theme,

![image](https://user-images.githubusercontent.com/47056543/209035470-1d5c4a95-7fd9-4b5e-b8d6-681521f02541.png)

with this, showing Mint-Y-Legacy-Dark-Teal:

![image](https://user-images.githubusercontent.com/47056543/209035677-212e1a71-d2cc-4bf0-8f92-c718628d1253.png)

_How then, when using dark themes, to have readability without glare?_ Here are some possibilities.

- Perhaps when text is highlighted, it ought to change its foreground colour.

- Perhaps one needs to find the exact right accent shade and pair it with the right foreground text colour and with the right background text colour. GitHub itself does a great job on that front. For, look at this (though I have had to scale it, which makes it look worse):


![image](https://user-images.githubusercontent.com/47056543/209036945-bf35f713-c598-4593-ac40-da7bbfe8afbc.png)

There there is no glare, but, also, no sacrifice in readability.

**Comment by LinuxOnTheDesktop** [comment]
@SebastJava 

Sorry if I miss something, but are we to take it that some commits have fixed this issue (and indeed that the same goes for #354)?

**Comment by SebastJava** [comment]
@LinuxOnTheDesktop No, You did not miss anything. You are right, nothing got fixed. Sorry but... I just got tired of waiting. :)
