### ISSUE TITLE
Minor Cursor Bug (tested under Cinnamon) (confirmed under XFCE)

### ISSUE THREAD

**Issue by robsennk** [linuxmint/mint-themes#417]
There is a minor cursor bug through several builds. (tested under vanessa and vera)

Whenever you change your mouse cursor in the themes of mint (tested under cinnamon, but also xfce users report it) it dont take the settings over for the whole system. it still stays default on some programs.

example: you choose the white prox cursor. its shown on the desktop after it and maybe firefox but not other programs like steam. there is still the black cursor.

a: https://ibb.co/WgFQ8rs
b: https://ibb.co/4MnSZ3z

we have found out that you need to manually update the settings in the console, but this should not be the default as it should be done via the themes without fumbling around in the console.

`sudo update-alternatives --config x-cursor-theme`

**detailed threads about it:** 
https://forums.linuxmint.com/viewtopic.php?p=2272182#p2272182
https://forums.linuxmint.com/viewtopic.php?f=211&t=387636

**Comment by clefebvre** [comment]
https://github.com/linuxmint/cinnamon/issues/11341
