### ISSUE TITLE
Dark variant of Mint-Y themes break when setting org.gnome.desktop.inferface.color-scheme to "Prefer-Dark"

### ISSUE THREAD

**Issue by AchillesBoi** [linuxmint/mint-themes#424]
When using the dark variant of Mint-Y themes, libadwaita apps remain in Light mode. To make libadwaita apps switch to Dark mode, one must change org.gnome.desktop.inferface.color-scheme to "Prefer-Dark". This in turn breaks Mint-Y themes but only the Dark variants; regular GTK3 apps will display in the old classic Adwaita theme instead of Mint-Y.

**Comment by JosephMcc** [comment]
I apologize if I missed something but there is no reason to open this issue more than once: https://github.com/linuxmint/mint-themes/issues/420

**Comment by AchillesBoi** [comment]
That's fine, I just thought maybe I wasn't clear enough in the first one since no further communication was made, so I opened a new one and elaborated a bit more.
