### ISSUE TITLE
Selected not in focus state is white text on white background in default theme

### ISSUE THREAD

**Issue by mjohenneken** [linuxmint/mint-themes#448]
The styling for list items selected and not in focus are white text on white background which makes it unreadable. Found this issue in at least in mint-y and mint-y-aqua

Related: https://github.com/qgis/QGIS/issues/53735

**Comment by mjohenneken** [comment]
It seems to apply to all mint-y variants in light mode. However i cloud find this issue so far only in QGIS

**Comment by JosephMcc** [comment]
Make sure you test this with the latest 2.1.5 version of mint-themes. There was a fix that may have taken care of this.

**Comment by mjohenneken** [comment]
Good point I'm running on 2.0.5 which is the latest i can get from apt. I downloaded the 2.1.5 tag. However I can't find information to install it locally. How can i test it?

**Comment by mjohenneken** [comment]
Alright found a way. Just run make and then add it to ~/.themes. 2.1.5 fixes the issue I encountered, thanks!

This is the how it look with the new theme:
![image](https://github.com/linuxmint/mint-themes/assets/5088045/a5908fa6-c59f-4420-af27-29b1747e22a9)
