### ISSUE TITLE
Themes Should End with Lowercase "-dark"

### ISSUE THREAD

**Issue by BlindRepublic** [linuxmint/mint-themes#458]
Mint's theme names should end with `-dark` (explicitly with a lowercase `d`) as `webkitgtk` and `libadwaita` check will automatically set their themes to dark mode when the current gtk theme has the suffix `-dark`. Ideally, it would be better for there to be something that explicitly states that the theme is a dark variant in the theme itself, but this would be more convenient than having to constantly run `gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'` when changing themes.

**Comment by clefebvre** [comment]
Light themes support gtk-dark.css so they don't need to be correlated with another theme (i.e. a dark one).
