### ISSUE TITLE
Missing contrast in LibreOffice with any light theme

### ISSUE THREAD

**Issue by ineuw** [linuxmint/mint-themes#467]
Using Linux Mint 21.3 Cinnamon, all light themes lack contrast in LibreOffice toolbar and icons. Please see the image. What can I do to correct this?

![light or dark cinnamon themes with libreoffice](https://github.com/linuxmint/mint-themes/assets/10367016/d72ad8ae-c1c1-4767-aa35-0b070b908aa8)

**Comment by rcalixte** [comment]
Which icon settings are you using for LibreOffice? This seems to come up from time to time as [seen here](https://github.com/linuxmint/mint21.2-beta/issues/30) and it is usually related to the icon theme in use.

**Comment by JosephMcc** [comment]
This really has nothing to do with mint-themes. The styling and look of this cannot be controlled from the gtk themes. It's down to the icon theme you use in LibreOffice as noted in the link that @rcalixte pointed to.

**Comment by ineuw** [comment]
This is out of the box LibreOffice as it was included on the .iso, installed three days ago. All updates were applied. The settings shown below is only one of the many combination I tried, changing them doesn't affect the icons in light mode. It's light on light. I tried all the Series, L, Y, X, etc. LO is not changing the icons to dark for contrast. Who and where should I ask?

Version: 7.3.7.2 / LibreOffice Community
Build ID: 30(Build:2)
CPU threads: 4; OS: Linux 5.15; UI render: default; VCL: gtk3
Locale: en-US (en_US.UTF-8); UI: en-US
Ubuntu package version: 1:7.3.7-0ubuntu0.22.04.4
Calc: threaded

![240204_1849_any selection](https://github.com/linuxmint/mint-themes/assets/10367016/e986073f-3249-425b-bb84-e2f476ad9690)

**Comment by JosephMcc** [comment]
You can change this in LibreOffice itself under Tools->Options. Under "View" you can change the icon style.

**Comment by ineuw** [comment]
Much thanks, issue resolved.

**Comment by AchillesBoi** [comment]
@JosephMcc I think the issue is that LibreOffice already has an option to automatically change the icon theme based on the selected Mint-Y theme (an option which is enabled by default on every Mint release) but it is currently unable to do so correctly. For example, in KDE Neon it is also set to automatically change icon themes based on the selected Plasma theme and it does so as expected, but on Cinnamon it does not.

**Comment by ineuw** [comment]
This issue is not resolved. The current 
```
Version: 24.2.7.2 (X86_64) / LibreOffice Community
Build ID: 420(Build:2)
CPU threads: 4; OS: Linux 6.8; UI render: default; VCL: gtk3
Locale: fr-CA (fr_CA.UTF-8); UI: fr-FR
Ubuntu package version: 4:24.2.7-0ubuntu0.24.04.1
Calc: threaded
```
I am unable to improve the white on white icons in Linux Mint Cinnamon. Changing to a dark theme is not an option. I tried Cinnamon Y, and L. and there is no difference.

> You can change this in LibreOffice itself under Tools->Options. Under "View" you can change the icon style.

Under "View", There is only Colibri.svg that enhances the outline of the icons. Do I have any other choice?

![Image](https://github.com/user-attachments/assets/350d4ee5-756e-4844-83a9-06ac33cebd30)
