### ISSUE TITLE
fretboard balls do not show up

### ISSUE THREAD

**Issue by Kreijstal** [linuxmint/mint-themes#469]
I saw this bug posted, but not sure if it fell on your radar, so here it goes just in case

https://github.com/bragefuglseth/fretboard/issues/30

If it is not needed, feel free to close

**Comment by JosephMcc** [comment]
The app uses libadwaita so shouldn't be getting themed by your user theme unless you are trying to force it. The mint themes have no  support for libadwaita apps.

**Comment by bragefuglseth** [comment]
Fretboard developer here; I suspect that the `GTK_THEME` variable has been set in this case, which is intended for debugging and is very prone to breaking GNOME apps. It should be unset.

**Comment by mtwebster** [comment]
Cinnamon never sets or modifies GTK_THEME (nor does MATE or Xfce, at least in their Mint editions).
