### ISSUE TITLE
Let's update the logo!

### ISSUE THREAD

**Issue by zaharb840** [linuxmint/mint-themes#471]
The Linux Mint logo has a 2010's feel to it. It's high time for a major upgrade! A new logo has been designed by ARYLUNEIX, and I've attached it here. Let's modernize Linux Mint!
![mint_logo_color](https://github.com/linuxmint/mint-themes/assets/136559594/47ab7049-77e3-4bf7-a1a6-b29cd2cd02c1)
![mint_logo_color_text](https://github.com/linuxmint/mint-themes/assets/136559594/1428a116-d122-4244-89f0-7888dd17c043)
![mint_logo_mono](https://github.com/linuxmint/mint-themes/assets/136559594/5477adeb-c6a7-4268-b9b1-00c1f7feb52b)
![mint_logo_mono_text](https://github.com/linuxmint/mint-themes/assets/136559594/f3a0a3d2-a02e-409b-8871-5d5f1cb82b17)

**Comment by masimbadenola** [comment]
Looks amazing! But I think maybe this is the wrong repo to publish this to...

**Comment by zaharb840** [comment]
> Looks amazing! But I think maybe this is the wrong repo to publish this to...

Where i can publish this? Sorry for my bad english.

**Comment by JosephMcc** [comment]
https://github.com/orgs/linuxmint/discussions

**Comment by carlosmintfan** [comment]
Unfortunately...I don't like the logo. I mean, what should that be?

**Comment by carlosmintfan** [comment]
Soo simple...so uninteresting...don't be insulted, but...stupid.

**Comment by akemmanuel** [comment]
I would leave Linux mint if the logo is adopted

**Comment by carbuck** [comment]
This logo sucks
