### ISSUE TITLE
Mint-Y Light themes still have dark terminal colors

### ISSUE THREAD

**Issue by AndreiMiculita** [linuxmint/mint-themes#478]
# Steps to reproduce:
1. (via simplified theme settings) Activate Mint-Y, select "Light", any color
2. Open a terminal, under Edit > Preferences > (current profile) > Colors > make sure "Use colors from system theme" is checked

# Expected behaviour
Terminal should use a light color, such as the ones available when "Use colors from system theme" is unchecked (Black on white, GNOME light, Tango light, Solarized light)

# Actual behaviour
The terminal color is dark (mostly white on black).
![image](https://github.com/user-attachments/assets/5ed2fa02-845a-405d-bf11-520f4e2c3a20)

# Other observations
I could pick one of the light themes for the terminal, but then I have to lose the automatic switch when I change system themes. I switch from light/dark system theme in the day/night so it is convenient to have it automated.

**Comment by JosephMcc** [comment]
Thanks for the suggestion. This is just an artistic choice (which we all know not everyone will like). It seems that most people prefer the dark terminal background even in the light theme. It's possible that this could be changed nowadays with the addition of the "Dark theme" preference that the terminal now has.
