### ISSUE TITLE
Nemo file manager's sidebar background remains always White linux mint 21.2

### ISSUE THREAD

**Issue by stevedonato** [linuxmint/mint-themes#479]
I have the same theme (cinnamon) as my 21.3 cinnamon  which is black, but my 21.2 is white?
I want black. How does this happen by it's self?

**Comment by JosephMcc** [comment]
The Gtk theme changed at some point, don't remember exactly which version, to have a light sidebar instead of dark in Nemo. I believe Mint-X still has the dark sidebar if you'd prefer to use that.

**Comment by stevedonato** [comment]
Just tried your suggestion Mint-x for desktop and min-x-blue for icons still a white background?

**Comment by stevedonato** [comment]
What does the GTK version have to do with Nemo?

**Comment by stevedonato** [comment]
I was asking for the Black not the White background like the issue that was
closed. Nemo has a WHITE sidebar background not a Black one,  I wanted a
blackground. I cannot find a theme that supports a Black background on the
side bar. I don't think GTK has anything to do with the colors of the
background. I know GTK can change the width of scroll bars and the font
size in Thunderbird mail inbox listing.

**Comment by JosephMcc** [comment]
The gtk theme is what controls the colors in applications. Use a different theme for the application theme.

**Comment by stevedonato** [comment]
I always used Mint-L-Blue theme that use to give me the black background on sidebar, unless some update changed it. But that should not be true either because on my other machine where I have mint 21.3, the theme still displays the correct black background on the sidebar. The error theme is on my mint 21.2 machine
