### ISSUE TITLE
linux mint theme missing in 2.2.0-1

### ISSUE THREAD

**Issue by Shawn-Hub** [linuxmint/mint-themes#483]
the linux mint theme is no longer available in the latest update of 2.2.0-1. to get it back you have to downgrade to 2.1.8-1. Using legacy themes are not the same.

**Comment by rcalixte** [comment]
This was an [intentional change](https://github.com/linuxmint/mint-themes/commit/5de93c0c55b98526e90e087afdcb2a4bb78d3070).

**Comment by Shawn-Hub** [comment]
will there be a way to add the linux mint desktop theme in the future or are we just stuck without it?

**Comment by JosephMcc** [comment]
I don't think there are any intentions to bring it back unless someone chooses to make a version of it on Cinnamon Spices.

**Comment by clefebvre** [comment]
People are welcome to copy it and maintain it themselves or on spices indeed, but from a Mint point of view it doesn't make sense to maintain yet another theme in addition to Mint-Y, Mint-X, Mint-L and the default Cinnamon theme.
