### ISSUE TITLE
Window controls scaling issue

### ISSUE THREAD

**Issue by shaicoleman** [linuxmint/mint-themes#56]
The Mint-X window controls do not scale properly.

To replicate the issue:
- Clean install of Linux Mint Cinnamon 17 64-bit
- Preferences > Fonts > Window title font: Sans Bold 40

![image](https://cloud.githubusercontent.com/assets/127225/3322445/cd2829b4-f74a-11e3-81ec-2897e4868a60.png)

**Comment by xenopeek** [comment]
In depends on the theme which issue you face with scaling text. Looking at Linux Mint 18.3 Cinnamon and scaling the window title font the same as, Mint-X zooms the window controls so they become blurry. Mint-Y doesn't zoom the window controls so they remain sharp but in comparison with the window title text look very tiny.

That's not unique to our themes though. AgingGorilla and Crux do the same thing as Mint-X. Bright and Simple do the same thing as Mint-Y. Adwaita and the others appear to scale the window controls without blurry zoom.

**Comment by JosephMcc** [comment]
I'm closing this as it really isn't a theme issue. It's down to how muffin handles them and there isn't a good solution.
