### ISSUE TITLE
Advice for repository organisation

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mint-themes#87]
I advise to create external repo for mint-libreoffice-icon theme, it is already implemented by shimmer project https://github.com/shimmerproject/libreoffice-style-elementary (just copy makefile and adopt paths and names). With zipped file in repo it's hard to create PRs, observe changes and of course git-diff. Also providing SVGs along with PNGs will help a lot (SVGs would be fine for mint-x-icons too)

**Comment by clefebvre** [comment]
libreoffice-style-mint
