### ISSUE TITLE
Mint X icon theme with LibreOffice

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mint-themes#89]
Bamm Gabriana mentioned in a bug report on LibreOffice that he and Clem wanted to push the Mint X icon theme upstream to LibreOffice and i would like to assist with making that happen as i work with the libreoffice design team.

https://bugs.documentfoundation.org/show_bug.cgi?id=72871

Would also like to mention that more toolbar buttons were introduced in LibreOffice 5.0, so the Mint X icon theme would need to be updated, so toolbar icon buttons dont appear as text buttons.

**Comment by Yanpas** [comment]
@philipzae Take a look at my PR :) https://github.com/linuxmint/mint-themes/pull/88

**Comment by philipzae** [comment]
@Yanpas Thanks for the notice. It would be good if a git repo could be created for the theme, so it would be easy to get to the latest updates easily.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/libreoffice-style-mint
