### ISSUE TITLE
Special theme for not-so-hi-dpi screens

### ISSUE THREAD

**Issue by yesint** [linuxmint/mint-themes#90]
Cinnamon currently has an option for x2 UI scaling. This is perfect for QHD screens, but not for Full HD 13.3 with 1920x1080. For such screens x1 scaling is too small and x2 is too large. x1.5 will be ideal but GTK can't do this.

It is possible to solve the problem partially by setting font scaling to 1.8-1.9 but this does not scale checkboxes, radio buttons, scrollbars and various icons - they all remain too small.

My idea is to provide a special variant of the default theme for such screens where all icons, bitmaps and controls are 1.5 larger. What need to be increased:

- Bitmaps for checkboxes and radiobuttons
- Scrollbars and sliders
- Toolbar icons from 16x16 to 24x24.
- Icons in treeview and such.

Unfortunately my knowledge of GTK themes is clearly not enough to do this but this task is easy for any theme developer.

I opened a feature request on GitHub https://github.com/linuxmint/Cinnamon/issues/4632 but it was closed immediately with the comment "Cinnamon developers don't produce themes".
So, I'm opening it here - probably this is the right place.

**Comment by JosephMcc** [comment]
> Unfortunately my knowledge of GTK themes is clearly not enough to do this but this task is easy for any theme developer.

If you don't know much about GTK themes, what makes you think it's easy. Doing what you're asking is a time consuming task. Even after such a theme was created, it would then have to be maintained. That takes up even more time. We already maintain a decent number of themes. If we are going to have more I would prefer to spend the time on something more people would find useful. I'm also not sure all of it would be entirely possible. Not with good results.

**Comment by yesint** [comment]
Well, I did a quick test and managed to increase  checkboxes, radiobuttons, scrollbars and sliders. There are still glitches here and there, but in general it works. What I don't understand is how to force the size of toolbar icons. Based on this I guessed that this work should not be so hard for a theme developer, who understand how it works (I don't actually). Of course I may be wrong, but the problem will become more and more important since the number of such screens is increasing.

**Comment by JosephMcc** [comment]
Regardless of weather or not this is possible to do, I doubt it's going to be done any time soon for the reasons I mentioned above. If you purchase a 13'' screen with a full HD res, your interface is going to be small. Not really sure what else you expected.
