### ISSUE TITLE
nemo left side shadow display problem

### ISSUE THREAD

**Issue by yuwtrue** [linuxmint/mint-themes#97]
it display as a color
 block not a shadow.
I am using arch and the last version of  cinnamon and nemo and mint themes 1.4.5
![2015-12-14 00-00-20](https://cloud.githubusercontent.com/assets/1270490/11767837/4d53641c-a1f6-11e5-89d0-483ff2e47d3c.png)

**Comment by JosephMcc** [comment]
Mint themes are designed for Linux MInt which uses gtk3.10 and LMDE which supports 3.14 at the moment. The issue your having is due to a newer gtk version than the theme supports.

**Comment by GLolol** [comment]
Related: linuxmint/mint-themes-gtk3#60 (you may want to try and apply the patch there, and install from source)
