### ISSUE TITLE
No visual feedback (focus borders) when using keyboard navigation

### ISSUE THREAD

**Issue by Piiit** [linuxmint/mint-themes#98]
No visual feedback (focus borders) when using keyboard navigation. In other themes, like for example Adwaita you can see where your current focus is when using keyboard short cuts and tab-navigation. It seems that this is a design-decision for the mint-x theme, but I think that keyboard navigation is an all-day task (not only for power-users). If someone wants to use the keyboard there must be some visual feedback, otherwise it seems incomplete. At least in my opinion. Therefore, it would be really nice to have it as default. Or, if the first suggestion is not possible, to have an option to set it from cinnamon settings, maybe as a "mint-x-for-keyboard-navigation" theme or something similar.

Thanks.

I posted this issue already (maybe at a wrong place) under https://github.com/linuxmint/mint-x-theme/issues/6

**Comment by Yanpas** [comment]
What do yo mean by visual navigation? Can you provide steps to reproduce and screenshots?

**Comment by Piiit** [comment]
As you can see in these two screenshots, there is no visual feedback while navigating with the keyboard over the config-menu of gedit with Mint-X. When I press 2 times TABULATOR I do not know where I am on the menus. However, when I do the same with Adwaita I have a border around "Zeilennummern einfügen". This is really important to me, because to be fast I like to use keyboard navigation with such dialogs.

With MintX theme:
![einstellungen_005](https://cloud.githubusercontent.com/assets/6096063/13007043/982dc8a8-d18d-11e5-8db4-5beadfe07907.jpg)

With Adwaita theme:
![einstellungen_006](https://cloud.githubusercontent.com/assets/6096063/13007037/87489a5e-d18d-11e5-9e19-dfbe1e0e387b.jpg)

I hope that helps. Otherwise just drop another comment...

Cheers!

**Comment by Yanpas** [comment]
the good news, I've found a solution:

> You should midify this file `/usr/share/themes/Mint-X/gtk-2.0/styles/buttons.rc`, focus function (scroll to the bottom)
```
image
        {
            function = FOCUS
            shadow = IN
        }
```

the bad news: 
* ugly dotted border appears everywhere
* this won't work in gtk3 apps
* moreover this theme support is ended due to Mint 18 will be using new themes.

PS: maybe dropping pixmap engine is good idea, murrine engine seems for me to be more flexible

**Comment by JosephMcc** [comment]
Not having the focus borders is a design decision. They were removed on purpose though I understand why some people want them.

While new themes are being looked at for Mint18 they are meant to be in addition to Mint-X. I'm currently already in the process of updating it for gtk3.18.

@Yanpas in most ways the pixmap engine is far more flexible than the murrine engine, just not as simple to work with.

**Comment by Yanpas** [comment]
It's a pitty to hear. Hope theme in 18 will highlight entries. In my opinion theme **must not** deprive user of any possibilities in favor of beaty.

**Comment by Piiit** [comment]
@Yanpas I have the same opinion. I think keyboard navigation without these highlighting borders is really limited. To my understanding design decisions must have a lower priority than reducing functionality. I see that dotted lines are not beautiful, maybe we can find another solution in design. However, I think that this is a minor problem. Not to know where the focus is currently, is a bug or a missing feature at least. 

Maybe we could just say that Mint-X did not have any borders, also in the future, but new themes should have them...

ps. @Yanpas Thanks for the workaround...

**Comment by Piiit** [comment]
We have these borders now in Mint-Y, since there are no plans to introduce them in Mint-X too, we can close this issue.
