### ISSUE TITLE
Mint-X theme on window borders produces unacceptable text when antialiasing is turned on

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/mint-themes#99]
The text in question is the text in windows' titlebars; and this happens with every font I have tried and is worse when using bold. The visual defect is that antialiasing (on any settings save 'off', I think) produces a strong white outline at the bottom of the letters.

The problem is particularly serious since Mint-X is, I think, the default theme on Mint Cinnamon and, further, because Mint-X is a good theme and there is no similar theme, to my knowledge.

A few further details are here: https://github.com/linuxmint/Cinnamon/issues/4836.

**Comment by JosephMcc** [comment]
The white outline is an intentional text shadow. It's just a style choice. I'm not sure that classifying it as "unacceptable" is very accurate as I've not seen any other complaints about it.

**Comment by ACinnamonUserInUK** [comment]
'Unacceptable' might have been too strong. Still, I find it hard too see how anyone with an eye for aesthetic detail would not be put off by the shadowing, at least given the dotted line that the shadowing forms under words. At any rate, is this a risk to be taken with new users of Mint?

I would be pleased were you to offer an alternative, non-shadowed version of the theme. Failing that, could you tell me how to disable the shadow myself, please?
